### ISSUE TITLE
INSPIRE WMS - Legend URL

### ISSUE THREAD

**Issue by Dnoack49** [INSPIRE-MIF/helpdesk-validator#1019]
Dear all, 

we are trying to validate the following WMS (using the production and staging instance):
https://inspire.brandenburg.de/services/el_gmk_wms?request=GetCapabilities&service=WMS 

and we receive the error:
`The legend format is invalid. The validator is expecting 'image/png', but the defined legend format is 'text/xml; charset=UTF-8'. Please, review your code and try again.`
![grafik](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/8046960/eb91051c-80a2-4a7d-8d01-af97f570566b)

However the Legen URL Format is set to` image/png`
Is this really an error? Could you please provide us with some guidance on what needs to be changed?

Kind regards

**Comment by fabiovinci** [comment]
Dear @Dnoack49,

according to the related test method "[Layer Style Legend URL](https://github.com/inspire-eu-validation/view-service/blob/master/iso-19128/at47-getcapabilities-layer-style-legend-url.md#style)", the validator checks that all the responses of the LegendURLs are valid images.

In your case, some LegendURL links are not working (the response is "_text/xml; charset=UTF-8_" instead of "_image/png_"), e.g. https://inspire.brandenburg.de/services/gmk_wms?language=ger&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=el_isobathdense&format=image/png&STYLE=%22%20xmlns:xlink=%22http://www.w3.org/1999/xlink

So, you need to check your WMS settings.

**Comment by Dnoack49** [comment]
Alright thank you very much, we will check our configuration. In case I have further questions I will reopen the issue.
