### ISSUE TITLE
Validator v. 2024.0 fails when choosing "Conformance Class 2c: 'INSPIRE data sets and data set series metadata for IACS'"

### ISSUE THREAD

**Issue by dhdeangelis** [INSPIRE-MIF/helpdesk-validator#1033]
The latest version of the validator, 2024.0, throws an error when choosing Conformance Class 2c: 'INSPIRE data sets and data set series metadata for IACS.

This error does not happen if IACS conformance class is not chosen. The error happens when running from both a local docker instance or the public instance.

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/51515911/9428dc6e-61c8-41ce-9f57-cb5eb195b950)

**Comment by fabiovinci** [comment]
Dear @dhdeangelis,

thank you for the notification, we will fix it asap.

**Comment by DanielMartinPerezdeLeon** [comment]
Dear @dhdeangelis,

Thank you for bringing the issue to our attention. After a thorough investigation, we've identified the root cause of the problem.

Rest assured, we've implemented the necessary fix and will promptly upload it to the [validator-ui repository](https://github.com/inspire-eu-validation/INSPIRE-Validator-UI/tree/staging). In the meantime, we encourage you to utilize our [staging environment](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) to try it and continue with your tests.

Should you have any further questions or concerns, feel free to reach out.

Best regards,

**Comment by dhdeangelis** [comment]
@fabiovinci thanks, I see this is tagged as ready for testing. Is it ready now or should I wait for a new release?

**Comment by DanielMartinPerezdeLeon** [comment]
> @fabiovinci thanks, I see this is ready for testing now or should I wait for a release?

@dhdeangelis You can test this in the [staging-environment](https://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) while we upload the new release

Regards,

**Comment by dhdeangelis** [comment]
I can confirm that the issue is solved in the staging instance. It is possible to test without the error described in the original post.

Thank you @DanielMartinPerezdeLeon and @fabiovinci 

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/51515911/67b982eb-fe6b-4526-9be4-09d196b21bda)

**Comment by fabiovinci** [comment]
The fix for this issue is now available in the [production instance](https://inspire.ec.europa.eu/validator/home/index.html).
For further details, please visit the [v2024.0.1 release notes](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2024.0.1).
