### ISSUE TITLE
Problems accessing the INSPIRE Validator Web page

### ISSUE THREAD

**Issue by montsemarco** [INSPIRE-MIF/helpdesk-validator#1053]
When trying to open the [INSPIRE Validato](https://inspire.ec.europa.eu/validator/home/index.html)r from a computer that is inside of my Organization ([www.diba.cat](http://www.diba.cat/))  the Web page is unformatted, therefore, cannot be used. I attach a screenhot.

Our computer science department suggest that the problem is that our corporative IP is blocked. Can you help me to solve this problem?

![image](https://github.com/INSPIRE-MIF/helpdesk/assets/1905272/b891ca2c-d5dc-4f9e-acf3-424179e1759c)

Thanks and best regards,

**Comment by fabiovinci** [comment]
Dear @montsemarco,

we have checked the access to the INSPIRE Reference Validator, and it is publicly available.

With the information provided, if the issue is sporadic, it may have been caused by a temporary unavailability of the INSPIRE Reference Validator due to an overload. 
If this issue persists over time, then it may be related to a rule or access restriction in your environment.

We kindly suggest checking access to the INSPIRE Reference Validator to confirm if the issue is still present and if it occurs consistently over time.

With the results obtained, please update this issue to help us determine the cause and ensure access to the INSPIRE Reference Validator.

**Comment by montsemarco** [comment]
I checked the access to the INSPIRE Reference Validator and now the issue is not present.

This issue persists over time, but I guess that no changes has been done in our infraestructure. However, the fact is that now it's working and I can acces the validator from our Organization.

Thanks for your help and best regards

**Comment by montsemarco** [comment]
I close the issue
