### ISSUE TITLE
GMX:Anchor vs gco characterstring

### ISSUE THREAD

**Issue by dlutsVMM** [INSPIRE-MIF/helpdesk-validator#107]
This is the second part of issue 106

The second problem I can't figure out has less to do with the validator and more with Geonetwork. Geonetwork uses gmx:anchor for its internal reference in the xml to the thesaurus used for a keyword. This results in a schema validations error. I have tried to use the options in Geonetwork to try to force it to use gco:characterstring instead of gmx:anchor, but for some reason it keeps changing back to gmx. Any suggestions/experiences on this topic would be very usefull.

In the attachments I have provided the draft version of the  xml as a docx and the test report.

[testreporthtml.docx](https://github.com/inspire-eu-validation/community/files/3574834/testreporthtml.docx)

[3c3e9731-819a-4ad6-8635-ac9ef52d6b2f.docx](https://github.com/inspire-eu-validation/community/files/3574815/3c3e9731-819a-4ad6-8635-ac9ef52d6b2f.docx)

**Comment by MarcoMinghini** [comment]
@dlutsVMM since this looks like a software-specific issue, please open a thread in the new INSPIRE Community Forum, where there is a dedicated section on Software & Tools: https://inspire.ec.europa.eu/forum/tcc

Other INSPIRE implementers using GeoNetwork and the same GeoNetwork team are active there and should be able to help you.

If this does not help, you may also open an issue in the [GeoNetwork helpdesk](https://github.com/geonetwork/core-geonetwork/issues) on GitHub.

**Comment by dlutsVMM** [comment]
Dear Marco,

Thanks for the pointers.
