### ISSUE TITLE
Annex III - Natural risk zones (NZ) - Dataset validation

### ISSUE THREAD

**Issue by lukastemberga** [INSPIRE-MIF/helpdesk-validator#1075]
Hi,

I'm trying to validate dataset for theme Natural risk zones (NZ) - Annex III. I'm able to pass all automatic tests except for:
`Conformance class: GML application schemas, Natural Risk Zones -> Basic test -> nz-gml.a.1: Feature in dataset`
[link](https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EIDc133e115-edfd-42c2-a783-79d946033605.html?lang=en#EID564ce9d3-77f0-4d09-92e4-a333bee43bfb)

The test returns an error stating:

> The XML documents representing the spatial data set do not contain a feature of any of the spatial object types in the 'Natural Risk Zones' application schemas. Therefore, the spatial data set cannot conform to this conformance class. If you have expected to find spatial objects from the application schema in the data set, please consult the statistics information to see the spatial object types that have been found.

I'm pretty sure my GML file contains proper feature of type `nz-core:RiskZone`. Also, looking at the statistics there are 20 features present and all are of RiskZone type.

Looking at the test condition for the test:
```
let $featuresFromAppSchema := $features[descendant-or-self::nz-core:ExposedElement 
| descendant-or-self::nz-core:HazardArea 
| descendant-or-self::nz-core:ObservedEvent 
| descendant-or-self::nz-core:RiskZone    /* This shall make it true ? */
| descendant-or-self::nz-core:ExposedElementCoverage 
| descendant-or-self::nz-core:HazardCoverage 
| descendant-or-self::nz-core:ObservedEventCoverage 
| descendant-or-self::nz-core:RiskCoverage]
return
	(if ($featuresFromAppSchema) then 'PASSED' else 'FAILED',
	if (not($featuresFromAppSchema)) then local:addMessage('TR.noFeature', map { 'theme': 'Natural Risk Zones' }) else ())
```
To my understanding `descendant-or-self::nz-core:RiskZone` shall be tested positive against XML tag `<nz-core:RiskZone gml:id="NZ_FloodRisk.5"> ... `

Is there a problem with my dataset or is this an validator error?
I have tried comparing this dataset against other datasets (other themes) that do pass validation without problems and I can't seem to find some major difference.
Thanks for your help in advance!

Test dataset and validation result:
[validation.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/15196887/validation.zip)

**Comment by fabiovinci** [comment]
Dear @lukastemberga,

this type of error occurs, now, for data themes that were updated to major version 5.0, such as NZ.
We are investigating why the error appears.

In the meantime, the error disappears if you update your dataset to the new version 5.

Please find in the screenshot below the changes I introduced in your test dataset:

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/22212406/36ce0fa6-5556-47e2-a89f-f1275e31a7c6)

In your case, the changes are related only to the namespaces since there are no attributes for which the datatype was changed (i.e. attributes for which the datatype changed from enumeration to codelist). 

Attached are the modified dataset and the validation report: [test_v5.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/15200779/test_v5.zip)

**Comment by lukastemberga** [comment]
@fabiovinci thank you for your help, I have adjusted schema URLs to what you suggested. It all works fine now.
