### ISSUE TITLE
Errores Tema Land Cover (LC)

### ISSUE THREAD

**Issue by CristinaMSL** [INSPIRE-MIF/helpdesk-validator#1102]
Good morning.

I am trying to adapt some data to inspire for the Land Coverage theme.
Once I get the gml and validate it, the following errors appear:

"Invalid content was found starting with element '{"http://inspire.ec.europa.eu/schemas/lcn/4.0":LandCoverNomenclature}'. One of '{"http://inspire.ec.europa.eu/schemas/lcn/5.0":LandCoverNomenclature}' is expected."

![image](https://github.com/user-attachments/assets/8f8834e1-ef34-4582-8e4f-c971c8fe1a9e)

I am not very clear what you are referring to... the only thing I could see is that in the field “nomenclatureDocumentation” has version 5.0 and from the field “LandCoverNomenclature” have version 4.0 (embeddedDescription, externalDescription, inspireId, nomenclatureCodeList and responsibleParty).

Is this the reason for these errors or is it something else?

I have used the xsd schema in its 5.0 version to make the relations and get the gml.
Dejo anexo al mensaje el gml que he utilizado para validar.

Translated with DeepL.com (free version)
[prueba2-8.zip](https://github.com/user-attachments/files/16346286/prueba2-8.zip)

I'm waiting for your answer. Thank you very much in advance.

**Comment by fabiovinci** [comment]
Dear @CristinaMSL,

I had a look at your GML file and it seems there are some errors with namespaces:

- xmlns:lcn="http://inspire.ec.europa.eu/schemas/lcn/4.0" should be xmlns:lcn="http://inspire.ec.europa.eu/schemas/lcn/5.0"
- xmlns:ns2="http://inspire.ec.europa.eu/schemas/base/3.3" should be removed since the related new one namespace (xmlns:base="http://inspire.ec.europa.eu/schemas/base/4.0") is already present.
- the declarations of the "ns2" namespace should be replaced by "base" namespace

In addition, please note that the element `<lcv:nomenclatureDocumentation/>` shall not be empty.

Find attached a [valid](https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID2ee6c132-8430-4225-8e25-90ae5165db6f) sample extracted from your GML file.
[prueba2-8.0001_sample.gml.zip](https://github.com/user-attachments/files/16346737/prueba2-8.0001_sample.gml.zip)

**Comment by CristinaMSL** [comment]
Hello again Fabio.

Thank you very much for your answer.

The first two points you have indicated, I have applied them and the error has been removed.
But regarding “Also, please note that the <lcv:nomenclatureDocumentation/> element must not be empty.”. The part corresponding to this field, gives me several errors that I don't quite know how to interpret. I have related all the obligatory fields and even so, an error still appears. What can this be due to? What am I doing wrong?

The errors are as follows:

 -Invalid content was found starting with element 'base2:LegislationCitation'. No child element is expected at this point.
-XML document 'prueba2-15-conectadndododoloqeupuedo.0001.gml': 168:47: cvc-complex-type.2.4.b: The content of element 'lcv:nomenclatureDocumentation' is not complete. One of '{“http://inspire.ec.europa.eu/schemas/lcn/5.0”:LandCoverNomenclature}' is expected.

Below I leave a zip with the gml and the test report with the errors.
Thank you very much in advance.


[Uploading prueba2-15-conectadndotodoloqeupuedo.zip…]()

**Comment by CristinaMSL** [comment]
Hello @fabiovinci 

I have continued testing and as I understand from the Land Cover theme documentation and the Inspire schematic elements loaded into the Hale Studio tool:

-The box with the question mark, indicates that from the Choice Group only one of the specified properties is allowed as a child. That is, from “”externalDescription - DocumentCitation” ” only DocumentCitation or LegislationCitation can be chosen.

I have tried to do this by selecting only DocumentCitation and relating only the name field. -> I get the error XML document 'prueba2-21-solodocumentcitationcon name.0001.gml': 141:47: cvc-complex-type.2.4.b: The content of element 'lcv:nomenclatureDocumentation' is not complete. One of '{“http://inspire.ec.europa.eu/schemas/lcn/5.0”:LandCoverNomenclature}' is expected.

[prueba2-21-solodocumentcitationcon name.zip](https://github.com/user-attachments/files/16362122/prueba2-21-solodocumentcitationcon.name.zip)


If I do the same, for LegislationCitation and relating only the field level and name. I get the same error again.

[prueba2-21-sololegislationcitationnameylevel.zip](https://github.com/user-attachments/files/16362127/prueba2-21-sololegislationcitationnameylevel.zip)


The truth is that I don't know what to do to fix this error, could you help me?

Thank you very much in advance.

**Comment by fabiovinci** [comment]
Dear @CristinaMSL,

looking at the first dataset, it seems you are nesting too much feature types, since there is a <lcv:LandCoverDataset>, inside the <lcv:member>/<lcv:LandCoverUnit>, taht contains a void <lcv:nomenclatureDocumentation/> element.


![image](https://github.com/user-attachments/assets/70cf3e76-1e34-491a-ba6c-3dfa1852f527)

You need to review the process that generated the dataset.

**Comment by fabiovinci** [comment]
Dear user,

we hope the solution provided helps you resolve the issue.
So we close this issue.
If there are any further questions or problems, please do not hesitate to reopen it or create a new issue.
