### ISSUE TITLE
Metadata 2.0: error with wrong reference to the metadata element Conditions applying to access and use

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/helpdesk-validator#111]
While testing a dataset metadata 2.0 XML file, I noticed that an error returned is incorrectly referred to the metadata element 'Conditions applying to access and use' instead of the metadata element 'Limitations on public access'.

Here the Test Report: http://inspire.ec.europa.eu/validator/v2/TestRuns/EID257e9e07-f305-4251-ad85-295439cfd3bd.html

Here the XML file tested: 
[esempio_liguria_2.0.zip](https://github.com/inspire-eu-validation/community/files/3583504/esempio_liguria_2.0.zip)

The two metadata elements mentioned above are documented as follows:

```
<!-- documentation of Limitations on public access -->
<gmd:resourceConstraints>
   <gmd:MD_LegalConstraints>
      <gmd:accessConstraints>
         <gmd:MD_RestrictionCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions">otherRestrictions</gmd:MD_RestrictionCode>
      </gmd:accessConstraints>
      <gmd:otherConstraints>
         <gco:CharacterString>Dato pubblico</gco:CharacterString>
      </gmd:otherConstraints>
   </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>

<!-- documentation of Conditions applying to access and use -->
<gmd:resourceConstraints>
   <gmd:MD_LegalConstraints>
      <gmd:useConstraints>
         <gmd:MD_RestrictionCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions">otherRestrictions</gmd:MD_RestrictionCode>
      </gmd:useConstraints>
      <gmd:otherConstraints>
         <gco:CharacterString>Dati forniti secondo licenza "CC BY 3.0" - http://creativecommons.org/licenses/by/3.0/deed.it</gco:CharacterString>
      </gmd:otherConstraints>
   </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```

The error should be that the gmd:otherConstraints element used to document Limitations on public access (in the first instance of gmd:resourceConstraints) includes a free-text element instead of a gmx:Anchor element, as required in the TG Requirement C.17.
Instead, in the test report the error returned (see the Assertion URI http://inspire.ec.europa.eu/validator/v2/TestRuns/EID257e9e07-f305-4251-ad85-295439cfd3bd.html?lang=it#EID18caeee3-4ad1-4513-9784-68855129e4f5) refers to the metadata element 'Conditions applying on access and use' that is properly documented and consistent with the TG requirement C.18.

**Comment by josemasensio** [comment]
Dear @AntoRot,

Thanks, looks like the validator does not distinguish between `gmd:resourceConstraints`, so even if you have more than one `gmd:resourceConstraints` and into those you have different `gmd:MD_LegalConstraints`, the validator does not see that and raise an error.

We will come bat to you when this is on the staging environment. 

Best regards.

**Comment by josemasensio** [comment]
Dear @AntoRot 
We have checked and we made the corresponding changes.

You can check it on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). If this does not work, please check it later.

Best regards.

**Comment by AntoRot** [comment]
Dear @josemasensio 

I checked again the file but it seems that the changes are not applied.

I will try later.

Best regards.

**Comment by josemasensio** [comment]
Dear @AntoRot,

You have to change below your access constraint to `Anchor` instead of `Character String`. 

Best regards.

**Comment by AntoRot** [comment]
Dear @josemasensio 

If you refer to the first instance of `<gmd:resourceConstraints>`, I know, but I deliberately used `CharacterString` instead of `Anchor` for the otherConstraints element in order to report that the error raised is not proper since it is incorrectly referred to the metadata element 'Conditions applying to access and use' and not to the metadata element 'Limitations on public access'.

If you refer to the second instance of `<gmd:resourceConstraints>`, based on the TG req C.18, the otherConstraints element can include both an Anchor element and a non-empty Free Text element. Consequently no error should be raised.

Best regards.

**Comment by josemasensio** [comment]
Dear @AntoRot,

We have checked again and now should be working. 


Best regards

**Comment by AntoRot** [comment]
Dear @josemasensio,

Now 2 errors are raised, for both metadata elements ('Limitations on public access' and 'Conditions applying to access and use'). See the test Report: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID61124d87-0ddc-4440-b141-25862a3ab0b6.html

But only the error on the 'Limitations on public access' element should be raised, as 'Conditions applying on access and use' metadata element is properly documented.

Best regards

**Comment by MarcoMinghini** [comment]
Dear @AntoRot,

looking at the Requirements C.17 and C.18 of the TG, it seems that there is no possibility for the Validator to distinguish between the two different metadata elements ('Limitations on public access' and 'Conditions applying to access and use').

In fact:
- C.17 on 'Limitations on public access' requires both the element `gmd:accessConstraints` and the use of the `gmx:Anchor` encoding
- C.18 on 'Conditions applying to access and use' states that 
> One instance of either gmd:accessConstraints or gmd:useConstraints element shall be given

which means that `gmd:accessConstraints` can again be used, and a `gmx:Anchor` may not be used (since also a `gco:CharacterString` is allowed). 

Therefore, the Validator has no way to distinguish to which case ('Limitations on public access' or 'Conditions applying to access and use') the element refers to. This should be the reason why no error was raised.

@josemasensio are the two cases distinguished in the ETS? if yes, how?

**Comment by AntoRot** [comment]
Dear @MarcoMinghini,

> looking at the Requirements C.17 and C.18 of the TG, it seems that there is no possibility for the Validator to distinguish between the two different metadata elements ('Limitations on public access' and 'Conditions applying to access and use').

That could be true if the `gmd:accessConstraints` element is used both for 'Limitations on public access' and for 'Conditions applying to access and use'. 
In that case the possible options could be:
- both the `otherConstraints` elements include free text elements. In this case, an error should be raised for the 'Limitations on public access';
- one `otherConstraints` element includes an Anchor element and the other `otherConstraints` element includes a free text element. In this case, if the validator check that the Anchor element properly points to one of the values from the code list ConditionsApplyingToAccessAndUse, then it should raise an error for the 'Limitations on public access' element. If, on the contrary, the Anchor element properly points to one of the values from the code list LimitationsOnPublicAccess, then no error should be raised. If the Anchor element doesn't point to a valid value coming from the mentioned code lists, then also this error should be raised;
- both the `otherConstraints` elements include an Anchor element. In this case, the validator should check that those Anchor elements point to a valid value from the mentioned code lists and, moreover, that both Anchor elements don't point to the same code list.

But, if the `gmd:useConstraints` element is used for 'Conditions applying to access and use' (as in the case of the example I checked) then the validator should distinguish that the `gmd:accessConstraints` refers to 'Limitations on public access' and consequently the errors should be properly raised.

**Comment by AntoRot** [comment]
Dear @josemasensio,

I checked the different options I described in the comment above.
Please find the checks performed in the table below. With regard to the tests referred to in rows 1 and 2, the errors are not properly raised yet.

ID | Limitations on public access | Conditions applying to access   and use | Error raised in the validator | Error that should be raised | Test Report links
-- | -- | -- | -- | -- | --
1 | accessConstraints='otherRestrictions' -->   otherConstraints -->   free text | useConstraints='otherRestrictions'  -->   otherConstraints -->   free text | Error both on Limitations on public   access and on Conditions applying   to access and use | Error only on Limitations on   public access | http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID07094531-2b49-4b9d-afa3-47857b159d9b.html
2 | accessConstraints='otherRestrictions' -->   otherConstraints -->   free text | accessConstraints='otherRestrictions' -->   otherConstraints -->   free text | Error both on Limitations on   public access and on Conditions   applying to access and use | Error only on Limitations on   public access | http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDba3ab306-1e8b-4521-a751-23cb9e26a043.html
3 | accessConstraints='otherRestrictions' -->   otherConstraints -->   Anchor | useConstraints='otherRestrictions' -->   otherConstraints -->   free text | No error | No error | http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID7172f953-18cb-4de8-8a33-bb6fa15754de.html
4 | accessConstraints='otherRestrictions' -->   otherConstraints -->   Anchor | accessConstraints='otherRestrictions' -->   otherConstraints -->  free text | No error | No error | http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDd33dc754-9f24-4fa7-9e06-59b4f05d629b.html
5 | accessConstraints='otherRestrictions' -->   otherConstraints -->   free text | accessConstraints='otherRestrictions' -->   otherConstraints -->   Anchor | Error on Limitations on public   access | Error on Limitations on public   access | http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID9100b8ad-04de-47a3-b483-6cf2d019eb39.html
6 | accessConstraints='otherRestrictions' -->   otherConstraints -->   Anchor (pointing to a wrong value and consequently a wrong URI) | accessConstraints='otherRestrictions' -->  otherConstraints -->   Anchor | Error on Limitations on public   access | Error on Limitations on public   access | http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID2658ea05-58a3-44ee-b1c6-e5dc0f67cb46.html

**Comment by josemasensio** [comment]
Dear @AntoRot,

Referring to the test 1 and 2 is raising a `Conditions of access and use` error because as is described on the ATS, the [Conditions for Access and Use](https://github.com/inspire-eu-validation/metadata/blob/2.0/common/conditions-for-access-and-use.md) required exactly one `AccessConstraint` or `UseConstraint` with at least one `otherConstraint` element with a non-empty free text. In both test are two elements with the requirements for the `Conditions of access and use` and no element for Limitations on public access, so this is the reason why the errors are raised.

Best regards.

**Comment by AntoRot** [comment]
Dear @josemasensio,

The two elements you refer to being used for `Conditions applying to access and use` are included in two different instance of `gmd:resourceConstraints/gmd:MD_LegalConstraints` element, accordingly to what stated by the TG requirements C.17 and C.18 (i.e.
 
> This element shall not be the same one as used for describing conditions applying to access and use
 
in the TG req C.17 and
 
> This element shall not be the same used for describing limitations on public access
 
in the TG req C.18).

Consequently, one instance of `gmd:resourceConstraints/gmd:MD_LegalConstraints` is to be intended as used to document the `Limitations on public access` and the other one to document `Conditions applying to access and use`.

In the test 1, the instance of `gmd:resourceConstraints/gmd:MD_LegalConstraints` that includes the `useConstraints` element is unequivocally to be referred to `Conditions applying to access and use` (as `useConstraints` element can't be used for `Limitations on public access`). Consequently, the other instance of `gmd:resourceConstraints/gmd:MD_LegalConstraints` (that includes the `accessConstraints` element) is to be referred to `Limitations on public access`. So, no error should be raised for `Conditions applying to access and use` but only for `Limitations on public access` (as `otherConstraints` includes a free text element not allowed for `Limitations on public access`).

In the test 2, `accessConstraints` element is used both for `Limitations on public access` and for `Conditions applying to access and use`. In this case, it could be harder to distinguish what  metadata element (`Limitations on public access` or `Conditions applying to access and use`) each instance of `gmd:resourceConstraints/gmd:MD_LegalConstraints` refers to. But, as in both cases the `otherConstraints` elements include a free text element (allowed only for `Conditions applying to access and use`), consequently, again, no error should be raised for `Conditions applying to access and use` but only for `Limitations on public access`.

Best regards.

**Comment by josemasensio** [comment]
Dear @AntoRot ,

In the test 1, there are two gmd:resourceConstraints/gmd:MD_LegalConstraints elements one that includes the useConstraints and another one that includes accessConstraints. It raises errors for C.17 and C.18 because of:

- C.17: There is not one gmd:resourceConstraints/gmd:MD_LegalConstraints element that includes the accessConstraints with an anchor in otherConstraints.

- C.18: There is one gmd:resourceConstraints/gmd:MD_LegalConstraints element that includes the useConstraints, but there is also one gmd:resourceConstraints/gmd:MD_LegalConstraints element that includes the accessConstraints with a free text in otherConstraints, then it is treated as Conditions applying to access and use, beacuse of that we will have two gmd:MD_LegalConstraints for Conditions applying to access and use when only one must be in the metadata.

In the test 2, you get errors for both C.17 and C.18 because the two gmd:resourceConstraints/gmd:MD_LegalConstraints that includes accessConstraints have a free text in their respective otherConstraints. Then the two of them are considered as Conditions applying to access and use, because for Limitations on public access the otherConstraints must contain an anchor.

Best Regards

**Comment by MarcoMinghini** [comment]
Dear @josemasensio, 
the explanation provided by @AntoRot is correct. Both cases 1 and 2 should only raise an error for Requirement C.17 (Limitations on public access). No error should be raised for Requirement C.18 (Conditions applying to access and use), since it can be unequivocally understood:

- in case 1, that the only instance of `accessConstraints` refers to C.18
- in case 2, that the instance of `accessConstraints` with free text refers to C.18

I understand your approach, but the point here is that the ETS (and, as a consequence, the 2 ATS) should be modified to take into account both the Requirements _together_.

Please let us know when the solution is implemened.

**Comment by AntoRot** [comment]
Dear @josemasensio,

I checked again the different options included in the table above and now all errors are properly raised.

Nevertheless, I noticed that in the tests performed, all test cases included in the conformance classes 1 and 2 failed without any valid reason, with the same error message (i.e. 

> "System error in the Executable Test Suite. Please contact a system administrator. Error information:
> [err:XPST0003] Expecting ')', found 'n'. 
>  (189/14)"

)
for all assertions.
See one of the test report: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDb0e29ca9-9329-4fec-b425-b5f43b9bfebc.html

Thank you,
Antonio

**Comment by josemasensio** [comment]
Dear @AntoRot,

Thank you for your report. Please, can you try again later? The validator has to be updated and it will take a while until the changes are applied. We will come back to you when the changes are available.

Best regards.

**Comment by juanpelegrina** [comment]
Dear @AntoRot 

We have already reloaded staging instance so the solution implemented is ready for testing. We have internally tested and works as expected, could you verify it? we are planning a release soon and we intend to include this issue on this [milestone](https://github.com/inspire-eu-validation/community/milestone/1)

Regards

**Comment by AntoRot** [comment]
Dear @juanpelegrina,
 
I checked again the different options included in the table above and now all works fine.

Regards
