### ISSUE TITLE
INSPIRE Validator returns error Code list http://inspire.ec.europa.eu/theme cannot be accessed.

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#1124]
Dear all,

can someone check why INSPIRE Validator returns errors when validating metadata for INSPIRE code lists:

Code list http://inspire.ec.europa.eu/theme cannot be accessed.
Code list http://inspire.ec.europa.eu/metadata-codelist/SpatialScope cannot be accessed. 

Thank you.

Kind regards,
Ana

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

thank you for reporting the error.

We will take a look as soon as possible.

**Comment by AndrMJ** [comment]
Dear @fabiovinci,

It seems as the problem also concerns code list of priority datasets:
Code list http://inspire.ec.europa.eu/metadata-codelist/PriorityDataset cannot be accessed. 

Best regards,
Andreas

**Comment by GDIAnja** [comment]
We have the same problem over here in Lower Saxony. Validation of metadata records is not possible any more.

You should consider correcting the ETF validator. With our tests, we do not want to find out whether the INSPIRE registry is running or other parts of the European infrastructure. We want to test our metadata. Therefore, it is necessary to make the necessary code lists for the tests available offline and deliver them with the ETF validator.

At the same time, there must be a functionality that allows the administrator of the ETF validator to find out with a click whether there have been changes in the relevant code lists in the meantime (for example once a month).

**Comment by fabiovinci** [comment]
Dear @AndrMJ,
thank you for reporting, the error is due to the temporary unavailability of the _.atom_ version of the codelists.
We are working on it.

Dear @GDIAnja,
Registry Resources are made available with each Validator release. For instructions on how to use them, please see the section "_Setting up a cache of INSPIRE Registry resources_", on the [Release page](https://github.com/INSPIRE-MIF/helpdesk-validator/releases).

To monitor changes in the registry, you can follow the [helpdesk-registry repository](https://github.com/INSPIRE-MIF/helpdesk-registry) and the related [releases](https://github.com/INSPIRE-MIF/helpdesk-registry/releases).

**Comment by juanluisrp** [comment]
> Dear @GDIAnja,
> Registry Resources are made available with each Validator release. For instructions on how to use them, please see the section "_Setting up a cache of INSPIRE Registry resources_", on the [Release page](https://github.com/INSPIRE-MIF/helpdesk-validator/releases).

@fabiovinci Actually these instructions are quite vague. How do I use them with the Docker image provided in the release to keep a cache? Do I need to copy them to a specific folder? Serve them using a web server? Are there specific instructions anywhere to use them?

**Comment by fabiovinci** [comment]
Dear all,

the Registry issue has been resolved, and the .atom format of the codelists is once again available.

I will close the issue, please reopen it if the error persists.

**Comment by antjacques** [comment]
Hello @fabiovinci 

Am I the only one still experiencing those issues with the validator? I tested several datasets that are supposed to be conform but I still got errors about codelist URLs:
![image](https://github.com/user-attachments/assets/8be28fa5-a46c-420e-bab8-05b10bd27133)

I can communicate the all report if needed.

Thanks

**Comment by fabiovinci** [comment]
Dear @antjacques,

the problem with the `.atom` format of the codelist has resurfaced.
We are working to solve it.

**Comment by fabiovinci** [comment]
Dear all,

we have verified that after applying the security patches and restarting the Registry server, the rules needed to download ATOM, CSV and ROR files were not applied.
The issue has been fixed and should not occur again.

**Comment by DanielMartinPerezdeLeon** [comment]
Dear @juanluisrp , 

Regarding the provision of further instructions on how to use the registry locally, please note that the purpose of these resources is vague on purpose, since we cannot know each user/entity approach on proxy configurations and policy.

The registry basically serves as an external server for the Validator to access its resources and validate the test against them. The idea is anyone can download the registry resources from the url provided earlier and serve it yourself, then you can set a local reverse-proxy to make all your network petitions made to the registry to point to the local ones you have served.

We are going to edit the last release's note to show a simple example on how to do this, since you are correct on pointing out it can be a bit too abstract.

Best regards,

**Comment by jenriquesoriano** [comment]
Dear @juanluisrp , 

we would like to inform that the [release notes](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2024.3) have been updated to include a simple use case for using the INSPIRE Registry resources locally. 
Please note that this use case is generic and may not fit the specific needs of an organization, but we hope it serves as an example to guide any organization interested in deploying the INSPIRE Registry resources.

Best regards

**Comment by juanluisrp** [comment]
Thank you for adding this @jenriquesoriano @DanielMartinPerezdeLeon.
