### ISSUE TITLE
Discovery service metadata validation failed for Coupled Resource element

### ISSUE THREAD

**Issue by grigoriouelena** [INSPIRE-MIF/helpdesk-validator#141]
I am testing a metadata file I have prepared for the national discovery service. I am using the staging instance (24 Oct.), since the validator is not working today.

The file I am testing is:
[discovery_md.zip](https://github.com/inspire-eu-validation/community/files/3766999/discovery_md.zip)

And the assertion that fails is:
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID33edffc1-797e-437b-bea7-b2ac186c4a72.html?lang=en#EID78b5b37f-3565-49df-999e-8ebdbf0318f2.

As I can see in my xml file, there is no operatesOn element.

**Comment by danielnavarrogeo** [comment]
Dear @grigoriouelena 

Your metadata does not have the _operatesOn_ element in the _SV_ServiceIdentification_ section.

You can see an example of its usage in:
 https://github.com/inspire-eu-validation/community/blob/a53e02e130625afe53e20157124fc5666a932273/examples/NetworkService_WMS_metadata_2.0_example#L299

Please, let us know if this solves your problem.

Regards

**Comment by grigoriouelena** [comment]
Dear Daniel,

Yes, my metadata doesn't have this element..
The problem is that even though the operatesOn element is not in my
metadata I get a failure saying that:
"The metadata record set has 1 record(s) with errors for this assertion.
XML document 'discovery_md.xml', record
'74074e3f-57f4-483e-ad8f-baa1eefd555b': The service metadata record has an
'operatesOn' property, but it does not have an xlink:href attribute."

Regards,

Elena

**Comment by danielnavarrogeo** [comment]
Dear Elena,

You are right. This element might not be provided but please take a look at this:

_The multiplicity of this element is zero or more with the following condition: "Mandatory if linkage to data sets on which the service operates are available"._

https://github.com/inspire-eu-validation/metadata/blob/2.0/sds/coupled-resource.md#notes

The test is going to be modified in order to allow not providing this element. I will let you know when it is ready in staging for testing.

Regads,

Daniel

**Comment by danielnavarrogeo** [comment]
Dear Elena,

The issue has been fixed. You can try in the staging instance.

Regards

**Comment by MarcoMinghini** [comment]
Dear @grigoriouelena,
according to the TG we have both that:
- the multiplicity of the Coupled Resource metadata element is 0..n
- the element is "mandatory if linkage to data sets on which the service operates are available".

In our opinion, this means in practice that the element is mandatory, since any INSPIRE service you may want to document refers to data set(s) which already exist (i.e. whose metadata is already available).

To keep this into account, the presence of the element might be made mandatory, or a manual check might be added if the element is not present.

The solution implemented is fine for the moment, but this should be further discussed with the sub-group.

**Comment by grigoriouelena** [comment]
Dear Marco, Daniel,

Of course the element should be provided, especially for the discovery service that is operating on data and services metadata. 

I was just checking the metadata file before I enter any coupled resources and I ran into a message that was not valid, in my opinion, so I thought I should report it.

I think that a manual check message is a good solution.

Thanks for the effort.

Regards,

Elena

**Comment by fabiovinci** [comment]
Dear all,

after reanalyzing the issue, it was verified that a manual check message should be added, as suggested by @grigoriouelena.

The related [ATS](https://github.com/inspire-eu-validation/metadata/blob/2.0/sds/coupled-resource.md) will be modified and the solution implemented in staging for testing.

**Comment by arantzaetxebarria** [comment]
Dear @fabiovinci, all

The solution has been implemented and it is in staging environment. Could you please verify? Thanks

Regards

**Comment by fabiovinci** [comment]
Dear @arantzaetxebarria,

I tested it and the fix implemented is fine.
