### ISSUE TITLE
Temporal reference system error - Dataset metadata CC2 test

### ISSUE THREAD

**Issue by grigoriouelena** [INSPIRE-MIF/helpdesk-validator#148]
I am checking dataset metadata compliance against conformance Class 2.
I have used the provided example to form my metadata according to MD TG 2.0.

Since yesterday (November 7th) I get the following 2 errors:
- md common req C.10: Responsible organisation: 
_System error in the Executable Test Suite. Please contact a system administrator. Error information:
[err:XPTY0004] Item expected, sequence found: (text {"info.egy@prv.ypeka.gr"},....
 (777/96)_
- md isdss 2.3: Temportal reference System
_The metadata record set has 1 record(s) with errors for this assertion.
XML document 'EF.EnvironmenntalMonitoringNetworks_WFD.xml', record '9483c21a-6673-4c84-9e4f-52b2d5361d31': The record must have an RS_Identifier element with non empty codeSpace element._

According to the MD TG 2.0, I think that there should not be a failure.

The staging instance is returning only the system error.

One of my metadata tested is: 
http://geoportal.ypen.gr/geonetwork/srv/api/records/9483c21a-6673-4c84-9e4f-52b2d5361d31/formatters/xml

The test reports are attached.
[CC2 - staging validator.zip](https://github.com/inspire-eu-validation/community/files/3823505/CC2.-.staging.validator.zip)
[CC2 - production validator.zip](https://github.com/inspire-eu-validation/community/files/3823544/CC2.-.production.validator.zip)

Thanks in advance.

Elena

**Comment by josemasensio** [comment]
Dear @grigoriouelena,

Thank you for your message. 
Concerning the md common req C.10 issue, the problem is that on your metadata there are two emails defined, when at the [ATS](https://github.com/inspire-eu-validation/metadata/blob/2.0/common/responsible-organisation.md) and the [TG](https://inspire.ec.europa.eu/sites/default/files/documents/metadata/inspire-tg-metadata-iso19139-2.0.1.pdf#page=37&zoom=100,0,581) only refers to one email.

On the other hand, the problem with the md isdss 2.3 is that in your ``gmd:MD_ReferenceSystem/gmd:referenceSystemIdentifier/gmd:RS_Identifier`` path, there is defined a ``gmd:code`` with a ``gmx:Anchor`` inside, when at corresponding [ATS](https://github.com/inspire-eu-validation/metadata/blob/2.0/isdss/temporal-rs.md) and at the [TG](https://inspire.ec.europa.eu/sites/default/files/documents/metadata/inspire-tg-metadata-iso19139-2.0.1.pdf#page=71&zoom=100,0,566) explains that the content of ``gmd:code`` must be a non-empty free text (``gco:CharacterString``).

If you have any other problems, please make us know.

Waiting for your feedback.
Best regards.

**Comment by grigoriouelena** [comment]
Dear @josemasensio ,

Thank you for your email.

As for the responsible party email address, I think that the standard - and the previous metadata editor if I recall correctly - allows multiple email addresses for every responsible party. If this is not the case anymore, I could change my metadata, but I think that the definition of more than one email addresses would be very useful.

As for the temporal reference system, I followed the example provided. The referenceSystemInfo element in my metadata is describing my crs and not the temporal system, since the dates I am using are referring to the gregorian calendar.

I attach two print screens I found from a presentation I had prepared for my data producers a few years ago, from the previous metadata editor. The email address field seems to give the user the option to add more than one email addresses.
![Inspire MD Editor-1](https://user-images.githubusercontent.com/55238073/68572354-dd5c9500-046d-11ea-9054-f0e57e952e4c.JPG)
![Inspire MD Editor-2](https://user-images.githubusercontent.com/55238073/68572367-e0f01c00-046d-11ea-9398-0d9ded91006d.JPG)

I have to note here that about a week ago my metadata passed all the CC2 tests.

I look forward for your feedback, since we are currently preparing our TG 2.0 metadata.

Best regards,
Elena

**Comment by fabiovin** [comment]
Dear @josemasensio,
regarding Req. C.10, it seems not so clear that "**only one**" e-mail address is required.
I think that if the ISO multiplicity of the element "`gmd:contactInfo/gmd:CI_Contact/gmd:address/gmd:CI_Address/gmd:electronicMailAddress`" is "_0..*_", INSPIRE should set it to "_1..*_" and not to "_1_".
This interpretation seems confirmed by the grigoriouelena's screenshots!

@grigoriouelena, the error related to the _md isdss 2.3_ was due to an error in the related ETS (already solved in the staging). 
It is a false error because it is raised even though the _Temporal reference systems_ element is not present in the metadata (as for the metadata tested by you). 

@josemasensio, in any case, the element `gmd:code`, that shall contain _Non-empty Free Text Elements_, can be encoded both with `gmx:Anchor `and `gco:CharacterString`.

Fabio

**Comment by fabiovin** [comment]
Dear @josemasensio,
we discussed further internally and we agreed to set the multiplicity of the "_gmd:contactInfo/gmd:CI_Contact/gmd:address/gmd:CI_Address/gmd:electronicMailAddress_" element to "**1..***".
Could you please update the relevant ETS accordingly?

Thank you,
Fabio

**Comment by josemasensio** [comment]
Dear @grigoriouelena,

We applied the ``gmd:contactInfo/gmd:CI_Contact/gmd:address/gmd:CI_Address/gmd:electronicMailAddress`` to be ``1..*``. 
You have the corresponding changes here: [#364](https://github.com/inspire-eu-validation/ets-repository/pull/364)

The changes are available on our [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). Please, could you try it and give us your feedback? We will appreciate it. Thank you.

Best regards.

**Comment by grigoriouelena** [comment]
Dear @josemasensio,

I tested it with the md file http://geoportal.ypen.gr/geonetwork/srv/api/records/3ab897a7-a831-439f-a239-324ee2e06b44/formatters/xml

The test report returned no error.
[Test run on 10_39 - 14.11.2019 with test suite Conformance Class 2_ INSPIRE data sets and data set series interoperability metadata.zip](https://github.com/inspire-eu-validation/community/files/3845346/Test.run.on.10_39.-.14.11.2019.with.test.suite.Conformance.Class.2_.INSPIRE.data.sets.and.data.set.series.interoperability.metadata.zip)

Best regards,
Elena
