### ISSUE TITLE
INSPIRE Validator: XML Schema Validation TG1.3 fails for apiso.xsd schema

### ISSUE THREAD

**Issue by JulianWill** [INSPIRE-MIF/helpdesk-validator#161]
Hello,

I'm currently trying to test metadata records with the schema:
xsi:schemaLocation="http://www.isotc211.org/2005/gmd http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd"

See file:
[metadata.zip](https://github.com/inspire-eu-validation/community/files/3873876/metadata.zip)

The test TG 1.3 "md -xml.a.1: Validate XML documents" fails with the error message "The file has Validation failed: -1:-1: Premature end of file. schema validation error(s)."

While the test TG 2.0 "md commen req C.1: XML Schema" passes.

The test was run using Firefox Quantum 60.8.0esr (64-Bit).
Test report:
[Test_report.zip](https://github.com/inspire-eu-validation/community/files/3873916/Test_report.zip)

I tested the XML schema of the file with Altova XMLSpy version 2009 sp1 and the schema was valid.

The issue has been raised earlier:
https://github.com/inspire-eu-validation/community/issues/87
It looks like the issue was temporary solved the 15th of October but also reported to be back problem  the 15th of November.

Could you please look into this? 

Thank you very much!

Best regards,
Julian Will

**Comment by josemasensio** [comment]
Dear @JulianWill,

Thank you for your message. We will investigate why the error occurs and communicate it to you as quickly as possible.

Best regards.

**Comment by josemasensio** [comment]
Dear @JulianWill,

The validator is not checking some XML schema definition. One of them was ``http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd``, the one that you got on your file. We will fix this and come back to you as soon as is available on [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). 

Best regards.

**Comment by josemasensio** [comment]
@JulianWill, the changes are already available on [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). 

Please, let us know if there is another problem.
Waiting for your feedback.

**Comment by JulianWill** [comment]
Thank you for the quick help. The file passes now the XML validation on the staging instance.

Do intergrate the fix in the production instance with the next planned update of the Geoportal in December?

**Comment by alitka** [comment]
I also tested, but I still get the error "Validation failed: -1: -1: Premature end of file."

- [ ] a description of the steps to reproduce your issue
1. go to http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp and select "Conformance class: INSPIRE Profile based on EN ISO 19115 and EN ISO 19119"
2. start the test and use an externale URL: 
- example 1: https://gdk.gdi-de.org/gdi-de/srv/ger/csw?REQUEST=GetRecordById&SERVICE=CSW&VERSION=2.0.2&Elementsetname=full&outputSchema=http://www.isotc211.org/2005/gmd&ID=ac9b2c35-3cc4-4c96-b3a9-bda24b7ab087 
- example 2: https://gdk.gdi-de.org/gdi-de/srv/ger/csw?REQUEST=GetRecordById&SERVICE=CSW&VERSION=2.0.2&Elementsetname=full&outputSchema=http://www.isotc211.org/2005/gmd&ID=82f97ad0-198b-477e-a440-82fa781624eb
3. the error message returned for the test "Schema validation > md-xml.a.1: validation XML documents" `XML document 'csw.xml', record '82f97ad0-198b-477e-a440-82fa781624eb': Validation failed: -1: -1: Premature end of file.`

- [ ] the browser and version used
`Firefox Browser 70.0.1 (64-Bit)`

- [ ] a screenshot illustrating the problem
![grafik](https://user-images.githubusercontent.com/29542183/69411087-8e83ea80-0d0c-11ea-9448-e317c223c178.png)

- [ ] the Test Report (ideally as an attachment to the issue)
- example 1: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID368009ec-93d8-483c-859f-0faa102646c9.html
- example 2: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDabc5e609-bfef-417d-a4d4-dbefeb387a3c.html

[testReports_examples.zip](https://github.com/inspire-eu-validation/community/files/3878670/testReports_examples.zip)

- [ ] the name of the Test that failed or better: change the Level of Detail
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID368009ec-93d8-483c-859f-0faa102646c9.html#EID545ad4c0-cdba-4b64-bcdd-b7a90c96f476

**Comment by JulianWill** [comment]
I can confirm the findings from Anja Litka. 
The test still returns an error if the metadata is retrieved from a CSW GetRecord request. 

Test results for the metadata record via file upload: XML schema is valid
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID1ea38ceb-c2bb-452f-bc72-809cb12599db.html#EID8df1f0eb-84d3-4190-91bb-b472909d10ee

Test results for the same metadata record via CSW GetRecord request: XML schema is invalid
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID47bac811-46b1-4cea-8468-0118ba801080.html#EIDc82231a7-e794-4485-974c-eeb5cf55e979

File used for the test:
[82f97ad0-198b-477e-a440-82fa781624eb.zip](https://github.com/inspire-eu-validation/community/files/3878794/82f97ad0-198b-477e-a440-82fa781624eb.zip)
CSW GetRecord request used for the test:
https://geoportal.bafg.de/soapServices/CSWStartup?request=GetRecordById&service=CSW&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=82f97ad0-198b-477e-a440-82fa781624eb
Test results:
[test_results.zip](https://github.com/inspire-eu-validation/community/files/3878807/test_results.zip)

Tests are run on the staging environment using Firefox Version 68.0.1esr.

According to Altova XML Spy the schema for the CSW GetRecord request is valid.

**Comment by josemasensio** [comment]
Dear @JulianWill, @alitka,

Thank you all for your feedback. We will check why the validator is raising this error and we will come back to you with the solution. 

Best regards.

**Comment by ghost** [comment]
I can confirm that validation of metadata records provided using GetRecordByID request as source delivered expected validation results on **15.10.2019**. Tests were done on staging instance. 

For more information see this comment https://github.com/inspire-eu-validation/community/issues/87#issuecomment-542099629.

**Comment by josemasensio** [comment]
Dear all, 

After some internal talk and some research, we updated the MD 1.3 test with the following:

As @danielnavarrogeo explained in #138, there were some updates on the validator. We modified the test to check if on the schemaLocation is defined http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd, and if it is, the schemaLocation is forced against schema https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/apiso-inspire/apiso-inspire.xsd.

@DeordD, thank you for your feedback. We are glad to hear that everything works as it should. 

@JulianWill, please, try to run the test now with the file. We will be interested to have your feedback.

@alitka, @JulianWill ([CSW GetRecord request](https://geoportal.bafg.de/soapServices/CSWStartup?request=GetRecordById&service=CSW&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=82f97ad0-198b-477e-a440-82fa781624eb)) , the problem here is that the validator checks if the first tag of the provided MD contains the schemaLocation attribute. On both of the MD that you provided to us, the first tag is `<csw:GetRecordByIdResponse>`.
We tried to remove it and the MD pass the first test.

In any case, the transition period from MD version 1.3 to version 2.0, will end in December. For this reason, support for MD TG 1.3 will finish during the incoming month.

We will be glad to have your feedback.
Best regards.

**Comment by JulianWill** [comment]
> 
> 
> I can confirm the findings from Anja Litka.
> The test still returns an error if the metadata is retrieved from a CSW GetRecord request.
> 
> Test results for the metadata record via file upload: XML schema is valid
> http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID1ea38ceb-c2bb-452f-bc72-809cb12599db.html#EID8df1f0eb-84d3-4190-91bb-b472909d10ee
> 
> Test results for the same metadata record via CSW GetRecord request: XML schema is invalid
> http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID47bac811-46b1-4cea-8468-0118ba801080.html#EIDc82231a7-e794-4485-974c-eeb5cf55e979
> 
> File used for the test:
> [82f97ad0-198b-477e-a440-82fa781624eb.zip](https://github.com/inspire-eu-validation/community/files/3878794/82f97ad0-198b-477e-a440-82fa781624eb.zip)
> CSW GetRecord request used for the test:
> https://geoportal.bafg.de/soapServices/CSWStartup?request=GetRecordById&service=CSW&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=82f97ad0-198b-477e-a440-82fa781624eb
> Test results:
> [test_results.zip](https://github.com/inspire-eu-validation/community/files/3878807/test_results.zip)
> 
> Tests are run on the staging environment using Firefox Version 68.0.1esr.
> 
> According to Altova XML Spy the schema for the CSW GetRecord request is valid.

**Comment by alitka** [comment]
Too be clear: if you use the "Conformance class: INSPIRE Profile based on EN ISO 19115 and EN ISO 19119" with an external URL, which include a GetRecords-request, the issue is still there, right? 

I did a test (https://gdk.gdi-de.org/gdi-de/srv/ger/csw?REQUEST=GetRecordById&SERVICE=CSW&VERSION=2.0.2&Elementsetname=full&outputSchema=http://www.isotc211.org/2005/gmd&ID=0da92c24-f4b4-4c96-b3a9-bda24b7ab087) and the error message is still the same: `Validation failed: -1: -1: Premature end of file.`
- http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDd0ee3947-4873-43a8-9df4-52020b6aa329.html

But another point was mentioned by Jose in his mail, that "the transition period from MD version 1.3 to version 2.0, will end in December [and the] support for MD TG 1.3 will finish during the incoming month." How is this possible, that all "TG 1.3 metadata records" are conform for the monitoring 2019, but in January 2020 not anymore?

**Comment by JulianWill** [comment]
The issue is still there for testfiles insert with an external URL which include a GetRecords-request.

The test "Conformance class: INSPIRE Profile based on EN ISO 19115 and EN ISO 19119" still returns  an error on the XML schema validation.

Test 
https://geoportal.bafg.de/soapServices/CSWStartup?request=GetRecordById&service=CSW&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=82f97ad0-198b-477e-a440-82fa781624eb

Test result:
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDed32a4e6-776e-4496-b025-5e16d4705541.html#EIDde58df7c-3c7b-4f1c-a42d-950509548bc2
[Test_result.zip](https://github.com/inspire-eu-validation/community/files/3885160/Test_result.zip)

If I validate the URL using Altova XML Spy (2009 sp 1) the XML is valid:
![grafik](https://user-images.githubusercontent.com/7677820/69518645-61c41300-0f58-11ea-88dd-e1f5d29644e7.png)


@DeordD: 
Have you checked again if the XML validation is still valid using testfiles insert with an external URL which include a GetRecords-request. Can you post the testresults? The test you have done the 15.10.19 where all done using the "file upload" option, right?

**Comment by ghost** [comment]
Hi @JulianWill,

1. `Have you checked again if the XML validation is still valid using testfiles insert with an external URL which include a GetRecords-request. `
On 15.10.2019 I checked both options (XML-Upload and GetRecordByID-URL). Both tests were OK. 
Sadly, I have just documented the results for XML-Upload.  But, here ist ETS that was deployed on staging instance:
[ets-md-xml-bsxets.zip](https://github.com/inspire-eu-validation/community/files/3885244/ets-md-xml-bsxets.zip)
--->On 22.11.2019 i didn't perform any tests on staging instance!

2. `Can you post the testresults? `
No, I didn't save them. 

3. `The test you have done the 15.10.19 where all done using the "file upload" option, right?`
No, I checked both options XML-Upload and GetRecordByID-URL.

**Comment by MarcoMinghini** [comment]
Dear @alitka,

> But another point was mentioned by Jose in his mail, that "the transition period from MD version 1.3 to version 2.0, will end in December [and the] support for MD TG 1.3 will finish during the incoming month." How is this possible, that all "TG 1.3 metadata records" are conform for the monitoring 2019, but in January 2020 not anymore?

As mentioned in the INSPIRE TG v.2.0 for metadata, a period of 3 years (from 19 December 2016 to 19 December 2019) has been left to Member States to perform a smooth transition between MD v.1.3 to 2.0. After this period, Member States should only provide metadata according to TG v.2.0, and as a consequence the support for fixing errros in the tests for MD TG v.1.3 will be concluded.

Questions on how the metadata according to TG v.1.3 will be considered for the calculation of the indicators will need to be discussed in the sub-group on 2018.1.

**Comment by josemasensio** [comment]
Dear all,

@alitka:

> Too be clear: if you use the "Conformance class: INSPIRE Profile based on EN ISO 19115 and EN ISO 19119" with an external URL, which includes a GetRecords-request, the issue is still there, right?

Yes, if the metadata first element is a GetRecord request the validation fails. It does not make any difference if the file is from an external URL or from an upload. 

> How is this possible, that all "TG 1.3 metadata records" are conform for the monitoring 2019, but in January 2020 not anymore?

Version 2.0 of the MD TG were published in Dec 2016, with a 3-year implementation deadline to enable a smooth transition.

@JulianWill;

As you mentioned above, the validator should accept the GetRecord-redirection, so we will update the test to allow this. 
And please, if the issue is solved don't close it. We will mark as solved and leave it open.

Thank you all and best regards.

**Comment by alitka** [comment]
Running in an error message again, if I upload a xml-file:

`The dataset has 1 file(s) with errors for this assertion.
XML document 'nw_dataset_xml_iso19139.xml': The file has Validation failed: 1:528: cvc-elt.1.a: Cannot find the declaration of element 'gmd:MD_Metadata'. schema validation error(s).`

The error message appears, because the declaration for the gmd-namespace under the xsi:schemaLocation is "http://schemas.opengis.net/iso/19139/20060504/gmd http://schemas.opengis.net/iso/19139/20060504/gmd/gmd.xsd", but the test only checks one of the following URLs:
-	http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd
-	http://www.isotc211.org/2005/gmd/gmd.xsd
-	http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd

 Is it possible, to add this "additional xsd-location" to the test "md-xml.a.1"?

**Comment by danielnavarrogeo** [comment]
Dear @alitka 

A fix for this issue has been developed and you can test it in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could please check it and provide us feedback whether the issue has been solved?

Regards

**Comment by alitka** [comment]
Dear @danielnavarrogeo
I have tested with a xml-file, a direct URL to the metadata record and via CSW GetRecord request
again and everything is working properly.

Nevertheless, I'm a bit suprised, because you said, that after 19 December 2019
> the support for fixing errros in the tests for MD TG v.1.3 will be concluded.

Thanks & regards.

**Comment by danielnavarrogeo** [comment]
Dear @alitka 

Thank you for testing the implemented solution.

Regarding the support to MD TG v.1.3, it is indeed concluded already. This issue has been considered since it was opened before the support ended.

Regards

**Comment by ghost** [comment]
Dear @danielnavarrogeo ,

thanks a lot for fixing this problem. 

I have just compared [XML Validation for TG version 2.0 - md common req C1: XML Schema](https://github.com/inspire-eu-validation/ets-repository/blob/a1f49c931d440109b190241e35372450929f5c34/metadata/2.0/common/ets-md-common-bsxets.xml#L68) and [standalone XML Validation for Basic Tests - Conformance Class 'XML encoding of ISO 19115/19119 metadata'](https://github.com/inspire-eu-validation/ets-repository/blob/a1f49c931d440109b190241e35372450929f5c34/metadata/1.3/xml/ets-md-xml-bsxets.xml#L93) and it seems that two XQuery expressions are not exactly the same. 

Should this be the case? 
Should we expect identical error message after validation of one metadata record with [following schemas](https://github.com/inspire-eu-validation/community/issues/161#issuecomment-559718140) against these two TestCases?

Kind regards,
