### ISSUE TITLE
Textual: replace 'View Service WCS Core' by 'Download Service WCS Core'

### ISSUE THREAD

**Issue by thijsbrentjens** [INSPIRE-MIF/helpdesk-validator#165]
Just a minor textual enhancement: the validator lists a WCS validator:

Conformance Class 'Download Service WCS Core'

But after opening more details of this validator, the conformance class is named:

Source: Conformance Class 'View Service WCS Core'

For a next update/release, please correct the name in the Conformance Class to 'Download Service WCS Core'

**Comment by josemasensio** [comment]
Dear @thijsbrentjens,

Thank you for your feedback. We will update this typo error.

Best regard.

**Comment by josemasensio** [comment]
Dear @thijsbrentjens,

The error has been fixed. We will appreciate if you could provide us with your feedback.

Thank you in advance and best regards.

**Comment by MarcoMinghini** [comment]
Dear @thijsbrentjens,
we will keep the issue open, but just change the label to reflect what is the status of the solution (and in particular to know that it is now included in the staging instance and has to be accepted by the community; check also the project board [here](https://github.com/inspire-eu-validation/community/projects/1)).
We would appreciate your formal confirmation that the problem is now solved in the staging instance, so that we can mark the issue as 'solved'.
Thank you.

**Comment by thijsbrentjens** [comment]
Sorry for closing too quickly :). The typo is fixed in the staging environment.
