### ISSUE TITLE
OperatesOn URL validation

### ISSUE THREAD

**Issue by kkoistinen** [INSPIRE-MIF/helpdesk-validator#172]
Hi,

We are validating service metadata https://www.paikkatietohakemisto.fi/geonetwork/srv/api/records/a22ec97f-d418-4957-9b9d-e8b4d2ec3eac/formatters/xml which contains multiple OperatesOn elements. Some of the OperatesOn URLs return HTTP 301 response (redirection) instead of HTTP 200. 

ETF validator throws an error on URLs which return 301:

XML document 'csw.xml', record 'a22ec97f-d418-4957-9b9d-e8b4d2ec3eac': The metadata record has a linkage property, but it references a resource at 'http://www.paikkatietohakemisto.fi/geonetwork/srv/en/csw?service=CSW&request=GetRecordById&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=36a49889-7853-42f2-81f8-be665713f2bb' that cannot be accessed. The HTTP status code when requesting the resource is: '301'. A status code of '200' is expected.

Is it really wrong to have references on URLs that return HTTP 301 or is it a bug in ETF validator?

Best regards,
Kai Koistinen
National Land Survey of Finland

**Comment by danielnavarrogeo** [comment]
Dear @kkoistinen,

The http url that you have provided is automatically redirected to a https one.

The validator is not able to handle this redirection. This is currently a limitation of the validator.

You could solve this by changing the urls affected from http to https.

Regards

**Comment by josemasensio** [comment]
Dear @kkoistinen,
Thank you for your message. Please, could you provide us with the Conformance Class that you have tested? 
Best regards.

**Comment by kkoistinen** [comment]
@josemasensio 

Conformance class in this case is "INSPIRE Profile based on EN ISO 19115 and EN ISO 19119"

**Comment by josemasensio** [comment]
Dear @kkoistinen,

Please, can you attach the test result URL to check what is raising the error?

Thank you.

**Comment by kkoistinen** [comment]
https://beta.paikkatietoalusta.fi/validointipalvelu/v2/TestRuns/EID7cbdcfa8-743f-4617-9888-a69a38b5f48a.html

**Comment by josemasensio** [comment]
Dear @kkoistinen,

Is your validator pointing to the `master` branch? If it is, please, update the branch to `v1.0.8` or `staging`. The new release is not already on the `master` so this is not up to date. The problems with the redirections were solved on the release mentioned above, on the issue #150  and are available on our [reference validator](http://inspire.ec.europa.eu/validator/) or on our [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp).

Otherwise, we will appreciate it if you can add your validator to the list created on issue #162.

In any case, the transition period from MD version 1.3 to version 2.0, will end on the 19 of December. For this reason, support for MD TG 1.3 will finish during the incoming days.

Best regards.
