### ISSUE TITLE
Not sure whether I'm in error or the validator is

### ISSUE THREAD

**Issue by PeterParslow** [INSPIRE-MIF/helpdesk-validator#180]
Hi,
I've just run the validator on a UK based Discovery Service - not the current national one!

https://ckan.publishing.service.gov.uk/csw?request=GetCapabilities&service=CSW&version=2.0.2

I get a rather fundamental error, that seems to imply it can't find the INSPIRE Extended Capabilities at all. 
set-extended-capabilities-scenario => "Premature end of file."

I can see a couple of things wrong in 'my' Extended Capabilities (URL pointing to local host, haven't set the start & end dates) - but I don't think they should result in a total failure, so perhaps there's something I haven't noticed.

Full results: http://inspire.ec.europa.eu/validator/v2/TestRuns/EID62c26213-fb61-4961-83a8-9d36cee3f06b.html

**Comment by danielnavarrogeo** [comment]
Dear @PeterParslow 
We are analyzing this issue. We will keep you posted.
Regards

**Comment by danielnavarrogeo** [comment]
Dear @PeterParslow 

We have been testing your service. It seems there is some problems related with the gzip compression of the capabilities document.

If you request the capabilities in Chrome an error is shown and the xml is not printed well.
![imagen](https://user-images.githubusercontent.com/45062523/70786159-45afd680-1d8c-11ea-8cae-c9d3699fb047.png)

The log of the ETF shows the following message:
![imagen](https://user-images.githubusercontent.com/45062523/70786473-0635ba00-1d8d-11ea-9837-8cd0d48ea136.png)

We have published your same metadata internally, test it in ETF and there is no problem. So the issue seems to be related with the configuration of the service.

Regards

**Comment by PeterParslow** [comment]
This is odd. It works in Firefox; your Chrome screen shot starts as simply Chrome's habit of stripping out the XML tags - but then you get the ERR_HTTP2_PROTOCOL_ERROR. I tried with Internet Explorer, and get INET_E_DATA_NOT_AVAILABLE, without any data shown.

It's a pity the web's not consistent :)

How would I even tell if the server is trying to compress it. I wouldn't expect gzip; I guess it's possible that if you are using HTTP headers to request a compressed stream, then the server might be doing that. I don't have any client side tools to try that out.

I can also GetRecords from it, chaining to a GeoNetwork instance.

Not sure where to go with this.

**Comment by danielnavarrogeo** [comment]
Dear @PeterParslow 

You may want to ask to the community related with the software you are using to provide the service.

We do not know what is the problem. But it does not seem to be an issue with the INSPIRE validator since we deploy statically your same capabilities document and found no problems.

Regards

**Comment by PeterParslow** [comment]
I should have updated this: I raised it with the organisation that provides the service, and they're looking into it.

**Comment by danielnavarrogeo** [comment]
Thank you @PeterParslow, I will then close this issue.

Please do not hesitate to open a new issue here if you find one.

Regards
