### ISSUE TITLE
TG version 2: gmd:MD_ScopeDescription "Service"

### ISSUE THREAD

**Issue by laers** [INSPIRE-MIF/helpdesk-validator#189]
The example on page 69 in Technical Guidelines for the implementation of INSPIRE dataset and service metadata based on ISO/TS 19139:2007 Version 2.0.1 provides this example

`<gmd:levelDescription> `
`<gmd:MD_ScopeDescription> `
`<gmd:other> `
`<gco:CharacterString>Service</gco:CharacterString> `
`</gmd:other> `
`</gmd:MD_ScopeDescription> `
`</gmd:levelDescription>`

ETF Validator rejects this and gives this output: The term "service" in the language of the metadata must be in lower case.

**Comment by danielnavarrogeo** [comment]
Dear @laers 

Thank you for opening this issue. We are going to fix it and we will come back to you afterwards.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @laers 

This issue is related with [96](https://github.com/inspire-eu-validation/community/issues/96). The issue has been fixed and the requirements 3.1 and 3.8 behaves now as follows:

requirement 3.1:
* Check that /gmd:MD_Metadata/gmd:hierarchyLevel/gmd:MD_ScopeCode@codeListValue is "service".
* Check that /gmd:MD_Metadata/gmd:hierarchyLevelName/gco:CharacterString is a non-empty free text.

requirement 3.8:
* Check that /gmd:MD_Metadata/ gmd:dataQualityInfo[1]/gmd:DQ_DataQuality/gmd:scope/gmd:DQ_Scope/gmd:level/gmd:MD_ScopeCode@codeListValue is "service".
* Check that /gmd:MD_Metadata/ gmd:dataQualityInfo[1]/gmd:DQ_DataQuality/gmd:scope/gmd:DQ_Scope/gmd:levelDescription/gmd:MD_ScopeDescription/gmd:other is a non-empty free text.

Therefore, the lower case check of /gmd:MD_Metadata/gmd:hierarchyLevelName/gco:CharacterString in requirement 3.1 and /gmd:MD_Metadata/ gmd:dataQualityInfo[1]/gmd:DQ_DataQuality/gmd:scope/gmd:DQ_Scope/gmd:levelDescription/gmd:MD_ScopeDescription/gmd:other in requirement 3.8 has been removed.

While it checks exactly the term "service" (in lower case) for the elements /gmd:MD_Metadata/gmd:hierarchyLevel/gmd:MD_ScopeCode@codeListValue and /gmd:MD_Metadata/ gmd:dataQualityInfo[1]/gmd:DQ_DataQuality/gmd:scope/gmd:DQ_Scope/gmd:level/gmd:MD_ScopeCode@codeListValue.

Could you please check it in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) environment and provide us feedback?

Regards

**Comment by danielnavarrogeo** [comment]
Dear @laers 

Could you please check the implemented solution in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) environment and provide us feedback?

Regards

**Comment by alitka** [comment]
Dear @danielnavarrogeo
I have tested with a xml-file, containing the term "service" in the language of the metadata (german = Dienst) and everything is working properly.

entry for TG Requirement 3.1: metadata/2.0/req/sds/resource-type
`<gmd:hierarchyLevel>`
`<gmd:MD_ScopeCode
codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ScopeCode"
codeListValue="service" />`
`</gmd:hierarchyLevel>`
`<gmd:hierarchyLevelName>`
**`<gco:CharacterString>Dienst</gco:CharacterString>`**
`</gmd:hierarchyLevelName>`

entry for TG Requirement 3.8: metadata/2.0/req/sds/only-one-dq-element
`<gmd:DQ_Scope>`
`<gmd:level>`
`<gmd:MD_ScopeCode codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ScopeCode"	codeListValue="service" />`
`</gmd:level>`
`<gmd:levelDescription>`
`<gmd:MD_ScopeDescription>`
`<gmd:other>`
**`<gco:CharacterString>Dienst</gco:CharacterString>`**
`</gmd:other>`
`</gmd:MD_ScopeDescription>`
`</gmd:levelDescription>`
`</gmd:DQ_Scope>`

Thanks & regards.

**Comment by danielnavarrogeo** [comment]
Thank you @alitka for testing the solution. Then we will consider this issue as 'solved'.

Regards
