### ISSUE TITLE
INSPIRE Validator cannot be reached

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#196]
When trying to access the INSPIRE Validator at http://inspire.ec.europa.eu/validator/, I get this error:
504 Gateway Time-out
nginx/1.14.1

The staging instance at http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/ still works.

**Comment by danielnavarrogeo** [comment]
Dear @JohannaOtt 

Thank you for the comment. 

We are currently performing [maintenance works](https://github.com/inspire-eu-validation/community/issues/195). You can still use the staging instance.

Sorry for the inconvenience.

Regards.

**Comment by danielnavarrogeo** [comment]
Dear @JohannaOtt 

The INSPIRE Reference Validator at http://inspire.ec.europa.eu/validator/ is up and running again.

Sorry for the inconvenience.

Regards.

**Comment by JohannaOtt** [comment]
Dear @danielnavarrogeo 
Thank you for the notification. Unfortunately, the first test I started (GML, only 4 GML basic conformance classes) does not continue for 15 minutes: 
![grafik](https://user-images.githubusercontent.com/34163838/72794314-18ccca00-3c3c-11ea-96e2-902a41eccd20.png)
I tried the same test and uploading a zipped version of the file but that got canceled: 
![grafik](https://user-images.githubusercontent.com/34163838/72794392-3863f280-3c3c-11ea-87ed-63499106318c.png)

**Comment by danielnavarrogeo** [comment]
Now it works again. You can use: http://inspire.ec.europa.eu/validator/

Regards.

**Comment by JohannaOtt** [comment]
@danielnavarrogeo I am sorry, but the validator still gets stuck for me at the exact same test 
![grafik](https://user-images.githubusercontent.com/34163838/72817483-2436ea00-3c6a-11ea-8bc4-be39532df2fc.png) or has there been something added to it so that it is expected that it takes more than 25 minutes?

**Comment by danielnavarrogeo** [comment]
Dear @JohannaOtt 

We are studying what is causing the error in the validator. It seems to be related with a gml file named 'US_govser_testDataINSPIREvalidator.gml.zip'.

We are reproducing the error in a local instance.

Regards

**Comment by JohannaOtt** [comment]
Dear @danielnavarrogeo Thanks for investigating. This is the file I uploaded (tried as zip and as gml - got stuck at the same test). I was able to test the same file (only with a different name) successfully last week in case that helps.

**Comment by danielnavarrogeo** [comment]
Thank you @JohannaOtt for the information.

We will keep you updated.

**Comment by carlospzurita** [comment]
Dear @JohannaOtt 
We have been investigating the problems with your file, and we found a series of errors that were thrown on the validator on the geometry validation.

`ERROR d.i.e.b.SecondaryGeometryElementValidationHandler - Error in XML document (line: 15, column: 559, character offset: 2107): Cannot parse 'gml:posList': contains 39 values, but coordinate dimension is 2. This does not match.`

These appeared along all the GML in the validation, and was causing an uncontrolled exception in the validator. We made a quick test loading the WFS collection in QGIS and saving it again as a GML, and the geometries were validated. Of course this is not a valid test result because the GML was not saved using the INSPIRE schema, but at least we know that the geometries are well formed to be loaded.

We need to delve deeper on the issue on why this is crashing the validator instead of just throwing an error on the Test Report.

**Comment by JohannaOtt** [comment]
Dear @carlospzurita 
Thank you for the update. I just wanted to test with a different dataset that does not have geometry issues, but now, I am again running into
504 Gateway Time-out
nginx/1.14.1
when trying to access http://inspire.ec.europa.eu/validator/

**Comment by carlospzurita** [comment]
Dear @JohannaOtt 
Did you also tried to test the dataset with no geometry issues before this? I saw the same errors happenning on the production instance, and it can be the cause you are seeing the time out.

For now, we would like to ask you to don't submit this test runs, at least until we have found a way to fix the problem.

Also, can you give us permission to share the dataset causing the crash (or a simplified/anonymised version of it) with the colleagues from the Techincal Commitee for the [ETF validator software](https://github.com/etf-validator/etf-webapp) in order to help find a solution?

**Comment by JohannaOtt** [comment]
Dear @carlospzurita I did not do any testing today as I was not able to reach the validator.
I have to clarify with my customer whether the dataset can be shared further. I will get back to you on that.

**Comment by JohannaOtt** [comment]
@carlospzurita I got feedback from the data owner that the dataset can be shared for testing/fixing purposes.

**Comment by carlospzurita** [comment]
@JohannaOtt thank you very much, we will come back to you with the results of our testing.

**Comment by carlospzurita** [comment]
Dear @JohannaOtt 

We have been testing with your dataset and we found the source of the error. The validator relies on the library deegree to parse GML geometries and validate them. There is an error in the srsName and srsDimension attributes detection, causing the <gml:posList> interpreted as 2 dimension. This is an issue that you have encountered in the past (see https://github.com/inspire-eu-validation/ets-repository/issues/161) and still persist. 

Adding those attributes to the <gml:posList> on the GML file lets the validator process the geometry. This is of course a temporary solution, as these attributes are not required by the GML schema. However, until we deploy a hotfix for this issue, is a quick workaround for the validation of your datasets.

**Comment by JohannaOtt** [comment]
Dear @carlospzurita 
Thank you for the feedback and the temporary workaround. Due to a misunderstanding with the customer who is the owner of the dataset, we did try to validate agains yesterday - I am sorry if that caused any inconveniences.

**Comment by carlospzurita** [comment]
Dear @JohannaOtt 

We added a workaround for this issue. Please check it out on https://github.com/inspire-eu-validation/community/issues/203#issuecomment-584600627

**Comment by JohannaOtt** [comment]
Dear @carlospzurita I just uploaded the file to the staging instance and the validator did run without crashing. Thank you for the quick fix.
