### ISSUE TITLE
Cache schemas to reduce validation time

### ISSUE THREAD

**Issue by MarcoMinghini** [INSPIRE-MIF/helpdesk-validator#205]
In any validation performed in the INSPIRE Validator, most of the time is taken to access online resources (schemas, including imported schemas). 

A solution which is currently under development caches the schemas locally, so that the validation is much faster. This improvement will be soon available in the staging instance for testing.

**Comment by carlospzurita** [comment]
The solution for caching external schemas locally is deployed on the staging envorinment. You can test your metadata records there and provide useful insight for us in order to apply this to he production instance.

**Comment by ghost** [comment]
Hi @MarcoMinghini ,

thanks a lot for the information given. Really good news!

Is it planned to integrate this functionality in the [following version - 2.1.0](https://github.com/etf-validator/governance/issues/85) of ETF-Validator or some minor release is planned? 

Is it planned to commit newest changes in the [next branch](https://github.com/etf-validator/etf-webapp/commits/next)?
 
Thanks a lot in advance.

Kind regards

**Comment by carlospzurita** [comment]
Dear @DeordD 

> Is it planned to commit newest changes in the next branch?

This solution was implemented at server level, and it doesn't have any effect on the validator code. The **next** branch will remain the same for this.

 We will discuss if it is interesting to include this in the released Docker image.

**Comment by ghost** [comment]
Dear @carlospzurita ,

i just saw that [pre-release](https://github.com/inspire-eu-validation/community/releases/tag/v2020.1) was released today. Thanks a lot for providing this version to the community!

Can we also expect some pre-release including local schema-caches implementation as docker image like stated in https://github.com/inspire-eu-validation/community/issues/205#issuecomment-581275615? 

Thanks in advance.

**Comment by carlospzurita** [comment]
Dear @DeordD 

Please take into account that this pre-release is a work in progress. We will be updating everything until the release day, so for now, you should not use the information there as a reference. We are still discussing the matter on including the schema cache as part of the official release.

Thank you very much.

**Comment by MarcoMinghini** [comment]
Dear @DeordD, all,
did you have a chance to test this improvement on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp) and confirm that validation is overall faster?

We would like to include this improvement in the next release of the INSPIRE Reference Validator (scheduled on 15/03/2020) but we would like to get some feedback from the community before marking the issue as _solved_.

**Comment by ghost** [comment]
Dear @MarcoMinghini,
I will perform some tests for metadata records. 

I will publish the results here until the end of the week. 

Kind regards.

**Comment by ghost** [comment]
Dear @MarcoMinghini, 

here are the test results. 

**Test results**

_TG 2.0:_

| # | Instance | hierarchyLevel | Run | Validation time | Validation report |
| ------ | ------ | ------ |  ------ | ------ | ------ |
| 1 | staging | dataset | 1st | 1.793 s | http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDbf653942-3bc0-4cb8-92f3-463880b82e6e.html | 
| 2 | staging | dataset | 2nd | 0.528 s | http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDd8327bf3-7001-4f68-acee-405a0f44f1e7.html | 
| 3 | staging | dataset | 3rd | 0.621 s | http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID08613eae-14ef-453f-8326-d426e62b5087.html | 
| 4 | production | dataset | 1st | WAITING | # 205 - TG 2.0 (dataset) 1st run | 
| 5 | production | dataset | 2nd | WAITING | # 205 - TG 2.0 (dataset) 2nd run | 
| 6 | production | dataset | 3rd | 28 s | http://inspire.ec.europa.eu/validator/v2/TestRuns/EID2cc0ea9b-349f-4fd6-a739-eb451f461f57.html |
| 7 | production | dataset | 4th | 27 s | http://inspire.ec.europa.eu/validator/v2/TestRuns/EID279698f4-d18d-4e90-b415-c47405491750.html |
| 8 | production | dataset | 5th | 27 s | http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDb986c316-f070-4ac4-97c8-30c533590abe.html |

_TG 1.3:_

| # | Instance | hierarchyLevel | Run | Validation time | Validation report |
| ------ | ------ | ------ |  ------ | ------ | ------ |
| 1 | staging | service | 1st | 47 s | http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID6e8e34b8-46b0-48c1-a657-35180f2d62d5.html | 
| 2 | staging | service | 2nd | 2 min 34 s | http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDe45a3ac2-b092-4414-85a4-57ecb9ed54bf.html | 
| 3 | staging | service | 3rd | 1.255 s | http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID72c33089-6f6c-4e85-89d2-43e72007679c.html | 
| 4 | staging | service | 3rd | 1.795 s | http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID0437e38b-cf5f-43dc-87d9-21d53638fed2.html  |
| 5 | production | service | 1st | 1.440 s (actual time ~ 15 s) | http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDf42295a5-322f-40ae-845c-d9bbb0c7fbff.html | 
| 6 | production | service | 2nd | 1.381 s (actual time ~ 15 s) | http://inspire.ec.europa.eu/validator/v2/TestRuns/EID0494773f-c166-49b9-99ec-0f6c074b880a.html | 
| 7 | production | service | 3rd | 1.457 s (actual time ~ 15 s) | http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDbd042a56-7a23-48d5-92f5-cd2e9d655d5a.html |

**Test reports**
Validation reports:
[validation reports.zip](https://github.com/inspire-eu-validation/community/files/4302239/validation.reports.zip)

Validation reports can't be opened in web browsers - they are not well formed.

**Test metadata**
Test metadata records:
[service-metadata.zip](https://github.com/inspire-eu-validation/community/files/4302227/service-metadata.zip)
[dataset-metadata.zip](https://github.com/inspire-eu-validation/community/files/4302228/dataset-metadata.zip)

**Notes**
Following aspects could have significant impact on validation times:   
1. ETF-validator environments on production and staging instance aren't exactly the same.
2. ETS for TG 1.3 and 2.0 are different on production and staging instance.
3. XQuery scripts for XML-Validation (see [note](https://github.com/inspire-eu-validation/community/issues/161#issuecomment-586143486)) for TG 1.3 and TG 2.0 are different on staging/production instance.
4. Overall validation time in the reports doesn't match the actual validation time. Large differences occurred for TG 1.3 on production instance. This could be related to [issue # 246](https://github.com/inspire-eu-validation/community/issues/246). 
XML-Schema validation on production instance (TG 1.3 and TG 2.0) takes around 35 s when metadata record can be fully validated. Validation takes less time if following message occurs in the report: `The dataset has 1 file(s) with errors for this assertion. XML document 'service-metadata.xml': The file has Validation failed: -1:-1: Premature end of file. schema validation error(s).`  
5. It is not known which effect [issue # 246](https://github.com/inspire-eu-validation/community/issues/246) has on the validation time for metadata which have apiso.xsd in the XML-header.
6. Validation results aren't compared in order to check if the solution with cache schema and remote schema deliver the same error messages. 

**Conclusion**

In my opinion validation on staging instance with cached schema is overall and significantly faster under assumption that aspects in Notes don't have significant impact on validation process and results. 

Kind regards.

**Comment by carlospzurita** [comment]
Dear @DeordD 

Thank you for the analysis of results. As you said, production and staging are a little bit different, but we also have deployed a replica of the production instance for metadata validation in the INSPIRE Geoportal and the results are similar. 

As far as we know, there should not be any influence from the issues you commented, given that this is just a cache. It is only acting as an intermediary to external resources, wether this are reachable and processed correctly or not. So in any case, this are independent issues.

For all of this, we are going to mark this issue as solved and include it in the next release. Thanks again for your feedback.

Best regards.
