### ISSUE TITLE
Move of ISO resources to HTTPs

### ISSUE THREAD

**Issue by jmrubio82** [INSPIRE-MIF/helpdesk-validator#21]
Hi,
It looks like ISO website moved all resources to HTTPs - and as the validator has not implemented any redirection, it returns "301 Moved permanently", throwing a few schema validator errors. 
![image](https://user-images.githubusercontent.com/46571286/51022759-66244f00-1585-11e9-9beb-262fb03e716a.png)
I am not sure if this is something that you are considering to implement or it will be left to be fixed on the catalogues side. 
Thank you!

**Comment by MarcoMinghini** [comment]
As a temporary solution, a modified version of the INSPIRE schemas was created: https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/

Instead of importing the ISO schemas (now moved to https and causing redirection problems), these schemas import the corresponding OGC schemas.

This change is already deployed and can be tested in the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).
