### ISSUE TITLE
Pre-defined WFS - check on optional element wfs:boundedBy

### ISSUE THREAD

**Issue by danieluct** [INSPIRE-MIF/helpdesk-validator#214]
When testing pre-defined WFS,  a check is made against the bounding box of the returned feature collection (/wfs:FeatureCollection/wfs:boundedBy/gml:Envelope/@srsName) : https://github.com/inspire-eu-validation/ets-repository/blob/cf007c52279f874324e9e554ab19b19651cd8112/service/ds-wfs-pre-defined-soapui-project.xml#L5266

The wfs:boundedBy element is however optional according to the WFS 2.0 standard and I am not aware of any requirement to provide it in INSPIRE technical documents

**Comment by danielnavarrogeo** [comment]
Dear @danieluct 

Could you provide us the url of the service that you are validating in order to analyze the issue?

Regards

**Comment by danieluct** [comment]
Hi @danielnavarrogeo,
The service I have tested is https://inspire.meteoromania.ro/WIGOS/WFS?request=GetCapabilities&service=WFS&version=2.0.0

**Comment by iuriemaxim** [comment]
@carlospzurita Please remove the test of the bounding box for Predefined WFS as the wfs:boundedBy element is optional according to the WFS 2.0 standard and there are any requirement to provide it in INSPIRE technical documents.

This is not possible to be delivered in Geoserver, and in case that we will write code to deliver the bounding box, it takes a huge time to be computed depending on the WFS elements that are requested (filtered).

I assume that is easy to remove a test in the validator and this issue is pending from to much time, so it could be done for this release in June, not to wait until December again.

We are waiting for two issues to be solved in order to have a reference implementation that would pass all the tests. This is one of it and another one is related to a CITE test (spatial Join issue)

Iurie

**Comment by carlospzurita** [comment]
Dears @iuriemaxim @danieluct 

We have been discussing the approach and we decided that indeed the `boundedBy` element is optional for the responses of the storedQuery. What we are going to implement a is an optional check for the CRS in case of the existence of the element `boundedBy`, but else it will pass directly.

**Comment by iuriemaxim** [comment]
@carlospzurita Thank you for the good news!

**Comment by iuriemaxim** [comment]
@carlospzurita There are any new information regarding this issue? Most probably the fix should not be so difficult.

**Comment by carlospzurita** [comment]
A fix for this issue has been published on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). Please let us know if everything is in order.

**Comment by iuriemaxim** [comment]
@carlospzurita Thank you for the fix.

The following service was tested and no errors were trigerred anymore:
https://inspire.meteoromania.ro/WIGOS/WFS?request=GetCapabilities&service=WFS&version=2.0.0

Still one issue to go (#209) and WFS tests are ok.  Probably just certain relaxed tests need to be further checked and some topics to be clarified.

The issue can be marked as solved in order to be deployed into production.

**Comment by iuriemaxim** [comment]
@carlospzurita Thank you for the fix.

The following service was tested and no errors were trigerred anymore:
https://inspire.meteoromania.ro/WIGOS/WFS?request=GetCapabilities&service=WFS&version=2.0.0

Still one issue to go (#209) and WFS tests are ok.  Probably just certain relaxed tests need to be further checked and some topics to be clarified.
