### ISSUE TITLE
Fully compliant services for "Download Service - Direct WFS"

### ISSUE THREAD

**Issue by thorsten-reitz** [INSPIRE-MIF/helpdesk-validator#216]
Hi all,

We're currently trying to iron out a last few issues with our WFSes according to the Conformance Class: Download Service - Direct WFS. We still have a couple of issues remaining, e.g. on the tests related to Temporal Filters. Now I was wondering if you know about a service that actually fully passes these requirements? I checked a dozen or so but all have many errors in this class.

Thanks a lot & all the best,

Thorsten

**Comment by iuriemaxim** [comment]
Hi Thorsten,

You may see issue #208 that we also found to be triggered due to a bug in the OGC CITE TeamEngine test.
Of interest could be also issues #209 and #210 that are also due to some bugs in the OGC CITE TeamEngine tests for WFS that is used by the ETF validator.
We asked the removal of these tests in the ETF validator until will be fixed by OGC. See also issue #215 to understand that it takes more than 9 months for OGC to make a commit, so any support is welcomed.

Best regards,
Iurie

**Comment by iuriemaxim** [comment]
Hi Thorsten,

You may try https://inspire.meteoromania.ro/WIGOS/WFS?service=WFS&request=GetCapabilities

The issues that still exist are (due to):
- issue https://github.com/inspire-eu-validation/community/issues/208 : Fails the SpatialFilter (OGC 09-026r2, A.8) for multipoint geometries present in the environmental monitoring network element due to issue https://github.com/opengeospatial/ets-wfs20/issues/163   in CITE test, but is passing the tests for single point geometries present in the environmental monitoring facility.  If this https://github.com/opengeospatial/ets-wfs20/pull/154 pull request that waits already for more than 9 months will be committed by OGC, than this issue would be fixed.

- issue https://github.com/inspire-eu-validation/community/issues/209. Fails the Spatial joins (OGC 09-025r2: 7.9.2.5.3, A.1.12) due to issue https://github.com/opengeospatial/ets-wfs20/issues/164  in CITE test. Here is what is written in the code of the OGC CITE Teamengine test for WFS (https://github.com/opengeospatial/ets-wfs20/blob/master/src/main/java/org/opengis/cite/iso19142/joins/SpatialJoinTests.java ) 
![image](https://user-images.githubusercontent.com/20813598/74647563-89f09600-5184-11ea-8ed5-f1d96d38d560.png)
There are at least three **TODO** written in the code

-	The above two CITE tests should be removed in the ETF validator until the two CITE issues mentioned above would be solved by OGC.
-	Supplementary issue https://github.com/inspire-eu-validation/community/issues/210. There is also a CITE test issue related to namespace https://github.com/opengeospatial/ets-gml32/issues/46  that affects the implementation. A workaround can be done in the implementation by hard-coding the schema that is used by OGC in the code of the WFS server implementation.

Would be also interesting to test also the same service against ”Download Service - Predefined WFS”.
This is an important test to be performed for WFS services because the ”Download Service - Direct WFS” test is not testing requirements related to stored queries, as it should normally do.
Most probably the test ”Download Service - Predefined WFS” should be a prerequisite for the test ”Download Service - Direct WFS”. I will raise an issue on this subject as well.
For the ”Download Service - Predefined WFS” there are issues in the ETF Validator such as:
- issue #214 - Pre-defined WFS - check on optional element wfs:boundedBy
- issue #218 - Pre-defined WFS - Service metadata - validate against schema provides an undocumented error, while no error seems to exist in the XML

If these would be fixed in the ETF validator, we could have a WFS reference implementation that would pass the ETF validator.

Please let us know if you have the same errors (if using point and multi-point geometries).

Best regards,
Iurie Maxim

**Comment by iuriemaxim** [comment]
Hi Thorsten,

The OGC CITE Teamengine test is determining the bounding box of the data in WGS84 rounding down the coordinates of the bounding box at two decimals. Even more, for multipart geometries the test is not performing the intersect with the multipart geometry, but with each part of the geometry, one by one. Therefore the implementation of Spatial Filter is completely wrong now. The only solution to avoid it is to move the northern and eastern vertices/points until they will will be within the bounding box that is rounded at two decimals. This means that those points/vertices should be moved a maximum of about 500 meters to south, respectively to west. In most cases this would not be a solution, but it is a workaround that works.

**Comment by thorsten-reitz** [comment]
Hi Iurie,

Thank you very much for the pointers. This clarifies several points. We did investigate a bit into the issue we have with the SpatialFilters as well, some some of the queries contructed there are definitely problematic as well, e.g. filtering on `validTo` despite that field not being popluated in any feature.

**Comment by iuriemaxim** [comment]
Hi Thorsten,

As we are also very interested to understand which are all issues that exist in the ETF Validator in order not to have anymore pseudo-errors, please describe the issue with the ”validTo” element.

In order to see a WFS service that is valid against the OGC SpatialFilter test, we moved the most eastern geometry a little bit to the west and the most northern geometry a little bit to the south. Now the https://inspire.meteoromania.ro/WIGOS/WFS?service=WFS&request=GetCapabilities is passing the SpatialFilter test of the Conformance Class: Download Service - Direct WFS, as can be seen in the image below:


![image](https://user-images.githubusercontent.com/20813598/74656246-6e8e8680-5196-11ea-94bf-2a806109f738.png)

We changed the longitude of the most eastern geometry (point) from 29.7268 to 29.72 and the latitude of the most northern geometry (point) from 48.1948 to 48.19. Now the position of these two geometries (meteorological stations) are incorrect, but the SpatialFilter OGC test is now passed.
This is how it may be possible to implement a work-around in order to pass the test (of course that now the data is incorrect).

Now the service fails only the Spatial join test (OGC 09-025r2: 7.9.2.5.3, A.1.12) due to issue opengeospatial/ets-wfs20#164 in CITE test, as indicated in issue #209 of the ETF. This is that error where in the code of the CITE test is written three times TO DO, proving that the code is incomplete. This issue would not exist if all geometries are declared as polygons (not abstract feature). But all our geometries are points and multi-points and this test is not covered by the OGC CITE TeamEngine WFS 2.0.0 test and therefore the ETF validator triggers an pseudo-error.

Therefore if within your service are only polygons and they would be declared as polygons instead of abstract feature type (as required by the XSD INSPIRE schema), then it could be possible to pass all the WFS tests, assuming the most eastern and the most northern polygon geometry will be changed in order to trim the most eastern and northern coordinates to two decimals. Of course that the GML tests will not be passed as the INSPIRE XSD schema requires the geometries to be abstract feature type and not polygon, but at least it can be tested.

Hope it helps,
Iurie

**Comment by thorsten-reitz** [comment]
Hi Iurie,

The service we are testing is this one (Example GetFeature Request): 

`https://test.haleconnect.de/ows/services/org.171.316ed4a8-86bf-471d-ba42-b4ad1d416ab4_wfs?service=WFS&version=2.0.0&request=GetFeature&count=100&typenames=ns1:SpatialPlan&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns1,http://inspire.ec.europa.eu/schemas/plu/4.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)`

The data is planned land use. According to the ETF test run, it tries to filter these objects using the `validTo` property, which is not popluated in this data, so I would expect the empty return (empty FeatureCollection) to be OK instead of a ETF compliance testing error. It does make me wonder how to get a valid result with such data.

Here is the encoded request the ETF constructs:

```
https://test.haleconnect.de/ows/services/org.171.316ed4a8-86bf-471d-ba42-b4ad1d416ab4_wfs?service=WFS&version=2.0.0&request=GetFeature&count=100&typenames=ns1:SpatialPlan&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns1,http://inspire.ec.europa.eu/schemas/plu/4.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)&filter=%3Cfes%3AFilter%20xmlns%3Ans1%3D%22http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fplu%2F4.0%22%20xmlns%3Awfs%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%2F2.0%22%20xmlns%3Afes%3D%22http%3A%2F%2Fwww.opengis.net%2Ffes%2F2.0%22%3E%3Cfes%3AAfter%3E%3Cfes%3AValueReference%20xmlns%3Atns%3D%22http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fplu%2F4.0%22%3Etns%3AvalidTo%3C%2Ffes%3AValueReference%3E%3Cgml%3ATimeInstant%20xmlns%3Agml%3D%22http%3A%2F%2Fwww.opengis.net%2Fgml%2F3.2%22%20frame%3D%22http%3A%2F%2Fwww.iso.org%2Fiso%2Fiso8601%22%20gml%3Aid%3D%22T01%22%3E%3Cgml%3AtimePosition%3E1983-12-04T15%3A39%3A59.999Z%3C%2Fgml%3AtimePosition%3E%3C%2Fgml%3ATimeInstant%3E%3C%2Ffes%3AAfter%3E%3C%2Ffes%3AFilter%3E
```

**Comment by iuriemaxim** [comment]
While testing https://test.haleconnect.de/ows/services/org.171.316ed4a8-86bf-471d-ba42-b4ad1d416ab4_wfs?service=WFS&version=2.0.0&request=GetCapabilities

there are more errors, not only some due to the Spatial Filter issue:

![image](https://user-images.githubusercontent.com/20813598/74658366-c7601e00-519a-11ea-8567-889c0850e131.png)

![image](https://user-images.githubusercontent.com/20813598/74658460-07bf9c00-519b-11ea-9829-ad6bb491e5fb.png)

Is this the service that you are testing?
https://test.haleconnect.de/ows/services/org.171.316ed4a8-86bf-471d-ba42-b4ad1d416ab4_wfs?service=WFS&version=2.0.0&request=GetCapabilities
If so, than other issues should be fixed first.

Prior changing the coordinates of the most northern and most eastern geometries we had only this pseudo-error for the Spatial Filter OGC test:
![image](https://user-images.githubusercontent.com/20813598/74658999-22dedb80-519c-11ea-8192-08de4bba8575.png)
And of course that pseudo-error for SpatialJoins where in the CITE code is written TODO.

**Comment by iuriemaxim** [comment]
The ”validTo” issue is not linked to SpatialFilter test, but is linked to TemporalFilter test.

![image](https://user-images.githubusercontent.com/20813598/74661357-77845580-51a0-11ea-8db7-6eae694b869e.png)

The difference that I can see between the GetCapabilities requests can be seen in the image below, in the right being yours:

![image](https://user-images.githubusercontent.com/20813598/74661416-9a166e80-51a0-11ea-818b-635e847664a7.png)

Not sure if it is due to this difference, but the XML retrieved by https://test.haleconnect.de/ows/services/org.171.316ed4a8-86bf-471d-ba42-b4ad1d416ab4_wfs?service=WFS&version=2.0.0&request=GetFeature&count=100&typenames=ns1:SpatialPlan&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns1,http://inspire.ec.europa.eu/schemas/plu/4.0),xmlns(wfs,http://www.opengis.net/wfs/2.0) request does not have any elements with gml32 prefix.

We declared xmlns:gml="http://www.opengis.net/gml/3.2", while in your service is declared xmlns:gml=”http://www.opengis.net/gml” and xmlns:gml32=”http://www.opengis.net/gml/3.2”

For our WFS the ETF test will display:
![image](https://user-images.githubusercontent.com/20813598/74661832-67b94100-51a1-11ea-8b7b-f84a93b84b23.png)

We may look also which are the requests that are made by CITE TeamEngine tests on our WFS server.

UPDATE. This is what CITE test reports:
org.testng.SkipException: Feature type has no temporal properties: 
http://inspire.ec.europa.eu/schemas/ef/4.0/EnvironmentalMonitoringFacilities.xsd 

Therefore it may be possible that CITE tests have some other issues as well in relation with Temporal Filter for those feature types that have temporal properties (i.e.: http://inspire.ec.europa.eu/schemas/plu/4.0)

Hope it helps,
Iurie

**Comment by danielnavarrogeo** [comment]
Dear @thorsten-reitz and @iuriemaxim 

Thank you for sharing your findings with the community. In the INSPIRE validation team we are analysing the last issues found related with WFS.

Regarding the availability of fully compliant services with "Download Service - Direct WFS", we encourage the community to share any service that is fully compliant with the mentioned Conformance Class.

Regards

**Comment by iuriemaxim** [comment]
In any implementation with Geoserver and app-schema the numberMatched will be ”unknown” as it is impossible to count the number of matched features and even if it would be implemented it would require a lot of modifications and will be a time consuming process. But numberReturned could be 0 or any other integer.

Therefore the request https://test.haleconnect.de/ows/services/org.171.316ed4a8-86bf-471d-ba42-b4ad1d416ab4_wfs?service=WFS&version=2.0.0&request=GetFeature&count=100&typenames=ns1:SpatialPlan&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns1,http://inspire.ec.europa.eu/schemas/plu/4.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)&filter=%3Cfes%3AFilter%20xmlns%3Ans1%3D%22http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fplu%2F4.0%22%20xmlns%3Awfs%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%2F2.0%22%20xmlns%3Afes%3D%22http%3A%2F%2Fwww.opengis.net%2Ffes%2F2.0%22%3E%3Cfes%3AAfter%3E%3Cfes%3AValueReference%20xmlns%3Atns%3D%22http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fplu%2F4.0%22%3Etns%3AvalidTo%3C%2Ffes%3AValueReference%3E%3Cgml%3ATimeInstant%20xmlns%3Agml%3D%22http%3A%2F%2Fwww.opengis.net%2Fgml%2F3.2%22%20frame%3D%22http%3A%2F%2Fwww.iso.org%2Fiso%2Fiso8601%22%20gml%3Aid%3D%22T01%22%3E%3Cgml%3AtimePosition%3E1983-12-04T15%3A39%3A59.999Z%3C%2Fgml%3AtimePosition%3E%3C%2Fgml%3ATimeInstant%3E%3C%2Ffes%3AAfter%3E%3C%2Ffes%3AFilter%3E

provides a human understandable correct response even if the test is performing a filter on an element that is not present in the XML, namely validTo.

![image](https://user-images.githubusercontent.com/20813598/74667695-70634480-51ac-11ea-96d2-050ad7d0d077.png)


If for example I would ask how many of us are below 50 years, but for none would be indicated the age (as it is not mandatory), then if the system would reply with "0" (zero), than the reply would be technically correct. same would be with a select in a database on a date-time field that has all values NULL or EMPTY.

Probably that the reply "unknown" would be correct as well from the human perspective. But I don't think that an SQL syntax would provide "unknown" if performing a select in a database on a date-time field that has all values NULL or EMPTY. It will provide an error message if the field would not exist at all. So the CITE test either should interpret that the reply is correct, either should verify if a non-mandatory element has values or not and to perform the test on that element only if it has values.

But having in mind that numberMatched will be always "unknown" due to constrains already mentioned at the beginning, then the note that exist in the response would not be correct.

I think that you are right and this is another OGC CITE TeamEngine issue that affects the official INSPIRE ETF validator.

It is one more example why the OGC CITE TeamEngine errors should not be triggered in the ETF, until their issues would not be fixed.

Please raise this as an ETF bug, due to CITE tests that were implemented in the ETF.

It should be known that the OGC CITE tests were developed based on a sample dataset with simple features, while the INSPIRE features are complex and of course different than the ones used for the development of the CITE tests.

Iurie

**Comment by iuriemaxim** [comment]
The Temporal Filter issue mentioned by Thorsten is already reported as a bug to OGC CITE TeamEngine even if the description and conclusion is not really the same. See https://github.com/opengeospatial/ets-wfs20/issues/157

**Comment by iuriemaxim** [comment]
Issue #219 was raised as a conclusion of this discussion.

It looks like there are quite many issues in the OGC CITE TeamEngine tests that affects the official INSPIRE ETF validator.

**Comment by MarcoMinghini** [comment]
Dear @thorsten-reitz and @iuriemaxim,
since this discussion - though very useful - points to multiple issues, each already described separately (and some of them already solved, some pointing to OGC TEAM Engine issues already solved), I would propose to close this issue and continue our discussions separately in each of the other issues.

**Comment by iuriemaxim** [comment]
@MarcoMinghini, indeed it can be closed.
