### ISSUE TITLE
Pre-defined WFS Service metadata validate against schema error

### ISSUE THREAD

**Issue by danieluct** [INSPIRE-MIF/helpdesk-validator#218]
When testing https://inspire.meteoromania.ro/WIGOS/WFS?request=GetCapabilities&service=WFS&version=2.0.0 using "Conformance Class: Download Service - Pre-defined WFS" I receive the following error in the Capabilities>Service metadata>Request and check external ServiceMetadata>Validate against schema section:
"The server experienced a several unexpected error. Please, try again later. if the problem persist, please contact with the helpdesk."
This happens both on the official validator and in the staging environment. The same service was also tested using "Conformance Class: Download Service - Direct WFS" and no  schema validation was reported for the capabilities. The only noticeable characteristic of the external metadata is that the GeoNetwork discovery service that provides the external metadata file appends two empty lines at the end of the response, though this is never reported as an issue when testing it with several other schema validators.

**Comment by danielnavarrogeo** [comment]
Dear @danieluct 

We are developing a solution to this issue. It is related to the provided metadata linked from the ExtendedCapabilities section.

We will let you know when the solution is ready for testing. 

Regards

**Comment by josemasensio** [comment]
Dear @danieluct

After some internal meeting, we agreed to remove the metadata schema validation from WFS since there is no reference to this test on the [Technical Guidance](https://inspire.ec.europa.eu/documents/Network_Services/Technical_Guidance_Download_Services_v3.1.pdf). Now the problem should be solved. You can check this changes on the [Staging Instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Please, could you provide us with your feedback?

Thank you and best regards.

**Comment by danieluct** [comment]
Dear @josemasensio, 
I can confirm the issue is not present anymore on the  staging instance.
Regards.

**Comment by danielnavarrogeo** [comment]
Thank you for your feedback @danieluct 

Regards
