### ISSUE TITLE
Someone successfully deployed the etf docker image on windows server 2016 ?

### ISSUE THREAD

**Issue by apfelnymous** [INSPIRE-MIF/helpdesk-validator#221]
The original repository was archived, so I thought this goes here...

I wanted to setup the etf docker image (https://github.com/etf-validator/etf-webapp-docker) on a windows server 2016. Running `docker-compose up -d` will yield:

`ERROR: client version 1.21 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version`

Anyone encountered this?

**Comment by danielnavarrogeo** [comment]
Dear @apfelnymous 

We are not currently using docker-compose for the ETF deployment. You can follow the following instructions for deployment:

1. Extract the contents of the .zip files from the [current release](https://github.com/inspire-eu-validation/community/releases/download/v1.0.8/etf-release-v1.0.8.zip).

2. Go into the extracted folder and into the etf-webapp.war, select the file WEB-INF/classes/etf-config.properties and modify the etf.webapp.base.url property to the desired base url. By default is localhost:8080/etf-webapp

3. Execute 'docker build -t [TAG_OF_IMAGE] .'

4. Run the built image with 'docker run -p 8080:8080 [TAG_OF_IMAGE]'

You might want to ask in the [etf-webapp repository](https://github.com/etf-validator/etf-webapp) the issue related with docker-compose.

Regards

**Comment by apfelnymous** [comment]
Hello, thank you!

Step 3 will return:
```
C:\Program Files (x86)\docker\docker\docker.exe: failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\docker\windowsfilter\111e6b0a54f05ce7e5d8138bd0daae387cc58dd8e9823cb2b3efc2a
9d70aca95\UtilityVM: The system cannot find the path specified
```
https://github.com/docker/for-win/issues/2119

After looking this up my guess is the image doesnt run on windows server 2016

@jonherrmann 
The readme says:
" Please see the [ETF wiki](https://github.com/interactive-instruments/etf-webapp/wiki) for alternative installation options."
But doesnt lead me to a clue for my OS, any advice ?

**Comment by jonherrmann** [comment]
Hi János,

I have created an initial image for the INSPIRE Executable Test Suites + ETF bundle which has been used for testing purposes. This image is no longer maintained in the old repository within the the etf-validator GitHub organisation, but the INSPIRE Validator image is now distributed here in the inspire-eu-validation organisation.

Please note that I'm not the maintainer of this specific docker image (the dockerfile maintainer information is wrong) and since I don't know the modifications of this image, I unfortunately can't help.

@michellutz @MarcoMinghini 
Perhaps you could describe in the community repository readme file how to install this Docker image and what the prerequisites (operating system, etc.) are.

> We are not currently using docker-compose for the ETF deployment. 

Then the docker-compose file should better not be in the installation package?

**Comment by apfelnymous** [comment]
Thank you for your replies so far.
To make things maybe more obvious:

running the hello-world image would return the same error, except I call it with the tag "nanoserver-sac2016" like this:
`docker run hello-world:nanoserver-sac2016`

**Comment by apfelnymous** [comment]
The docker image used here is running a linux container right ? If yes, then according to this:
https://chunliu.me/2018/02/12/running-linux-containers-on-windows-server-2016/

It cannot work since at work we use windows server 2016 1607

**Comment by carlospzurita** [comment]
Dear @apfelnymous 

Yes, the Docker image is built on top of a Debian image. We have never tried a Windows Server deployment for the INSPIRE validator, so unfortunately we cannot offer much insight for now. It seems that you are right though, given the information in the link that you provided.

Also, we are not using the docker-compose feature. In the next release we will be updating the deployment instructions and documentation for Docker.

**Comment by apfelnymous** [comment]
Dear @carlospzurita 

thank you for the answer, so then Im just gonna switch to the tomcat variant of etf deployment.

Dear @jonherrmann 
Is the admin documentation still current for tomcat ?

The documentation points to a 2.0.0 release:
https://services.interactive-instruments.de/etfdev-af/etf-public-dev/de/interactive_instruments/etf/etf-webapp/2.0.0/etf-webapp-2.0.0.war

which differs in size of the latest one here:
https://github.com/etf-validator/etf-webapp/releases

so I wonder how are they related ?

**Comment by jonherrmann** [comment]
The [Win/Tomcat installation](https://docs.etf-validator.net/v2.0/Admin_manuals/index.html#_installation_on_windows) has been tested on Win 7 & 10. If Oracle is not an option, you could use [AdoptJDK](https://adoptopenjdk.net). I guess you have to install files from the ZIP instead of the files mentioned in the documentation.

**Comment by dperezBM** [comment]
Dear all,

Since this issue had no interaction time ago, we decided to close it. Please feel free to open a new one if needed.

Thank you and best regards.
