### ISSUE TITLE
INSPIRE Validator error: Invalid content was found starting with element '{"http://inspire.ec.europa.eu/schemas/ef/3.0":EnvironmentalMonitoringFacility}'. One of '{"http://www.opengis.net/gml/3.2":AbstractFeature}' is expected.

### ISSUE THREAD

**Issue by LeonorQueiroz** [INSPIRE-MIF/helpdesk-validator#229]
Hello,

I'm harmonizing the EF Bathing Waters and appears the error below:

Conformance class: INSPIRE GML application schemas, General requir Conformance class: INSPIRE GML application schemas, General requir… Failed: 1 / 6 Failed: 1 / 6
Schema validation 
gmlas.b.2: validate XML documents
Messages "XML document 'teste85_27022020.gml': 9:57: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://inspire.ec.europa.eu/schemas/ef/3.0":EnvironmentalMonitoringFacility}'. One of '{"http://www.opengis.net/gml/3.2":AbstractFeature}' is expected."

Can you help me please?

Best regards,
Leonor Queiroz.

**Comment by iuriemaxim** [comment]
Hello Leonor,

You should add the file that is not passing the test or provide the link to the WFS request in order to be able to provide any hint.

Examples of files made according to Environmental Monitoring Facility schema, that are passing the ETF validation, can be retrieved trough the following short-URLs:

https://inspire.meteoromania.ro/ids/EnvironmentalMonitoringFacility.15015

https://inspire.meteoromania.ro/ids/EnvironmentalMonitoringFacility.15015/RelativeHumiditySYNOP

Hope it helps,
Iurie

**Comment by josemasensio** [comment]
Dear @LeonorQueiroz,

In order to replicate what is causing this error, could you please send us the data you are using?
If the information contained in this data is sensitive, please send it to inspire-helpdesk@bilbomatica.com, it will be treated with the maximum privacy and will be deleted once the error is solved. 

Thank you and regards.

**Comment by josemasensio** [comment]
Dear @LeonorQueiroz, 

First of all, thank you for providing the data.

After the email conversation that we got, you mentioned that the problem has been solved.
Please, in order to resolve the issue, we would like you to confirm there is not a problem anymore. Could you verify it?

Please let us know if you need more help.

Regards.

**Comment by josemasensio** [comment]
Dear @LeonorQueiroz , 

As we agreed via mail, you told us that the issue was solved. We will close it. 
Please, if you have any other issue, let us know.

Thank you and best regards.
