### ISSUE TITLE
It is quite odd that while testing metadata files against Metadata TG version 2.0 users are allowed to test the same file against TG version 1.3 in the same test.

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#231]
I raised this issue as I found that the users that are not very familiar with INSPIRE are confused and do not understand exactly how to test metadata files made according to Metadata TG version 2.0 against different conformance classes. And this is due to the fact that a certain logic was not implemented in the ETF validator as users are allowed to select tests which they should not be able to select.

While testing metadata files against Metadata TG version 2.0 users are allowed to test the same file against TG version 1.3 in the same test. This is quite odd and users should not be able to select the tests against TG version 1.3 if they are testing against Metadata TG version 2.0.

No metadata file can be done in order to be conform against both TG version 1.3 and 2.0, as there are significant differences between these two guidelines. Metadata file can be either conform with Metadata TG version 1.3 or with Metadata TG version 2.0.

Also there should be implemented a certain logic for testing metadata files against TG version 2.0. If they would test a metadata of a network service, then they should not be able to test the same file against the test for metadata of a dataset or spatial data service. There are three metadata files types and they are not overlapping:
- metadata of a data set (DS): Conformance Class 1 and 2 (+ common)
- metadata of a network service (NS): Conformance Class 3 and 4 (+ common)
- metadata of a spatial data service (SDS): Conformance Class 5, 6 and 7 (+3 and common)

There should be a certain logic implemented in the validator. Supplementary it would be very useful if the three categories will be somehow delimited by texts or lines within the validator.

If a user wants to test a metadata file of a network service against conformance class 4 or 3, then it should not be able to select any of the tests that are encircled in red.

![image](https://user-images.githubusercontent.com/20813598/75663831-2aad7e00-5c7a-11ea-96b9-2714b8f73633.png).

Same apply if the user wants to test a metadata file of a dataset against conformance class 2 or 1, then it should not be able to select any of the tests that are encircled in red.

![image](https://user-images.githubusercontent.com/20813598/75664787-b96eca80-5c7b-11ea-8b05-21b814972904.png)

And same apply if a user wants to test a metadata file of an SDS against conformance class 7, 6 or 5, then it should not be able to select any of the tests that are encircled in red.
![image](https://user-images.githubusercontent.com/20813598/75665455-df489f00-5c7c-11ea-823d-1cd4da7e969b.png)

**Comment by MarcoMinghini** [comment]
Dear @iuriemaxim,
thanks for this comment. 

> While testing metadata files against Metadata TG version 2.0 users are allowed to test the same file against TG version 1.3 in the same test. This is quite odd and users should not be able to select the tests against TG version 1.3 if they are testing against Metadata TG version 2.0.

We've already had (internally) this discussion in the past. The only reason why the user is able to select at the same time any conformance class for MD TG 1.3 and 2.0 is that they all refer to the same TestObjectType (i.e. they are not mutually exclusive). All the non-selectable conformance classes (e.g. those for services) refer to different TestObjectTypes (i.e. they are mutually exclusive and cannot be selected). This is the reason.

Since we are aware that this can create confusion in some users (especially people who are not familiar with the Validator), and for a number of other reasons, we are already working on developing a customized UI for the INSPIRE Reference Validator (see #10). This will be ready in few months and will make it easier for users to find and select the conformance class(es) they want to test. Please follow the updates on that issue.

For this reason, I will close this issue; I also take the chance to invite you/everyone not to open other issues on the Validator UI, but only focus on the functionality.
