### ISSUE TITLE
As ISO changed the location of ISO_19139 schemas (ITTF), it is impossible to use anymore the validator for testing metadata files made according to version 1.3 of the TG

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#245]
If a user would test any metadata file made according to version 1.3 of the Metadata TG, starting from this week the validator will provide the following internal error because the ISO removed the files that were available at the following location (during this week):
https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml:

![image](https://user-images.githubusercontent.com/20813598/76094923-1b0c9d00-5fcc-11ea-937e-44a9b97df56f.png)

![image](https://user-images.githubusercontent.com/20813598/76095177-848cab80-5fcc-11ea-8f9d-bb4ae346f02a.png)

As the linkage checker (https://inspire-geoportal.ec.europa.eu/linkagechecker.html) is able to validate only metadata files made accordingly to version 1.3 of the TG and the INSPIRE Geoportal is accepting only metadata files made according to TG version 1.3, but the Linckage checker has its own issues, we seek guidance on how to test metadata files that can be imported in the INSPIRE Geoportal and also be valid.

Also metadata files made according to version 1.3 that were valid last week on the staging validator are not anymore valid. Are there any changes made in the staging validator for validating metadata according to TG Version 1.3?

Best reagrds,
Iurie

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

Thank you for raising this issue. We are analyzing the best approach to manage this.

Regards

**Comment by MarcoMinghini** [comment]
Dear all,
ISO introduced this breaking change which at the moment has a big impact on the validation of INSPIRE resources.

We (the JRC Validation team) have already discussed different approaches on how to address this in the best possible way. We also contacted ISO/TC211 (see [here](https://github.com/ISO-TC211/schemas/issues/24)) to first understand from them whether this is a temporary or permanent change. As you can see, they will hopefully restore the resources. If this will not happen, then we will have to make some changes on our side.

In general, I kindly ask you to be patient and avoid to ask the same question in different issues, or to open new issues to report the same problem. As you can see from the high number of issues open everyday in this helpdesk, we are under a heavy workload. I can ensure that we are reading and considering every issue report from the community, and we always take action as soon as we can (of course depending on the priority of the issue). Thank you all for understanding.

**Comment by DeordD** [comment]
Hi all ,

it seems that @MarcoMinghini efforts had effects.

APISO schema is again publicly available:
http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd

![grafik](https://user-images.githubusercontent.com/38787131/77438157-c3e93380-6de5-11ea-9b7a-9ef117ff78db.png)

I have just validated example metadata record sets and both are fully valid in production instance:
http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDd629d1ce-9fdc-48f2-8630-254f65f784b0.html
http://inspire.ec.europa.eu/validator/v2/TestRuns/EID44a98d53-213d-46e4-9471-c441d86c3d0b.html

Can someone els check if all problems are solved (codelists, character encoding, etc.)?

Kind regards.

**Comment by ronaldtse** [comment]
I believe the comment https://github.com/inspire-eu-validation/community/issues/246#issuecomment-604778904 applies here as well. Thanks @MarcoMinghini for bringing up this issue!

**Comment by MarcoMinghini** [comment]
Thanks @ronaldtse for the fruitful discussion in the ISO/TC 211 repository and for informing the INSPIRE Validation community about the outcome. Much appreciated!

**Comment by ronaldtse** [comment]
You're more than welcome @MarcoMinghini ! Feel free to let us know any further issues so we can address on our side 👍

**Comment by danielnavarrogeo** [comment]
Dear all,

Regarding the recent changes in ISO schemas URLs and how it affects TG 1.3, we would like to mention that there will not be further maintenance for MD TG 1.3.

In case a metadata 1.3 is valid against schemas https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/apiso-inspire/apiso-inspire.xsd or https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/iso_19139_20060504/iso_19139_20060504_wrapper.xsd, the schema validation will still pass. 

Otherwise, if the metadata 1.3 fail against those schemas and the declared attribute schemaLocation is https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd the schema validation will fail.

We encourage anyone to migrate metadata from 1.3 to 2.0. To do so, Geonetwork provide the following tool that might be of interest: https://geonetwork-opensource.org/manuals/trunk/en/user-guide/describing-information/inspire-editing.html#migrating-from-technical-guidance-version-1-3-to-version-2-0

We will then close this issue. Please do not hesitate about opening a new issue if you find any.

Regards
