### ISSUE TITLE
Button "Run test again": WFS-Directs Access and WMS supported?

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#290]
Hi all,

I am currently using the function "Run test again" in order to check the compliance of network services against Direct WFS and WMS. After the validation was initially performed the report is as expected sucessfully generated in "Test reports" section.  After click on "Run test again" button the validation didn't start or report containes different error messages comparing to initial report.

![image](https://user-images.githubusercontent.com/38787131/80478804-55e8dc80-894e-11ea-8ab5-8494f03f19f2.png)

1. Download service - Direct WFS

- use "Run test again":
Report had different and incomplete error messages this time.  Following status error message was shown in the top left corner of the report:
![image](https://user-images.githubusercontent.com/38787131/80476796-2dabae80-894b-11ea-9e4e-6796b19323c6.png)

2. View service - WMS
- Case 1: use "Run test again"
Validation didn't start.  

- Case 2: reload the "Test reports" page and use "Run test again"
Report had different and many more error messages comparing to inital report. Status error message was not shown in the report.

**Discussion**
Does validator support the possibility to run the test again for WFS and WMS CCs?

Kind regards,
Dejan

**Comment by danielnavarrogeo** [comment]
Dear @DeordD 

Thank you for opening this issue. We will test what is happening and we will keep you posted.

Regards

**Comment by iuriemaxim** [comment]
I get a similar behavior when testing a WFS service (https://inspire.meteoromania.ro/WIGOS/WFS?service=WFS&request=GetCapabilities)

In order to be able to access the "Run Test Again" there is a small button in the top left corner of the screen that shows the results of the test. Few people will notice it and will not guess what it does.

![image](https://user-images.githubusercontent.com/20813598/95305675-fbee2a80-088e-11eb-84f7-4b70d34307fc.png)

Hitting that button, the browser loads https://inspire.ec.europa.eu/validator//#test-reports

![image](https://user-images.githubusercontent.com/20813598/95305910-4bccf180-088f-11eb-89a3-28a26e938b0e.png)

The results are very different from the previous test (8 steps instead of 389 steps) as it is quite obvious that the OGC tests were not executed and the Status displays an error as can be seen in the image below

![image](https://user-images.githubusercontent.com/20813598/95306247-d281ce80-088f-11eb-8a0a-fde11760db1c.png)

**Comment by ghost** [comment]
@carlospzurita Any news on this?

**Comment by fabiovinci** [comment]
Dear all,

I'm closing this issue since it is related to the old UI.
Please reopen it or open a new one if the error persists in the new UI.
