### ISSUE TITLE
Data specification validation: Which data source formats are supported?

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#293]
**Introduction**
In order to validate GML dataset against "Data Theme" Conformance Classes it is needed to [upload a ressource](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/#start-tests?ids=EIDddecef4b-89a3-4f9d-9246-a50b588fa5a2) in some way. Currently there are two serveral data source formats which should be supported according to instructions for upload of resources.

_1st option: File upload:_
     - XML file
     - GML file
     - ZIP file

![grafik](https://user-images.githubusercontent.com/38787131/80589509-9b72db80-8a1a-11ea-80ae-e457ac743bc0.png)

_2nd option: Remote file (URL)_
     - URL to a GML/XML file
     - URL to a ZIP file

![grafik](https://user-images.githubusercontent.com/38787131/80589767-1dfb9b00-8a1b-11ea-9240-374b547dd687.png)

**Discussion:**
_1st option:_ 
I managed to upload the dataset only using a ZIP file with dataset with xml extension and validate the data set succesfully. 
Direct upload using dataset with xml and gml extension didn't work. Following error message was thrown in both cases:
 
![grafik](https://user-images.githubusercontent.com/38787131/80590500-40da7f00-8a1c-11ea-8991-5f8ea80097e6.png)

2nd option: 
I didn't manage to upload a dataset via WFS 2.0 GetFeature request. Following error message was thrown: 
![grafik](https://user-images.githubusercontent.com/38787131/80590334-02dd5b00-8a1c-11ea-9f41-85699eaaa7d7.png)

**But!**, after few minutes I found the validation report in Test reports section. It seems that error message is bit misleading.  

Q1: Which data formats are supported for upload of INSPIRE data sets?
Q2: Is there any step-by-step-instructions regarding upload of ressources for validation?

Kind regards.

**Comment by ghost** [comment]
P.S. 

It would be great to provide some reference services e.g. WMS 1.3.0, WFS 2.0 and AtomFeed to the community in order to help user to exclude possible errors which are caused by the validator. 

If user thinks that something is wrong with the validator, reference services and datasets should be validated in order to verify the problem in the validator. This approach would definitely simplify discussion here.

This approach was done for metadata records. Reference records can be found here:
https://github.com/inspire-eu-validation/community/tree/master/examples

**Comment by danielnavarrogeo** [comment]
Dear @DeordD 

Which Conformance Class are you using for validation?

Could you provide us the dataset you are using for testing?

Regards

**Comment by ghost** [comment]
Dear @danielnavarrogeo ,

dataset and CCs are provided via e-mail.

Kind regards

**Comment by danielnavarrogeo** [comment]
Thank you @DeordD 

We will analyze the issue and keep you posted.

Regards

**Comment by hogredan** [comment]
Dear @danielnavarrogeo ,

regarding the 2nd option @DeordD mentioned I didn't manage to upload a dataset via URL to a ZIP file. I used http://fbinter.stadt-berlin.de/fb/atom/PS/PS_Naturschutz.zip and got the following error 
![grafik](https://user-images.githubusercontent.com/18457212/87293040-043e0000-c502-11ea-8576-81152ce5355c.png)

Used CCs:
    Conformance class: Application schema, Protected Sites Simple (Version 0.2.1)
    Conformance class: Data consistency, Protected Sites (Version 0.2.0)
    Conformance class: Information accessibility, Protected Sites (Version 0.2.3)
    Conformance class: Reference systems, Protected Sites (Version 0.2.0)

Upload the same ZIP file directly worked.

**Comment by iuriemaxim** [comment]
@hogredan , @DeordD, @carlospzurita 

Related to DeodorD issue: I was able to test data served by WFS several times with no problem as well as XML/GML files by uploading them.

Link for testing Feature types provided via WFS: https://inspire-staging.meteoromania.ro/WIGOS/WFS?service=wfs&version=2.0.0&request=GetFeature&typeNames=ef:EnvironmentalMonitoringFacility&count=2

If the link that was provided was not a request to a WFS such as the above, or to another INSPIRE download service (ATOM, WCS, SOS), then it is normal to receive an error.

But I faced the same issue as @DeordD when performing multiple tests, but this is not because of the validator, but because of incorrect use of the browser. 

Most probably what was done, (as I did it as well) is that after the first test was executed, in order to do the second test, in the browser, the "Back" button was pressed several times, to arrive at the page from which to perform a new test. 

Below the same error that I am obtaining if I am using the browser's "Back" button to perform a new test after a tests was already completed.

![image](https://user-images.githubusercontent.com/20813598/95300870-79fb0300-0888-11eb-88cb-1f14d373a12c.png)

In this case, when executing the second test after using browser's "back" button, the error indicated by @DeordD  is is shown. The correct use of the validator is to open the validator starting page in a new window or to reload the starting page of the validator (delete the last part of the link, starting from # and hit enter).

![image](https://user-images.githubusercontent.com/20813598/95300104-61d6b400-0887-11eb-9037-9c91d8f7bb86.png)

What can be made in the validator, is to indicate that the "Back" button in the browser should not be used for performing a new test, and/or to add a button "perform a new test" after the results of the test are displayed and near the "Cancel" button, or other technical solution if possible to avoid such behavior of using "back" button.

![image](https://user-images.githubusercontent.com/20813598/95302954-47063e80-088b-11eb-823a-a360fc9f5854.png)
![image](https://user-images.githubusercontent.com/20813598/95304500-643c0c80-088d-11eb-861c-839fd62d707a.png)

Regarding the issue indicated by @hogredan, that's correct, a link to a ZIP file will not work and should not work. Providing datasets via a link that is not pointing to an INSPIRE download service, is not an option according to INSPIRE TGs, so this option should not exist.

So, in the second option, only URL of the requests to INSPIRE Download Services should be allowed, such as ATOM, WFS, WCS & SOS.

Datasets packed in ZIP format can be provided via ATOM and they should be accessed with ATOM requests such as http://example.eu/ATOM?request=GetSpatialDataset&spatial_dataset_identifier_code=XXXX .....

Accessing files directly trough a webserver or a FTP server (http://example.eu/file.zip) is not an option according to INSPIRE TGs.

I suggest to change the following text: instead of "Remote file (URL)" to be written "Download Service Request URL".

In the text box to be provided an example such as https://example.eu/WFS?service=wfs&version=2.0.0&request=GetFeature&typeNames=aa:bbb&count=2

The help text on the question mark should be changed as well from:
![image](https://user-images.githubusercontent.com/20813598/95298362-a14fd100-0884-11eb-8228-bf03aa5d16de.png)
into
"URL request to an INSPIRE Download Service serving data in GML 3.2 format (ATOM, WFS, WCS, SOS). The download will be initiated ..."

**Comment by fabiovinci** [comment]
Since the issue is related to the old UI, I will close it.
