### ISSUE TITLE
Add PNG and PDF to the INSPIRE media types register?

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#328]
Hi,

We currently serve a number of INSPIRE Planned Land Use download services and we would like to include related documents in our atom feeds. The related attachments include PDFs and PNGs which contain planning information that helps to explain the vector features. The attachments include georeferenced paper maps and other, regulatory documents. 

We receive errors in the following conformance class, because the types `application/pdf` and `image/png`  are not included in the [INSPIRE media-types register](https://inspire.ec.europa.eu/media-types/):

Conformance Classes/ETS : https://github.com/inspire-eu-validation/download-service/blob/master/atom-pre-defined/dataset-feed-link-media-type.md

Would it be possible to have these types added?

Kind regards,
Kate

**Comment by juanpelegrina** [comment]
Dear @Kate-Lyndegaard,

thanks for your suggestion, we will discuss it internally and let you know what decision is taken.

Regards
Juan

**Comment by carlospzurita** [comment]
Dear @Kate-Lyndegaard 

We are discussing this change on the INSPIRE media types. Can you  please provide us in the meantime the link to your ATOM feed? We would like to check it out in order to get some more insight.

Thank you.

**Comment by Kate-Lyndegaard** [comment]
Dear @carlospzurita,

From our perspective, it would be beneficial to allow the inclusion of additional, related documents in the atom feed because it improves the usability of the data for the end user. The documents provide an enriched context for the data, particularly in the case of the INSPIRE Planned Land Use theme. We acknowledge that the primary purpose of the atom feed is to provide data in multiple formats and/or spatial representations, however we would like to encourage the support of, or at a minimum, the tolerance of, additional media types in the INSPIRE media-types registry so that we are able to serve supportive documents in PDF or PNG file format in our atom feeds.

Here is an example of an INSPIRE compliant Planned Land Use dataset with an atom feed that includes related documents (georeferenced scanned paper maps in PNG and regulatory documents in PDF):
https://test.haleconnect.de/services/bsp/org.318.46e87c78-332f-4b96-ab34-dce3b024f4de/service/atom/id_predefined_dataset

In addition to the media-types issue, TG Requirement 27 states that each 'Dataset Feed' shall contain separate entries for each format/CRS combination in which the pre-defined dataset is available to download. It does not make sense to check media-types such as PDF for a CRS definition, however. A a backwards compatible approach might be to add an attribute to non-spatial data. In summary, we would like to determine a path forward for including supportive documents in our atom feed while at the same time delivering fully INSPIRE compliant services.

Kind regards,
Kate:-)

**Comment by carlospzurita** [comment]
Dear @Kate-Lyndegaard 

Thank you for providing the reasoning behind your issue and the example feed.

As stated in the TG for Download Services, the Atom feed entries are a way to share links to Spatial pre-defined datasets. Following this intepretation, regulatory documentation would not be a part of this, and should not be included in the entries as they don't contain any Spatial objects. Even more, as you commented, it would be an independent definition from the normal entry feed, to take into account cases like not checking CRS definition for a PDF document type.

In the case of supportive PNG files, if they are Spatial resources such as cartography reference, you can always use the supported media types for [images](https://inspire.ec.europa.eu/media-types/image), and transform your data to GeoTIFF or jpeg2000.

We're marking this as discussion to keep the conversation open and you're welcome to share any other feedback.

Kind regards.

**Comment by iuriemaxim** [comment]
Dear all,

Please see issue https://github.com/inspire-eu-validation/community/issues/39

I think that first of all is important to diferentiate between ISDSS and NS services.

If trough an ATOM service will be provided PDFs, PNGs, shapefiles etc, than for sure the ATOM service will not be a Network Service, but an ISDSS.

All conformance classes that are testing services in the validator are for Network Services.

For ISDSS are tested only the metadata files in Conformance Class 5, 6 and 7.

Data providers are already mixing the NS with the ISDSS and these confusions should be removed as they were created when the ISDSS TG appeared in 2016 opening a large door for data providers to create services that are not conformant with Network Services specifications.
See TGs for SDSs https://inspire.ec.europa.eu/Technical-Guidelines2/Spatial-Data-Services/
See TGs for NSs https://inspire.ec.europa.eu/Technical-Guidelines2/Network-Services/

They are separated things even in the menu of the INSPIRE Portal

![image](https://user-images.githubusercontent.com/20813598/85369183-4bedef00-b535-11ea-941e-16ad5480fe65.png)

According to the image below, most probably that the services that @Kate-Lyndegaard is implementing are Invocable SDS or even "another SDS" or out of scope of INSPIRE, so should not comply with NS regulations.

If a data provider wants to provide PDF files, than they could be provided within CI_Citation element by providing an URL to the PDF file. Most INSPIRE schemas has a CI_Citation element.

![image](https://user-images.githubusercontent.com/20813598/85368430-ebaa7d80-b533-11ea-805b-b33d7d42c0d2.png)

**Comment by iuriemaxim** [comment]
@carlospzurita Please also reconsider implementation done for issue #39

**Comment by Kate-Lyndegaard** [comment]
Dear All,

@iuriemaxim For your information we are serving INSPIRE-compliant download services (atom feed). 

We have thousands of customers wishing to fulfil regional reporting obligations, in addition to INSPIRE, and we are working together in an effort to deliver a useable end product. 

The validation community is a forum for constructive discussion:-) Thank you @carlospzurita for your feedback. We will certainly take this into consideration when discussing the architecture of our many, varied network services.

Kind regards,
Kate Lyndegaard

**Comment by iuriemaxim** [comment]
@Kate-Lyndegaard 

I fully agree that ATOM services are INSPIRE compliant, but the data served by that service is  a spatial dataset?

‘spatial data’ means any data with a direct or indirect reference to a specific location or geographical area; [INS DIR, Art. 3].

Could a PDF or a PNG be considered spatial data ?

‘spatial data set’ means an identifiable collection of spatial data;  [INS DIR, Art. 3].

Indeed ATOM is an INSPIRE compliant download network service, but in order to be a network service should it first be a Spatial Data Service.

Spatial data services means the operations which may be performed, by invoking a computer
application, on the spatial data contained in spatial data sets or on the related metadata [INS
DIR, Art. 3].

![image](https://user-images.githubusercontent.com/20813598/85462260-f30e6d00-b5ad-11ea-8328-0416da41ccc7.png)

If the service operates on spatial data, then:

Download service is a service enabling copies of spatial data sets, or parts of such sets, to be
downloaded and, where practicable, accessed directly [INS DIR, Art. 11].

Invocable spatial data service is a spatial data service that fulfils all of the following: (a) has
metadata which fulfils the requirements of Commission Regulation (EC) 1205/2008, (b) has at
least one resource locator that is an access point, (c) is conformant with a documented and
publicly available set of technical specifications providing the information necessary for its
execution. [INS ISDSS, Art. 2.33]

If the services are for regional reporting obligations, in addition to INSPIRE, maybe they should not be  validated against INSPIRE validator.

**Comment by MarcoMinghini** [comment]
Dear @Kate-Lyndegaard,
since quite some time has passed and there has been no further input to the discussion, we believe the issue can be closed and you can take the initial recommendation to convert your georeferenced paper maps and documents in the GeoTiff or jpeg2000 formats.

Should you have addition feedback on this, feel free to open a new issue in the [general helpdesk](https://github.com/INSPIRE-MIF/helpdesk).

**Comment by iuriemaxim** [comment]
Probably this: https://github.com/INSPIRE-MIF/helpdesk-validator/issues/361 and this: https://github.com/INSPIRE-MIF/helpdesk-validator/issues/39 should be considered too in relation to the answer provided by @MarcoMinghini
