### ISSUE TITLE
NEW ATS/ETS [staging] for Data Specification on Land Use

### ISSUE THREAD

**Issue by juanpelegrina** [INSPIRE-MIF/helpdesk-validator#330]
We are currently working on the development of the Land Use Data specification. Once the development is done, we will deploy it on staging to be tested by the community.

**Comment by fabiovin** [comment]
The ATS is already available, you can find it [here](https://github.com/inspire-eu-validation/data-lu/tree/3.0). All feedback is welcome.
The ETS is under development.
We are looking for some harmonised GML datasets in order to test the ETS, so also, in this case, all inputs are welcome.

Thanks for your collaboration.

**Comment by juanpelegrina** [comment]
ETS for data theme Data Specification on Land Use has been deployed on [staging,](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) please feel free to test your data against. Any feedback will be much appreciated.

You can find further information for LU data theme and their conformance classes on [ATS](https://github.com/inspire-eu-validation/data-lu) and [ETS](https://github.com/inspire-eu-validation/ets-repository/tree/data-lu)

Thanks for your collaboration

**Comment by apfelnymous** [comment]
Hello, I tested my existing land use gml file with the staged Validator - see my attached file.
One Error is about the hilucs value I used:

> XML document 'gesamtwald2elu.gml', ExistingLandUseObject 'Kommunalwald_1019_lagesamt': The property 'hilucsLandUse' has a value 'https://inspire.ec.europa.eu/codelist/HILUCSValue/1_2_Forestry' that is not one of the allowed values listed at https://inspire.ec.europa.eu/codelist/HILUCSValue.

Wether I set the parent value like in this test or a child value like: 

> https://inspire.ec.europa.eu/codelist/HILUCSValue/1_2_3_ForestryBasedOnContinuousCover

The error is the same saying that its not allowed, what am I not seeing here ?

[TestRunELU.zip](https://github.com/inspire-eu-validation/community/files/5117309/TestRunELU.zip)

**Comment by carlospzurita** [comment]
Dear  @apfelnymous 

We are looking into this error. Could yo please provide us with the GML file that you are using for this test, or at least a sample dataset?

Also, this issue is intended to serve as public announcement. For new issues on this, we suggest to open them as independent one to ease the administration of the helpdesk.
