### ISSUE TITLE
Errors in WMS validation. (layer names ":" and ".")

### ISSUE THREAD

**Issue by pmendive** [INSPIRE-MIF/helpdesk-validator#332]
Hello

I am performing validations on an INSPIRE WMS service and I am encountering the following error. (image)
![image](https://user-images.githubusercontent.com/49978896/84868232-a4784480-b07c-11ea-8b81-f8ce7e749ab4.png)

We are generating this service with geoserver 2.17 and at the moment it does not seem easy that we can solve it.

My proposal is if it is possible that the validator takes into account the ":" as well as ".". of course the identifiers in the metadata files would always be aligned.

http://epa-inspire-geoserver.eu-west-1.elasticbeanstalk.com/geoserver/wms?service=WMS&version=1.3.0&request=GetCapabilities

thanks

**Comment by carlospzurita** [comment]
Dear @pmendive

We recently solved another [issue](https://github.com/inspire-eu-validation/community/issues/39) with non-harmonized layer names. We changed the result of the test from FAILED to MANUAL REVIEW in case it does not fit in any value from INSPIRE. However, yours would not be considered passed anyway.

The check is made taking the layer name declared in the WMS and comparing directly with the list published in the registry, using the string as they are. We would need to execute a replacement operation to check the validity of the name from your services.

We will discuss internally and see if this can be performed safely, and get back to you with a response.

**Comment by iuriemaxim** [comment]
Dear @pmendive, @carlospzurita 

There are solutions also with Geoserver to serve WMS layer names with "." instead of ":".

You may have a look at
https://inspire-staging.meteoromania.ro/WIGOS/WMS?service=wms&version=1.3.0&Request=GetCapabilities

You may see layer names such as for example ACMF.GRIB910.Default

I am not in favor of this implementation as technologically it is possible to have layer names with dots in Geoeserver. If this implementation  will be done, then will be more complicated to ensure interoperability (@MarcoMinghini).

Iurie

**Comment by ahuarte47** [comment]
Hi, @iuriemaxim you are right for WMS, technologically it is possible, but not in all cases. 

As far we know, only if you create all layers in one unique workspace and you disable the prefix-name setting of that workspace in GeoServer, you can get complex names as you want including dots.

But it is not possible if you want to configure the INSPIRE compliant WFS Services too. We use the app-schema plugin to configure each layer conforming the WFS specification, and you need to create each layer in its respective workspace (for example, CadastralParcel in CP, EnvironmentalMonitoringFacilities in EF and so on) because each layer uses its respective workspace to get its respective INSPIRE XSD schema:
- CP:CadastralParcel --> https://inspire.ec.europa.eu/schemas/cp/4.0/CadastralParcels.xsd
- EF:EnvironmentalMonitoringFacilities --> https://inspire.ec.europa.eu/schemas/ef/4.0/EnvironmentalMonitoringFacilities.xsd

In this case you can not use one unique workspace for all layers that you want to be conforming to the INSPIRE WFS specification too.

**Comment by iuriemaxim** [comment]
From our experience WMS should not be based on complex feature types as those that are necessary for WFS. Therefore two separate instances should exist for Geoserver, one for WMS and anotherone for WFS.
For a conformant INSPIRE implementation will come to the conclusion that even more Geoserver instances are needed in order to comply with Requirement 52 ”A separate WFS endpoint shall be provided for each INSPIRE dataset thus providing one dataset per GetCapabilities response.”
The implementation of isolated workspaces that we required for Geoserver are unfortunately not solving yet the problem, so the only solution is still to use multiple Geoserver instances.

See some long time ago discussions here: https://inspire.ec.europa.eu/forum/discussion/view/88206/it-seems-that-there-is-no-fully-compliant-solution-to-serve-multiple-harmonised-datasets-trough-wfs-20?offset=10

I am not in favor of this implementation as this would be against the TGs and as there are solutions to comply with the TGs even if using Geoserver.

Iurie

**Comment by ahuarte47** [comment]
Hi @iuriemaxim, thank you very much for your comments and advices.

**Comment by iuriemaxim** [comment]
Hi @ahuarte47 Glad to help. Thank you for raising this issue as I was able to spot this issue https://github.com/inspire-eu-validation/community/issues/39 where I made some comments too

**Comment by iuriemaxim** [comment]
@carlospzurita, @pmendive Please mark this as discution and close it as a solution exist for data providers and no changes should be made in the validator,

**Comment by fabiovin** [comment]
Dear all,

I agree with @iuriemaxim, the layers name is a requirement of the Implementing rule (COMMISSION REGULATION (EU) No 1089/2010
of 23 November 2010 and its amendments), therefore the validator must verify it as required and cannot accept any other values in place of the dot.

**Comment by iuriemaxim** [comment]
@fabiovin Please see also issue https://github.com/inspire-eu-validation/community/issues/39 that was mentioned in this thread by @carlospzurita , because the fix already made is against the IRs and TGs.

Iurie

**Comment by pmendive** [comment]
many thanks

**Comment by iuriemaxim** [comment]
@carlospzurita: Please review also https://github.com/inspire-eu-validation/community/issues/39
