### ISSUE TITLE
ManagementRestrictionOrRegulationZone.competentAuthority.role and ManagementRestrictionOrRegulationZone.legalBasis reported as missing even though attributes are voidable and nilReason is provided

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#339]
This concerns the staging instance of the validator.

It reports an error for ManagementRestrictionOrRegulationZone.competentAuthority.role even though ManagementRestrictionOrRegulationZone.competentAuthority is voidable and the dataset contains a nilReason value for it. The same is true for the association ManagementRestrictionOrRegulationZone.legalBasis

- According to [this thread](https://wayback.archive-it.org/12090/20210119172006/https://inspire.ec.europa.eu/forum/discussion/view/266637/managementrestrictionorregulationzonecompetentauthority-voidable-but-role-mandatory) in the Thematic Clusters, this is an error in the validator
- The constraint that is checked here stems from the additional constraints for the featuretype defined in the implementing rules (see link in thematic cluster)
- The testIds are EIDf7d8aafd-a2cd-45fb-b553-f03cd2cc5258 and EID1ac9de98-f3f4-42d6-92e6-fddc72ade639
- I would need to check with my customer if I can deliver the file. Please let me know in case it is needed.

**Comment by carlospzurita** [comment]
Dear @JohannaOtt 

Thank you for your report. It would be very useful to have the original file to test this issue, because we are unable to find the reference EID that you mentioned. In the meantime, we are checking the implementing rules and the ETS code for this.

**Comment by fabiovin** [comment]
Dear @JohannaOtt.
regarding the _legalBasis_ attribute we discussed on it in [this issue](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/333), could you please have a look at my comment?

Regarding _competentAuthority.role_ attribute you are right, the competentAuthority attribute is mandatory but voidable, so if it is not present in the dataset (i.e. encoded as follow: `<am:competentAuthority xsi:nil="true" nilReason="https://inspire.ec.europa.eu/codelist/VoidReasonValue/Unknown"/>`, for example) the validator should not raise an error.

@carlospzurita Could you please update the related ETS accordingly? 

Thanks

**Comment by carlospzurita** [comment]
Dear alll,

A fix for this issue has been published on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). Please let us know if there is any other problem with this.

**Comment by JohannaOtt** [comment]
Sorry for the late reply - I was on vacation.

> regarding the legalBasis attribute we discussed on it in this issue, could you please have a look at my comment?

@fabiovin Which issue are you referring to?


@carlospzurita I can confirm that there is no validation error any more concerning the competentAuthority in the staging instance - nonetheless I would like to keep this issue open until the handling of legalBasis is clarified, too.

**Comment by fabiovin** [comment]
Dear @JohannaOtt,
sorry, I forgot the link.
Here is the discussion: https://github.com/INSPIRE-MIF/helpdesk-validator/issues/333

**Comment by sMorrone** [comment]
Dear @JohannaOtt and @fabiovin ,
I already posted a reply to the I[NPIRE Community Forum discussion](https://inspire.ec.europa.eu/forum/discussion/view/266637/managementrestrictionorregulationzonecompetentauthority-voidable-but-role-mandatory#elgg-object-266875) but, as I also wrote there, it is important that _"discussions ongoing here, involving thematic domain experts as well as INSPIRE experts, are aligned to  /taken into  consideration by the experts/ developers of the INSPIRE Validator team (and viceversa of course)_."

So coming to the _legalBasis_ question, we should consider that the constraint “_specify at least the most specific legal instrument”_ would have acted in the same manner on a ‘non-voidable’ association. 
Therefore, with respect to what stated by Fabio "_with voidable association + constraint instead of mandatory association it is possible  to better clarify what is required_" , the legalBasis was not made voidable with the aim to force it to 'non-voidable' through a constraint ... that would be quite odd... 
In my view, legalBasis having ‘voidable’ stereotype means that in the data specification it is considered possible that no  legalBasis information is contained in the source spatial data set OR that no corresponding value can be derived at reasonable costs --> For those cases a void value can be provided, and the Validator should NOT raise an error.

The key to the correct interpretation of the constaint can be found in the latter part of the sentence “_At least the most specific legal instrument that required the establishment of zone shall be provided_ **using the legalBasis association role”** (so, for example, should the most specific legal instrument be known to you and should this be an action plan, you shall not use the 'plan' association to provide it but the 'legalBasis' association).

So, what do you think?

All the best,
Stefania

**Comment by KathiSchleidt** [comment]
Also, based on 2007/2/EC Article 4 §4. "This Directive does not require collection of new spatial data."
What is not known need not be provided

**Comment by fabiovin** [comment]
Dear all,
let's continue the discussion on the INSPIRE Community Forum, and then we will report the outcomes here.
