### ISSUE TITLE
ERROR Assertion failed with error 'TR.invalidSchema' in WMS View Service ETS

### ISSUE THREAD

**Issue by klimeto** [INSPIRE-MIF/helpdesk-validator#342]
Dear developers,

Our national provider has problems to validate their Web Map Service using your validator production instance and experiences problems to get their service validated. I have tried to validate their service with the following inputs:

- ETF instance used: https://inspire.ec.europa.eu/validator/
- ETS used: Conformance Class: View Service - WMS
- WMS service endpoint used: https://zbgisws.skgeodesy.sk/inspire_administrative_units_wms/service.svc/get?request=GetCapabilities&service=WMS&VERSION=1.3.0

Resulting validation log throws several assertion and exception errors:

```bash
08.07.2020 08:33:30 - Preparing Test Run Test run on 10:33 - 08.07.2020 with test suite Conformance Class: View Service - WMS (initiated Wed Jul 08 08:33:30 UTC 2020)
08.07.2020 08:33:30 - Resolving Executable Test Suite dependencies
08.07.2020 08:33:30 - Preparing 1 Test Task:
08.07.2020 08:33:30 -  TestTask 1 (0d0c034b-cb0e-4158-94a4-cc265b15a563)
08.07.2020 08:33:30 -  will perform tests on Test Object 'INSPIRE View Service - Administrative Units' by using Executable Test Suite 'Conformance Class: View Service - WMS (EID: eec9d674-d94b-4d8d-b744-1309c6cae1d2, V: 1.0.7 )'
08.07.2020 08:33:30 -  with parameters: 
08.07.2020 08:33:30 - testIntensive = 
08.07.2020 08:33:30 - authMethod = basic
08.07.2020 08:33:30 - testRunTags = 
08.07.2020 08:33:30 - Test Tasks prepared and ready to be executed. Waiting for the scheduler to start.
08.07.2020 08:33:30 - Setting state to CREATED
08.07.2020 08:33:30 - Changed state from CREATED to INITIALIZING
08.07.2020 08:33:31 - Starting TestRun.7e2319e0-1ce2-4af1-840a-a7e8df38b494 at 2020-07-08T08:33:32Z
08.07.2020 08:33:32 - Changed state from INITIALIZING to INITIALIZED
08.07.2020 08:33:32 - Project Properties: 
08.07.2020 08:33:32 - testIntensive -  
08.07.2020 08:33:32 - authMethod - basic 
08.07.2020 08:33:32 - testRunTags -  
08.07.2020 08:33:32 - serviceEndpoint - https://zbgisws.skgeodesy.sk/inspire_administrative_units_wms/service.svc/get?request=GetCapabilities&service=WMS&VERSION=1.3.0 
08.07.2020 08:33:32 - username -  
08.07.2020 08:33:32 - authUser -  
08.07.2020 08:33:32 - authMethod - basic 
08.07.2020 08:33:32 - TestRunTask initialized
08.07.2020 08:33:33 ERROR Assertion failed with error 'TR.invalidSchema'
08.07.2020 08:33:44 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 08:33:44 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 08:33:44 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 08:33:44 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 08:33:44 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 08:33:44 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 08:33:44 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 08:33:44 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 08:33:44 ERROR Assertion failed with error 'TR.getMapSupportedFormat'
08.07.2020 08:33:44 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 08:33:44 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 08:33:49 - Releasing resources
08.07.2020 08:33:49 - Changed state from INITIALIZED to RUNNING
08.07.2020 08:33:50 - Duration: 19sec
08.07.2020 08:33:50 - TestRun finished
08.07.2020 08:33:50 - Changed state from RUNNING to COMPLETED
```

which results in all testing steps to fail.

Could you please test the above mentioned WMS endpoint and provide som e feedback to us?

Many thanks,
Tomas Kliment

**Comment by iuriemaxim** [comment]
Most probably it is due to the schema used.

Instead of the INSPIRE View Services (VS) schema:
http://inspire.ec.europa.eu/schemas/inspire_vs/1.0/inspire_vs.xsd

the GetCapabilities document is using this schema:
https://zbgisws.skgeodesy.sk/rest/directories/arcgisforinspire/schema/networkservices/inspire_vs/1.0/inspire-wms-extension.xsd

The differences between the two schemas can be checked side by side opening both above links in separate browser windows or preferably by using compare documents in Notepad++. If they are not the same, the test should not be passed.

Supplementary, the differences between two GetCapabilities documents may be checked if comparing the provided URL:
https://zbgisws.skgeodesy.sk/inspire_administrative_units_wms/service.svc/get?request=GetCapabilities&service=WMS&VERSION=1.3.0
with this one:
https://inspire-staging.meteoromania.ro/WIGOS/WMS?service=WMS&version=1.3.0&request=GetCapabilities

What can be observed is that accessing the link http://inspire.ec.europa.eu/schemas/inspire_vs/1.0/inspire_vs.xsd is opening it in the browser, while accessing the the link https://zbgisws.skgeodesy.sk/rest/directories/arcgisforinspire/schema/networkservices/inspire_vs/1.0/inspire-wms-extension.xsd a file it is saved locally.

It may be then, that the MIME type is not correctly provided.

Hope it helps,
Iurie

**Comment by carlospzurita** [comment]
Dear @klimeto 

Checking the logs we saw an exception from parsing the response of your GetCapabilities document in several TestSeps

`2020-07-08 10:11:46.798 [Thread-782] ERROR s.errorlog - org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
org.xml.sax.SAXParseException: Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at groovy.util.XmlSlurper.parse(XmlSlurper.java:147)
	at groovy.util.XmlSlurper.parse(XmlSlurper.java:200)
	at groovy.util.XmlSlurper.parseText(XmlSlurper.java:226)
	at groovy.util.XmlSlurper$parseText.call(Unknown Source)
	at Script1.run(Script1.groovy:2)
	.
        .
       .
`

We are debugging the response the TestDrvier is getting, but one suspect could very well be the declared schema as @iuriemaxim has commented, seeing that this problem is thrown at XML parser.

**Comment by klimeto** [comment]
Dears,

I have communicated this issue with the provider and they provided a testing instance of the same WMS where they use the VS schema from `inspire.ec.europa.eu` : 

`https://test-zbgisws.skgeodesy.sk/inspire_administrative_units_wms/service.svc/get?SERVICE=WMS&REQUEST=GetCapabilities`

However the same problem appears also there:

```bash
08.07.2020 11:57:21 - Preparing Test Run Test run on 13:57 - 08.07.2020 with test suite Conformance Class: View Service - WMS (initiated Wed Jul 08 11:57:21 UTC 2020)
08.07.2020 11:57:21 - Resolving Executable Test Suite dependencies
08.07.2020 11:57:21 - Preparing 1 Test Task:
08.07.2020 11:57:21 -  TestTask 1 (c89d8070-9caf-4d96-a476-e2a3398e915a)
08.07.2020 11:57:21 -  will perform tests on Test Object 'INSPIRE View Service - Administrative Units' by using Executable Test Suite 'Conformance Class: View Service - WMS (EID: eec9d674-d94b-4d8d-b744-1309c6cae1d2, V: 1.0.7 )'
08.07.2020 11:57:21 -  with parameters: 
08.07.2020 11:57:21 - testIntensive = 
08.07.2020 11:57:21 - authMethod = basic
08.07.2020 11:57:21 - testRunTags = 
08.07.2020 11:57:21 - Test Tasks prepared and ready to be executed. Waiting for the scheduler to start.
08.07.2020 11:57:21 - Setting state to CREATED
08.07.2020 11:57:21 - Changed state from CREATED to INITIALIZING
08.07.2020 11:57:21 - Starting TestRun.756dd227-8cb4-4fb4-9931-8838504efddd at 2020-07-08T11:57:23Z
08.07.2020 11:57:23 - Changed state from INITIALIZING to INITIALIZED
08.07.2020 11:57:23 - Project Properties: 
08.07.2020 11:57:23 - testIntensive -  
08.07.2020 11:57:23 - authMethod - basic 
08.07.2020 11:57:23 - testRunTags -  
08.07.2020 11:57:23 - serviceEndpoint - https://test-zbgisws.skgeodesy.sk/inspire_administrative_units_wms/service.svc/get?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0 
08.07.2020 11:57:23 - username -  
08.07.2020 11:57:23 - authUser -  
08.07.2020 11:57:23 - authMethod - basic 
08.07.2020 11:57:23 - TestRunTask initialized
08.07.2020 11:57:24 ERROR Assertion failed with error 'TR.invalidSchema'
08.07.2020 11:57:39 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 11:57:39 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 11:57:39 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 11:57:39 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 11:57:39 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 11:57:39 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 11:57:39 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 11:57:39 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 11:57:39 ERROR Assertion failed with error 'TR.getMapSupportedFormat'
08.07.2020 11:57:39 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 11:57:39 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.07.2020 11:57:45 - Releasing resources
08.07.2020 11:57:45 - Changed state from INITIALIZED to RUNNING
08.07.2020 11:57:45 - Duration: 24sec
08.07.2020 11:57:45 - TestRun finished
08.07.2020 11:57:45 - Changed state from RUNNING to COMPLETED
```

**Comment by iuriemaxim** [comment]
Compare this header
<WMS_Capabilities 
xmlns:inspire_vs="http://inspire.ec.europa.eu/schemas/inspire_vs/1.0" 
xmlns:inspire_common="http://inspire.ec.europa.eu/schemas/common/1.0" 
xmlns="http://www.opengis.net/wms" 
xmlns:xlink="http://www.w3.org/1999/xlink" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
version="1.3.0" updateSequence="1153" 
xsi:schemaLocation=
"http://www.opengis.net/wms https://inspire-staging.meteoromania.ro/WIGOS/WMS/schemas/wms/1.3.0/capabilities_1_3_0.xsd 
http://inspire.ec.europa.eu/schemas/inspire_vs/1.0 
http://inspire.ec.europa.eu/schemas/inspire_vs/1.0/inspire_vs.xsd">

with this one
<WMS_Capabilities 
xmlns="http://www.opengis.net/wms" 
xmlns:esri_wms="http://www.esri.com/wms" 
xmlns:inspire_common="http://inspire.ec.europa.eu/schemas/common/1.0" 
xmlns:inspire_vs="http://inspire.ec.europa.eu/schemas/inspire_vs/1.0" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
version="1.3.0" 
xsi:schemaLocation="http://inspire.ec.europa.eu/schemas/inspire_vs/1.0 
http://inspire.ec.europa.eu/schemas/inspire_vs/1.0/inspire_vs.xsd">

First of all it is missing the location of the WMS1.3.0 schema and most probably it is important to be provided in the xsi:schemaLocation (capabilities_1_3_0.xsd).

Second xmlns:esri_wms="http://www.esri.com/wms"  is not expected to be present and no esri_wms element should be present in the GetCapabilities response, but the error is not due to this.

Then there are other differences easy to spot (i.e. declaration for xmlns:xlink prefix is missing in the header even if the prefix is used. Probably that declaring it only within the XML is not enough).

Order of the elements in the header is also important, especially the order of schemas in the schema location, even if no standard exist to impose this, but most probably depends on the libraries that are used within the testing code.

Try to do the following: Copy and paste the result in an XML validator, or even in Notepad++ and validate the XML content against the declared schema. If it does not validate, fix the issue.

There is no error in the validator, just that it is not providing an inteligible error to the user.

The WMS service provided should not pass the View Service WMS Conformance Class test if the response is not a valid XML.

The validator could verify the header of the response and if something is wrong in the header could just provide an error that the header is incorrect. It could also provide an example of an expected header.

Hope it helps as this aspect was covered in other issues. If necessary I can indicate them.

The title of the issue could be probably renamed into ”validator is not checking the header of the response”.

**Comment by iuriemaxim** [comment]
Error provided by Notepad++: 

![image](https://user-images.githubusercontent.com/20813598/86919678-47c6f180-c131-11ea-8bbe-dc53dea51833.png)

The response is not a valid XML file. Is not in relation with INSPIRE or WMS, but just in relation with testing the XML.

**Comment by klimeto** [comment]
@carlospzurita @iuriemaxim The service provider updated the GetCapabilities XML available from here: `https://test-zbgisws.skgeodesy.sk/inspire_administrative_units_wms/service.svc/get?SERVICE=WMS&REQUEST=GetCapabilities`. 
When I try to validate it in both Oxygen Editor and Notepad++ I get no validation errors.

However when I try to validate it using INSPIRE Reference Validator I do get always the same error:

```bash
09.07.2020 11:49:24 - Preparing Test Run Test run on 13:49 - 09.07.2020 with test suite Conformance Class: View Service - WMS (initiated Thu Jul 09 11:49:24 UTC 2020)
09.07.2020 11:49:24 - Resolving Executable Test Suite dependencies
09.07.2020 11:49:24 - Preparing 1 Test Task:
09.07.2020 11:49:24 -  TestTask 1 (34320d2d-8773-4600-910c-6c978bff75da)
09.07.2020 11:49:24 -  will perform tests on Test Object 'INSPIRE View Service - Administrative Units' by using Executable Test Suite 'Conformance Class: View Service - WMS (EID: eec9d674-d94b-4d8d-b744-1309c6cae1d2, V: 1.0.7 )'
09.07.2020 11:49:24 -  with parameters: 
09.07.2020 11:49:24 - testIntensive = 
09.07.2020 11:49:24 - authMethod = basic
09.07.2020 11:49:24 - testRunTags = 
09.07.2020 11:49:24 - Test Tasks prepared and ready to be executed. Waiting for the scheduler to start.
09.07.2020 11:49:24 - Setting state to CREATED
09.07.2020 11:49:24 - Changed state from CREATED to INITIALIZING
09.07.2020 11:49:25 - Starting TestRun.6e4f2792-5de0-4be7-bdbf-51b908a1df54 at 2020-07-09T11:49:26Z
09.07.2020 11:49:26 - Changed state from INITIALIZING to INITIALIZED
09.07.2020 11:49:26 - Project Properties: 
09.07.2020 11:49:26 - testIntensive -  
09.07.2020 11:49:26 - authMethod - basic 
09.07.2020 11:49:26 - testRunTags -  
09.07.2020 11:49:26 - serviceEndpoint - https://test-zbgisws.skgeodesy.sk/inspire_administrative_units_wms/service.svc/get?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0 
09.07.2020 11:49:26 - username -  
09.07.2020 11:49:26 - authUser -  
09.07.2020 11:49:26 - authMethod - basic 
09.07.2020 11:49:26 - TestRunTask initialized
09.07.2020 11:49:27 ERROR Assertion failed with error 'TR.invalidSchema'
09.07.2020 11:49:38 ERROR Exception occurred in Test Step: java.lang.NullPointerException
09.07.2020 11:49:38 ERROR Exception occurred in Test Step: java.lang.NullPointerException
09.07.2020 11:49:38 ERROR Exception occurred in Test Step: java.lang.NullPointerException
09.07.2020 11:49:38 ERROR Exception occurred in Test Step: java.lang.NullPointerException
09.07.2020 11:49:38 ERROR Exception occurred in Test Step: java.lang.NullPointerException
09.07.2020 11:49:38 ERROR Exception occurred in Test Step: java.lang.NullPointerException
09.07.2020 11:49:38 ERROR Exception occurred in Test Step: java.lang.NullPointerException
09.07.2020 11:49:38 ERROR Exception occurred in Test Step: java.lang.NullPointerException
09.07.2020 11:49:38 ERROR Assertion failed with error 'TR.getMapSupportedFormat'
09.07.2020 11:49:38 ERROR Exception occurred in Test Step: java.lang.NullPointerException
09.07.2020 11:49:38 ERROR Exception occurred in Test Step: java.lang.NullPointerException
09.07.2020 11:49:42 - Releasing resources
09.07.2020 11:49:42 - Changed state from INITIALIZED to RUNNING
09.07.2020 11:49:43 - Duration: 18sec
09.07.2020 11:49:43 - TestRun finished
09.07.2020 11:49:43 - Changed state from RUNNING to COMPLETED
```

Can you check in your application logs what is actually happening at the application level?

Thanks,
Tomas

**Comment by carlospzurita** [comment]
Dear @klimeto 

We are investigating the issue debugging the response in the application level. As we shared yesterday, the log files show an unexpected content in the service response. We will get back to you with more information as soon as we can.

**Comment by iuriemaxim** [comment]
@klimeto Did tou tried with OGC CITE Teamengine? If it does not pass te OGC CITE tests, will not pass the INSPIRE tests as well. It may be that OGC CITE to report a Nullpointer exception as we encounter a simmilar issue with OGC validator and raised there an issue. To overcome that issue we modified and recompiled the code of Geoserver.
For ArcGIS for INSPIRE this solution however would not be possible and you will need to raise a bug @ ESRI.

Try to see if there is any conformant solution based on ArcGIS for INSPIRE.

You may also try to contact Conterra Gmbh as they developed ArcGIS for INSPIRE.


Look at the issue #210 that we raised for Null pointer Exception as it may be related to your issue as well.

**Comment by fabiovinci** [comment]
Dear @klimeto,

do you still have the reported errors?

**Comment by fabiovinci** [comment]
Dear @klimeto,
since there was no reply from your side, I will close the issue.
Please reopen it or open a new issue if the error persists.
