### ISSUE TITLE
Question about "Access to the private subnet was rejected" situation.

### ISSUE THREAD

**Issue by pandzel-zz** [INSPIRE-MIF/helpdesk-validator#370]
I remember I have already asked a very similar question, but never got it resolved, so my apologies for doing it again. I really need to get it going.

I have installed 2020.2 version of the testing suite within my docker on Windows 10 Pro. I am running "Predefined WFS" test and I am giving an URL to the service on my development machine. That URL looks like "http://<my machine>.<my domain>.com/..." but it's getting rejected with the message in the nice red box stating: 

Test Run Initialization failure!
Access to the private subnet was rejected by a configuration setting!

All I did before is I put my IP address in the /etc/hosts file.

Can anyone give me baby-steps how to by-pas that issue? Greatly appreciated.

**Comment by carlospzurita** [comment]
Dear @pandzel 

I suppose you are referring to issue #323 that was related to this. Was it useful our advice there? The issue was closed by yourself, so we left it as solved. 

Another option here could be to modify the configuration file of the validator to allow access to private networks, given that this is not a production environment. The steps for this are:

1. Download the file inspire-validator-2020.2.zip in the [release page](https://github.com/inspire-eu-validation/community/releases/tag/v2020.2)
2. Extract the contents, and inside the .war file, open the file `WEB-INF/classes/etf-config.properties` and uncomment and set to `true` this line 
```
# etf.testobject.allow.privatenet.access = false
```
3. Save the changes and update the .war file
4. In the extracted folder from the release, execute `docker build -t inspire-validator:2020.2`, then execute `docker run --name inspire-validator -d -p 8080:8080 -v ~/etf:/etf inspire-validator:2020.2`

This way, you are executing a modified version of the Docker image provided in the release with the change in the properties applied. This configuration normally is left to "false" to disallow the access to possible malicious sites.

Please let us know if this has been useful, and if you need any more feedback, we are happy to help.

Kind regards.

**Comment by pandzel-zz** [comment]
Success.

In addition to the steps above I had to modify res/docker-entrypoint.sh with the command: `echo "10.212.11.201 <myhost>.<mydomain>.com" >> /etc/hosts` before `cp /etc/hosts /etc/squid_hosts` line, otherwise 'Initialization and basic check' phase would fail due to inability to fetch XSD schema definition from my host.

Thanks for your help.
