### ISSUE TITLE
ELU - hilucs value

### ISSUE THREAD

**Issue by apfelnymous** [INSPIRE-MIF/helpdesk-validator#376]
Hello, I tested my existing land use gml file with the staged Validator - see my attached file (TestResult + gml file)
One Error is about the hilucs value I used:

> XML document 'gesamtwald2elu.gml', ExistingLandUseObject 'Kommunalwald_1019_lagesamt': The property 'hilucsLandUse' has a value 'https://inspire.ec.europa.eu/codelist/HILUCSValue/1_2_Forestry' that is not one of the allowed values listed at https://inspire.ec.europa.eu/codelist/HILUCSValue.

Wether I set the parent value like in this test or a child value like: 

> https://inspire.ec.europa.eu/codelist/HILUCSValue/1_2_3_ForestryBasedOnContinuousCover

The error is the same saying that its not allowed, what am I not seeing here ?
[TestRunELU.zip](https://github.com/inspire-eu-validation/community/files/5117405/TestRunELU.zip)

**Comment by carlospzurita** [comment]
Dear @apfelnymous 

We have checked your GML file and the cause of the error is that you are referencing the codelist value via HTTPS. However, if you check the URL that appear in https://inspire.ec.europa.eu/codelist/HILUCSValue, you will see that they are listed as HTTP.

In order to pass this test, the value `hilucsLandUse` needs to be set to `http://inspire.ec.europa.eu/codelist/HILUCSValue/1_2_Forestry`

**Comment by apfelnymous** [comment]
@carlospzurita Thank you alot.
