### ISSUE TITLE
NEW ATS/ETS [staging] for Data Specification on Environmental Monitoring Facilities

### ISSUE THREAD

**Issue by arantzaetxebarria** [INSPIRE-MIF/helpdesk-validator#399]
ETS for data theme Data Specification on Environmental Monitoring Facilities (EF) has been deployed on staging, please feel free to test your data against. Any feedback will be much appreciated.

You can find further information for EF data theme and their conformance classes on [ATS ](https://github.com/inspire-eu-validation/data-ef)and [ETS](https://github.com/inspire-eu-validation/ets-repository/tree/data-ef/data-ef)

Thanks for your collaboration

**Comment by iuriemaxim** [comment]
I tested ETS for EF with the following WFS services:

https://inspire-staging.meteoromania.ro/WIGOS/WFS?service=wfs&version=2.0.0&request=GetFeature&typeNames=ef:EnvironmentalMonitoringFacility&count=10

https://inspire-staging.meteoromania.ro/WIGOS/WFS?service=wfs&version=2.0.0&request=GetFeature&typeNames=ef:EnvironmentalMonitoringNetwork

![image](https://user-images.githubusercontent.com/20813598/95173035-d4309100-07c0-11eb-8126-d18da459dbc7.png)

Both typeNames are passing the tests on staging (ex: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID2ccc1a6a-934f-4551-8acd-8046eb10938a.html)

![image](https://user-images.githubusercontent.com/20813598/95166683-01784180-07b7-11eb-9a6d-9f7cab026e86.png)

**ETS for EF can be deployed in production. But some enhancements are still necessary.** 

The only issue that I observed is that if a user will not specify a limited number of Environmental Monitoring Facilities to be tested, by adding "&count=10" or any small number, then the test will run a lot of time due to the specificity of the data theme for the EF:EnvironmentalMonitoringFacility feature type. An enhancement should be done to speed up the test by not testing multiple times the same thing and to allow the user to chose to test all or fewer features (if they are really too many - not this case).

To replicate, the following link should be tested  https://inspire-staging.meteoromania.ro/WIGOS/WFS?service=wfs&version=2.0.0&request=GetFeature&typeNames=ef:EnvironmentalMonitoringFacility

The test is not stopping after a certain number of Environmental Monitoring Facilities features are tested or after a certain time and runs and runs and runs... It should be possible to test all features, but also to test only fewer features, but a better option is to improve the test.  
Results of the test: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/#monitor-test-run?id=EID27a2f88a-16d2-446e-9b7e-a40fa2e7218d

![image](https://user-images.githubusercontent.com/20813598/95167594-9fb8d700-07b8-11eb-984e-759f40222d61.png)
As can be seen in the image above, it is quite strange that the same URL is checked again and again and again in order to see that the link works. As it will be seen below, this is also causing some problems as the INSPIRE Registry is not always responding in due time as so many request are made. More precisely this link is checked 434 times. Considering an average of 3.7 seconds per check, this validation took 434x3.7=1605 seconds, meaning 26 minutes and 44 seconds as can be seen in the image illustrating the error. So from 30 minutes and 15 seconds as it took the entire test the validation of the same URL in the INSPIRE Registry took 26 minutes and 41 seconds. 

**So with a proper designed validation, the same test can be performed in only 3 minutes and 30 seconds, so 10 times faster.**

It is interesting to observe that the requests to the meteoromania.ro (served by WFS trough Nginx short-URL redirects) are taking less than 1 second as can be seen in the image below. So this shows that the INSPIRE Registry is not performing so fast, but still it is not ok to check the same URL so many times within the INSPIRE Registry or within other web services. Once a URL was checked, it should not be checked again and again and again. Also some security services could interpret this as an attack from the same IP and that IP could be automatically blocked due to this behavior.

![image](https://user-images.githubusercontent.com/20813598/95169969-62eedf00-07bc-11eb-84df-41e4d79e8c95.png)

After 30 minutes the test finished and indicated the following errors for some features:

![image](https://user-images.githubusercontent.com/20813598/95231953-89d50180-080c-11eb-9792-691351b40481.png)

Total test time: 30 minutes and 15 seconds
Time to test the same link on INSPIRE Registry: 26 minutes and 41 seconds (90% from the total time spent for the test)

Note also that the text is mentioning that only URLs that are not from INSPIRE Registry should be tested. Note also „codelist” vs ”codeList” (lowercase vs camelCase), both being accepted by the INSPIRE Registry (probably some changes occurred in the Registry). The pseudo-errors are not due to this issue, as all URLs have codeList writen in camelCase and the INSPIRE Registry is supporting both versions, but indeed maybe because codeList is written in camelCase the URL is checked:
http://inspire.ec.europa.eu/codelist/MeasurementRegimeValue/continuousDataCollection
http://inspire.ec.europa.eu/codeList/MeasurementRegimeValue/continuousDataCollection

![image](https://user-images.githubusercontent.com/20813598/95237260-a3784800-0810-11eb-8589-c627a4591019.png)

Here is a print screen from the TG of the EF mentioning camelCase value for the codeList (https://inspire.ec.europa.eu/id/document/tg/ef)

![image](https://user-images.githubusercontent.com/20813598/95239581-cfe19380-0813-11eb-9646-2026ba35f3e3.png)

Potential solution would be not to test URLs that are starting with both 
http://inspire.ec.europa.eu/codelist/ and 
http://inspire.ec.europa.eu/codeList/
or to confirm that there is a typo in the Annex C even if the registry supports both versions.

The errors triggered are fake as the INSPIRE Registry URL http://inspire.ec.europa.eu/codeList/MeasurementRegimeValue/continuousDataCollection
can be retrieved and it was retrieved for the rest of the features.

The errors were most probably triggered due to communication issues between the ETF and the INSPIRE Registry.
An improvement of the test should be made. Once a URL was tested that can be retrieved, it should not be tested again and again. This will led also to minimizing the time for the test. Most probably there are other tests within the EF that should be performed only once and if the input in the test is the same as another one that already passed, should not be tested again, but just should be copied the result from the previous test. Probably the same approach should be used for all data themes in order not to perform the same test for several times. It is quite strange to test several hundreds of time that the same URL can be retrieved or not. It is better to try to retrieve it one time and if it does not respond to try to retrieve it second or third time, but once it was clear that the URL can be retrieved or cannot be retrieved is useless to test the same URL again and again for each feature element.

I would appreciate your feedback.

**Comment by iuriemaxim** [comment]
@carlospzurita I made some updates to the previous post, to illustrate that the time spend to validate the same URL in the INSPIRE Registry takes 90% from the total validation process.

**Comment by iuriemaxim** [comment]
Following the conclusion from issue https://github.com/inspire-eu-validation/community/issues/407 and changing the URLs of the INSPIRE Registry from
http://inspire.ec.europa.eu/codeList/MeasurementRegimeValue/continuousDataCollection (codeList camelCase)
into
http://inspire.ec.europa.eu/codelist/MeasurementRegimeValue/continuousDataCollection (codelist lowercase)

The test of all features from ef:EnvironmentalMonitoringFacilities 

https://inspire-staging.meteoromania.ro/WIGOS/WFS?service=wfs&version=2.0.0&request=GetFeature&typeNames=ef:EnvironmentalMonitoringFacility

is not spending anymore 26+ minutes for testing the URLs in the INSPIRE Registry and the entire test takes 3 minutes and 35 seconds. 

![image](https://user-images.githubusercontent.com/20813598/95365566-ffa79e80-08da-11eb-877f-1ef07173ef37.png)

To compare: 
26' 44 seconds for 434 INSPIRE Registry URLs (3.7 second/URL)
  3' 31 seconds for 1449 URLs from various sites. (0.14 seconds/URL)

This indicates that the INSPIRE Registry is quite slow,

**The suggestion to improve the algorithm in the validator still exist as many URLs are checked multiple times**

Below some examples of URLs that are verified multiple times (the number in front indicates how many times those URLs were checked).

46 | https://inspire.meteoromania.ro/observedProperty/BUFR0-13-023
23 | https://inspire.meteoromania.ro/observedProperty/BUFR0-11-001SF32PT10M
23 | https://inspire.meteoromania.ro/observedProperty/BUFR0-11-002SF32PT10M
23 | https://inspire.meteoromania.ro/observedProperty/BUFR0-12-023
23 | https://inspire.meteoromania.ro/observedProperty/BUFR0-12-023SF2PT24H
23 | https://inspire.meteoromania.ro/observedProperty/BUFR0-12-023SF3PT24H
23 | https://inspire.meteoromania.ro/observedProperty/BUFR0-12-023SF4PT24H
23 | https://inspire.meteoromania.ro/observedProperty/BUFR0-13-003
23 | https://inspire.meteoromania.ro/process/DailyAverageAirTemperatureFrom4Values
23 | https://inspire.meteoromania.ro/process/DailyMaximumAirTemperatureFrom4Values
23 | https://inspire.meteoromania.ro/process/DailyMinimumAirTemperatureFrom4Values
23 | https://inspire.meteoromania.ro/process/RelativeHumidity
23 | https://inspire.meteoromania.ro/process/Temperature
23 | https://inspire.meteoromania.ro/process/TotalPrecipitations24HoursFrom0530UTC
23 | https://inspire.meteoromania.ro/process/TotalPrecipitations24HoursFrom1730UTC
23 | https://inspire.meteoromania.ro/process/WindDirection
23 | https://inspire.meteoromania.ro/process/WindSpeed
9 | https://inspire.meteoromania.ro/ids/EnvironmentalMonitoringFacility.15015
9 | https://inspire.meteoromania.ro/ids/EnvironmentalMonitoringFacility.15020
9 | https://inspire.meteoromania.ro/ids/EnvironmentalMonitoringFacility.15090
9 | https://inspire.meteoromania.ro/ids/EnvironmentalMonitoringFacility.15108

Taking in consideration the specifics of EF data theme it is critical not to verify the same URL more than one time.
For a full implementation with many EnvironmentalMonitoringFacilities that will monitor multiple parameters (observed properties) based on multiple processes, the numbers will raise to hundreds instead of tens as it is now, so it will become critical to check a URL only once and not again, again and again.

Also for services that are not optimized, looking at the EU INSPIRE Registry response time, the validation of the URLs will take most probably hours if the URLs will not be checked only once.

Below can be found the list of URLs that are checked in order to see how many they are just for 23 monitoring stations that provides only 17 observed properties.

[CheckedURLs.txt](https://github.com/inspire-eu-validation/community/files/5342832/CheckedURLs.txt)

**By looking in the test log, I see that the URL for the EPSG code, namely**

 **http://www.opengis.net/def/crs/EPSG/0/4258 is checked only once, even if it appears many, many times.**

07.10.2020 17:18:34 - "Checking URL: 'http://www.opengis.net/def/crs/EPSG/0/4258'"

**So a similar approach as for EPSG URLs should be used for all URLs, in order to check them only once.**

**So, the ETF is fine, can go to production, but should be optimized in order not to check the same URL several times.**

Below can be found entire test log:

[TestLog.txt](https://github.com/inspire-eu-validation/community/files/5342898/TestLog.txt)
