### ISSUE TITLE
Failure to pass Quality of Service criteria in Metadata, Conformance Class 6: INSPIRE interoperable SDS.

### ISSUE THREAD

**Issue by HanWelmer** [INSPIRE-MIF/helpdesk-validator#420]
Validation of the attached harmonised download service metadata fails with the following message:

The metadata record set has 1 record(s) with errors for this assertion.

            XML document 'Olie- en gasvelden DOWNLOAD onder INSPIRE - Copy.xml', record 'fa3ecd49-4571-4eb3-84f3-2865f42934b2': The minimum values for each of the Quality of Service criteria fon interoperable services shall be given in the metadata. They shall be encoded using one gmd:report/gmd:DQ_ConceptualConsistency element within the gmd:DQ_DataQuality element scoped for the entire service.

            XML document 'Olie- en gasvelden DOWNLOAD onder INSPIRE - Copy.xml', record 'fa3ecd49-4571-4eb3-84f3-2865f42934b2': The minimum values for each of the Quality of Service criteria fon interoperable services shall be given in the metadata. They shall be encoded using one gmd:report/gmd:DQ_ConceptualConsistency element within the gmd:DQ_DataQuality element scoped for the entire service.

Replacing the three data quality criteria with 3 times the performance criterium 'performance' gives all green results (which is obviously a false positive).

Selected test suites where:
Metadata (TG version 2.0)
Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records.
Conformance Class 3: INSPIRE Spatial Data Services baseline metadata.
Conformance Class 5: INSPIRE Invocable Spatial Data Services metadata.
Conformance Class 6: INSPIRE interoperable Spatial Data Services metadata.
Conformance Class 7: INSPIRE Harmonised Spatial Data Services metadata.

If necessary, please contact me at: han.welmer@tno.nl
[Olie- en gasvelden VIEW onder INSPIRE.zip](https://github.com/inspire-eu-validation/community/files/5382891/Olie-.en.gasvelden.VIEW.onder.INSPIRE.zip)

**Comment by carlospzurita** [comment]
Dear @HanWelmer 

We are checking the Test Reports for your metadata on the staging isntance, and checking the TG for Metadata 2.0. We will get back to you whenever we have any news on this.

**Comment by carlospzurita** [comment]
Dear @HanWelmer 

We are not able to locate your issue withing the attached metadata. The actual error that we are getting from out testing is the following

![imagen](https://user-images.githubusercontent.com/10537778/97169180-ea12ef80-1789-11eb-80fe-a969b4f0b3fb.png)


Can you please check that the attached metadata is indeed the one related to your issue?

**Comment by fabiovin** [comment]
Dear @HanWelmer,
it seems that your metadata refers to a WMS, so, it is a "Network Service" and not a "Harmonised Spatial Data Services".
In this case, the right conformance class is "Conformance Class 4: 'INSPIRE Network Services metadata'".

Indeed your metadata passes the validation against this one: https://inspire.ec.europa.eu/validator/v2/TestRuns/EID27a0bf9c-5b87-4b15-b06c-67fa12350827.html

Regards,
Fabio

**Comment by HanWelmer** [comment]
My apologies. I accidentally attached the pruned version, so they would pass conformance class 4 instead of 5,6,7. Attached you will find two files. The one postfixed with PPP containts 3 times a 'perfomance' QoS criterium and passes. The file with postfix ACP contains 'availability, capacity and performance' QoS criteria and fails.

[Olie- en gasvelden onder INSPIRE, download.zip](https://github.com/inspire-eu-validation/community/files/5440028/Olie-.en.gasvelden.onder.INSPIRE.download.zip)

**Comment by carlospzurita** [comment]
Dear @HanWelmer 

We had a look to the new metadata that you sent. In the case of the PPP file, even if this is not a realistic scenario to put three times the same value, there is no automatic check on that aspect as stated on the [ATS](https://github.com/inspire-eu-validation/metadata/blob/2.0/sds-interoperable/quality-of-service.md)

For the other file, you can find that there is a couple of errors on your capacity anchor

![imagen](https://user-images.githubusercontent.com/10537778/97280496-a3ca9880-183c-11eb-9fc7-fcccc14da6ca.png)

One is on the `href` attribute, that is pointing to performance instead of capacity. The other one is on the `valueUnit` URI, that should be modified to http://www.opengis.net/def/uom/OGC/1.0/unity . You can check this modifications with Table 4.2 on [metadata 2.0 TG](https://inspire.ec.europa.eu/sites/default/files/documents/metadata/inspire-tg-metadata-iso19139-2.0.1.pdf)

![imagen](https://user-images.githubusercontent.com/10537778/97282119-931b2200-183e-11eb-9793-ce6465fa7fc8.png)


Fixing this makes the Metadata pass the Data Quality checks on Conformance Class 6.

**Comment by HanWelmer** [comment]
Thanks a lot for your help.
