### ISSUE TITLE
Geometry Validation Errors Reported for Correct Geometry

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#421]
We are receiving invalid geometry validation errors for tests involving the AU, HY, and TN themes.

Examples of reported errors:

- XML document 'service.xml', AdministrativeBoundary 'auAdmBoundaryL.1727': The feature does not correspond to an edge in the topological structure formed by the complete boundary graph of all AdministrativeUnit features. It is not on the boundary of any AdministrativeUnit in the dataset.

- XML document 'service.xml', HydroNode 'netElementP.300501': The node is not located at the start or end of any link feature in the data set.

- XML document 'service.xml', DesignatedPoint 'netElementP.300209': The node is not located at the start or end of any link feature in the data set.

I've attached a zip file containing a more detailed explanation of the errors and the viewed correct geometry and the .xml files from the tests.

Thanks for any help that can be provided.
[GeometryValidationErros.zip](https://github.com/inspire-eu-validation/community/files/5386385/GeometryValidationErros.zip)

**Comment by carlospzurita** [comment]
Dear @robblis 

Thank you for your very comprehensive material collected from your errors. We are going to check the TestReports in our staging instance and review the geometries, to locate any error on the ETS that may be present.

**Comment by fabiovin** [comment]
Dear @robblis ,
sorry for the late reply. 

I had a look at your datasets and I tried to validate those related to the AU theme.

For the _AdminBoundaryL_1727_ dataset it seems that the links to the related administrative units don’t work. 
```
<au:admUnit
                xlink:href="http://agsinspire1.esri.com/arcgis/rest/services/AUTest/MapServer/exts/InspireFeatureDownload/service?SERVICE=WFS&amp;VERSION=2.0.0&amp;REQUEST=GetFeature&amp;STOREDQUERY_ID=urn:ogc:def:query:OGC-WFS::GetFeatureById&amp;id=auAdmUnitS.110616"/>
            <au:admUnit
                xlink:href="http://agsinspire1.esri.com/arcgis/rest/services/AUTest/MapServer/exts/InspireFeatureDownload/service?SERVICE=WFS&amp;VERSION=2.0.0&amp;REQUEST=GetFeature&amp;STOREDQUERY_ID=urn:ogc:def:query:OGC-WFS::GetFeatureById&amp;id=auAdmUnitS.121206"
            />
```
Could you please verify?

For the _AdminUnitS_110616 dataset_, I wasn’t able to upload it on the validator, I think the reason is that it isn’t instantiated in a gml:FeatureCollection.
Could you please check if it the right file?

Regards,
Fabio

**Comment by robblis** [comment]
Hi @fabiovin,

Sorry for the delay on this. 

So the service for this issue was stopped. I started the service again and you are welcome to test against it. 

The urls are the following:

http://agsinspire1.esri.com/arcgis/rest/services/AUTest/MapServer/exts/InspireFeatureDownload/service?REQUEST=GetFeature&SERVICE=WFS&VERSION=2.0.0&TYPENAMES=au%3AAdministrativeBoundary&COUNT=10&namespaces=xmlns(au,http://inspire.ec.europa.eu/schemas/au/4.0)

http://agsinspire1.esri.com/arcgis/rest/services/AUTest/MapServer/exts/InspireFeatureDownload/service?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&STOREDQUERY_ID=urn:ogc:def:query:OGC-WFS::GetFeatureById&id=auAdmUnitS.110616

http://agsinspire1.esri.com/arcgis/rest/services/AUTest/MapServer/exts/InspireFeatureDownload/service?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&STOREDQUERY_ID=urn:ogc:def:query:OGC-WFS::GetFeatureById&id=auAdmUnitS.121206

Please let me know if you have any other questions.

Thanks,
Robert

**Comment by robblis** [comment]
Hi @fabiovin 

Just want to check if you still need to test this, so I know to keep the service online.

Thanks,
Robert

**Comment by fabiovin** [comment]
Dear @robblis,

your AU datasets still have the error "_au-dc.f.1: The geometry of each instance administrative boundary corresponds to an edge in the topological structure formed by the complete boundary graph, including the boundaries of all levels._" because the validator cannot verify the consistency between AdministrativeBoundary and AdministrativeUnit.

I would suggest creating a unique dataset containing both feature types.
In this way, the reference between the two feature types could be encoded using an "internal" link.

Example:

- For the _AdministrativeBoundary_ feature type: `<au:admUnit xlink:href="#auAdmUnitS.110616"/>`
- For the _AdministrativeUnit_ feature type: `<au:boundary xlink:href="#auAdmBoundaryL.1727"/>`

**Comment by dperezBM** [comment]
Dear all,

Since this issue had no interaction time ago, we decided to close it. Please feel free to open a new one if needed.

Thank you and best regards.

**Comment by robblis** [comment]
Hi @dperezBM,

We are still looking into this. We will open a new case when we are ready.

Thanks,
Robert
