### ISSUE TITLE
WMS executed tests are not found in the list of tests executed by the validator

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#422]
While executing three WMS tests in the production environment in the last hour, and looking for its log, I found that none of them is found in the list of the tests that is accessible at: https://inspire.ec.europa.eu/validator/#test-reports
Most probably can be tested with any WMS.

**Comment by carlospzurita** [comment]
Dear @iuriemaxim 

We have been experiencing some problems with the test reports sorting by date, and with the volume of validations that we are getting, most recent test reports are disappearing. We are looking into this and get back to you with any news.

Sorry about the inconveniences.

**Comment by ghost** [comment]
Dear @carlospzurita ,

I have experienced the same problem. 

Could you also please answer following questions:
1. What is maximal number of reports which can displayed in "Test reports" section in INSPIRE Validator?
2. Does the deletion of one test report in "Test reports" section automatically means that report can't be accesed anymore if one has correct URL to the report?

I assume these questions are also relevant for those who are deploying their own validator and that system requirements don't play any role for those two actions.

Thanks in advance!

**Comment by carlospzurita** [comment]
Dear @DeordD and @iuriemaxim 

To try to give closure on this issue, the status of the TestReports section is the following. The Test Reports that you get on the interface is extracted using the API call. This request returns the results paginated by 1500 results. However, this results are not being ordered, and when we got more than 1500 TestReports, is not ensured that the latest TestRun executed would show up on this page.

Also, answering the second question from @DeordD , deleting a TestReports makes it no longer accessible through the URL.

To overcome this issue, the new UI developed by the JRC is applying an ordering on the results before rendering them, so it may be partially solved. For now, is not foreseen to modfy the API call to order the results by date.

I hope this summarize everything clearly for you.

**Comment by iuriemaxim** [comment]
@carlospzurita
Ok, 
So the interface could be auto-restarted/reset when it is approaching the 1500 tests limit? (I suppose that counting the number of the tests is possible),

**Comment by ghost** [comment]
@carlospzurita 
Thanks for answering giving first insights concerning question nr. 1 from  https://github.com/inspire-eu-validation/community/issues/422#issuecomment-712758967

Concerning question 1:
Did I understand correctly that a maximal number of reports which can displayed in "Test reports" section in current INSPIRE Validator is 1500? 

Concerning your feedback to question nr. 2:
Does it mean that the reports which can't be seen in the reports section because of sorting issue (after 1500 records) still can be accessed if one has saved an URL to HTML report? 

Thanks a lot for the help.

**Comment by iuriemaxim** [comment]
@DeordD From what I experienced, yes you can access the report if you saved the link. But you cannot access of the features that are available in the "Test report" interface. For example you cant access the log file and you cant run the test again.

**Comment by iuriemaxim** [comment]
@carlospzurita I see this issue as being marked as ready for testing. Can you please specify what can I test? I think better is to put another label, such as „Will be partially fixed by the New UI”.

**Comment by carlospzurita** [comment]
We marked this issue as ready for testing given that it was partially solved on the new interface. However, the testing instance is no longer available publicly.

For the new release we are still keeping the current interface. In order to keep this issue somewhat under control, we are going to reduce the time tests are being kept on the reference validator, going down to 3 days. This way the Test Reports page will have to show less results and you would be able to find the newest tests.

We are marking this as solved to deploy this solution on the production instance, even though is a compromise solution for now.
