### ISSUE TITLE
View Service WMS: Fees element is mandatory when external service metadata is provided

### ISSUE THREAD

**Issue by thijsbrentjens** [INSPIRE-MIF/helpdesk-validator#43]
See the ATS: https://github.com/inspire-eu-validation/view-service/blob/master/iso-19128/fees-node.md

https://github.com/inspire-eu-validation/view-service/blob/review-ats-tg_3.11/iso-19128/at24-getcapabilities-fees-node.md

The Fees element should only be checked when scenario 1 is used. This implementation implements scenario 2 (service metadata in external document): http://www.broinspireservices.nl/wms/osgegmw-a-v1.0?&request=GetCapabilities&service=WMS

- [x] a description of the steps to reproduce your issue
1. run the View Service - WMS test from http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/
1. enter URL: http://www.broinspireservices.nl/wms/osgegmw-a-v1.0?&request=GetCapabilities&service=WMS 
1. see report for at24-getcapabilities-fees-node

- [1] the name of the Test that failed or better: change the `Level of Detail`
in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI`

- [x] the URL of your service / the file you have uploaded or referenced (as
an attachment). http://www.broinspireservices.nl/wms/osgegmw-a-v1.0?&request=GetCapabilities&service=WMS

**Comment by alitka** [comment]
According to the Technical Guidance for the implementation of INSPIRE View Services (version 3.11; 2013-04-04) Requirement 10: 

An INSPIRE View service shall contain the INSPIRE metadata elements set out in the Metadata Regulation [INSMD] as shown in Table 3.

Table 3: Mapping between INSPIRE metadata elements and [ISO 19128] WMS elements

INSPIRE Metadata elements (Mandatory - Conditional) | ISO 19128 elements of<WMS_Capabilities>
------------ | -------------
... | ...
Conditions for Access and Use (M) | wms:Fees
Limitations on Public Access (M) | wms:AccessConstraints

I think, it's not correct to skip the test for the scenario 2 - service metadata in external document.

**Comment by MarcoMinghini** [comment]
There is some confusion in the TG in referring to the two scenarios. In our understanding:

- **scenario 1**: metadata is provided through a reference (using an `<inspire_common:MetadataURL>` element) to an online INSPIRE metadata resource in the extended capability
- **scenario 2**: metadata is provided including all INSPIRE metadata elements mapped to the [ISO 19128] – WMS1.3.0 elements and the extended capability elements.

Therefore, the scenario used by @thijsbrentjens is scenario 1.

To our understanding, @thijsbrentjens is right: the Fees element should not be checked since we are in scenario 1. In this case, the ATS is correct (the test should be only done in scenario 2), but the test is not correctly implemented in the ETS.

**Comment by fabiovin** [comment]
I fully agree with this interpretation of the two scenarios.

Regarding the TG requirements, there is probably confusion between the requirements that apply only to scenario 1 or 2 and those that apply to both.

I think this should be the mapping:
- Scenario 1: Requirement 6 - 8 - 9
- Scenario 2: Requirement 7 - 8 - 9 - 10 to 29

Figure 5 (Technical Guidance for the implementation of INSPIRE View Services - version 3.11) clearly explains the differences between the metadata elements in the two scenarios.

**Comment by MarcoMinghini** [comment]
**2017.4 meeting 2019-05-22**

- @thijsbrentjens is correct that the Fees element should not be checked since we are in scenario 1.

- Although the ATS is correct, the [ETS ](https://github.com/inspire-eu-validation/ets-repository/blob/wms-tg-3.11/service/vs-wms-soapui-project.xml) ﻿﻿seems to be wrong, because it starts from the hypothesis of scenario 1 and, if at least one element among those listed is found, assumes we are in scenario 2 (see lines 57-70). Conversely, the ETS should assume to be in scenario 2 and check whether there is an <inspire_common:MetadataURL> element: if yes, then we are in scenario 1.

- it is agreed to change the test accordingly.

**Comment by josemasensio** [comment]
Dear @thijsbrentjens,

We are happy to announce that the solution for this issue has been implemented in the INSPIRE Validator. The solution passed our quality controls, but we will appreciate if you could test it and give us some feedback. You can test the solution in the staging environment:

http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/

Thanks in advance for your help.

**Comment by thijsbrentjens** [comment]
Thanks, I re-tested, it is fixed in the staging environment. So if it is up to me, you could close this issue as soon as it is deployed in production.

**Comment by MarcoMinghini** [comment]
Dear @thijsbrentjens, thank you. Yes, when it is also deployed in production we will close the issue.
