### ISSUE TITLE
New UI of the INSPIRE Reference Validator - feedback

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#443]
Herewith a feedback concerning new UI of the validator (according to the call in #417):

Browser: Firefox 78.4.1esr (64-Bit)

# Positives
1. Integration of GitHub HelpDesk in the UI (Get suport, More on the INSPIRE validator): This should help the users which are not familiar with GitHub to communicate the problems in validator 
2. Configure your test section will help newcomer to validate INSPIRE resources without knowing the conformance class architecture in detail
3. Filter capabilities have been improved compared to old validator, especially the facets are useful to reduce the amount of the reports. 

# Negatives
1. Multilinguality: In the current validator some UI elements are provided per default in other languages than English, for example in German. In the new validator this is not the case and UI elements are not translated. 
2. Test reports section: 
   - Reports section takes significant amount of time to be loaded. Web browser freezes if the amount of reports is too high
   - Items in dropdown menu by clicking on "Sort by Date" can't be distinguished between each other. It is also not clear which sorting is currently active
![grafik](https://user-images.githubusercontent.com/38787131/98967341-a8fe3780-250c-11eb-8a09-c89c47b14440.png)
   - Refine tests/Clear all: After the click on one of the buttons there is no indication that some process is running. In case that 10000 reports can be provided in this section user could think that nothing happens and refresh the page.
   - Filter options: 
      - Individual conformance classes can't be searched, one example is "Conformance class 2b"
![grafik](https://user-images.githubusercontent.com/38787131/98972222-72c3b680-2512-11eb-9185-2b34b5106328.png)
      - Test reports with exact search term can't be found, one example is "Testclass"
![grafik](https://user-images.githubusercontent.com/38787131/98972880-57a57680-2513-11eb-82b0-b9680b2e008d.png)
3. Metadata TG 2.0 tests: If one like to validate the requirements for INSPIRE Monitoring "Simple options" won't be sufficient. One has to change to Advanced option and check "Conformance Class 2b: 'INSPIRE data sets and data set series metadata for Monitoring'". In that case I would expect that Conformance Class 2 is unchecked, which is standard behaviour in the current validator. That basically means that unexperienced user still have to use the "Advanced options"
![grafik](https://user-images.githubusercontent.com/38787131/98970380-2a0afe00-2510-11eb-8daa-469cce2935fe.png)

# Questions:
1. For which web browsers is the new UI optimzed and in which version?
2. In case that some organization has it own profile what has to be done to integrate custom conformance classes in the UI? Can UI be influenced using the TagEIDs like in the old validator? (see the list of known ETF instances https://github.com/inspire-eu-validation/community/issues/162)
3. Is there a option to configure for neutral UI by choosing some predefined UI templates in the INSPIRE validator backend? (INSPIRE and standard)
4. If I understood well API and backend is exact the same like the etf-core. Will INSPIRE validator also in the future be synchronised with the core? If one decides to use etf core instead of the INSPIRE validator because UI is very hardly customizable can user expect **exactly** the same validation results (API and UI usage) like in INSPIRE validator?

Kind regards,
Dejan

**Comment by MarcoMinghini** [comment]
Dear @DeordD,
as you might have already noticed, the new UI has been recently included in the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) of the INSPIRE Reference Validator. Starting with the next release scheduled for mid-June (see the release plan [here](https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/release%20strategy)), the new UI will be also included in the [production instance](https://inspire.ec.europa.eu/validator/).

On behalf of the INSPIRE validation team, I would like to thank you for testing the new UI and providing us with useful feedback and suggestions. As you can see, your comments were highly considered to improve the UI.

Please find below the replies to your questions:

> Multilinguality: In the current validator some UI elements are provided per default in other languages than English, for example in German. In the new validator this is not the case and UI elements are not translated.

As you can see, the new UI is completely different than the old one, and no automatic translations are foreseen. We may plan to add translations in other languages in the future, in case the community is available to help provide them.

> For which web browsers is the new UI optimized and in which version?

The UI was developed using the latest [Europa Component Library v2 framework](https://ec.europa.eu/component-library/ec/) (with Angular) and is responsive on PC & mobile browsers. The development phase was executed using Chrome v90, Firefox v88 and Safari for MacOS. It was not tested with Explorer / Edge.

> In case that some organization has it own profile what has to be done to integrate custom conformance classes in the UI? Can UI be influenced using the TagEIDs like in the old validator? (see the list of known ETF instances https://github.com/inspire-eu-validation/community/issues/162)

Unfortunately, for the time being it is not that easy to insert new custom conformance classes. In the future, and depending on the need for this functionality, we may modify the current structure to make it configurable without having to make changes at the code level, but for the time being the only way to add new custom conformance classes is to intervene in the code and in the views.

> Is there an option to configure for neutral UI by choosing some predefined UI templates in the INSPIRE validator backend? (INSPIRE and standard)

Right now there is no option for alternative UIs on the backend, that is, the ETF. There is only the ETF default interface (the one currently available in production), and any other UI should be developed in the same manner as the INSPIRE one, relying on the ETF API. Starting with the next release in June, the INSPIRE UI will be integrated in the Reference Validator.

> If I understood well API and backend is exact the same like the etf-core. Will INSPIRE validator also in the future be synchronised with the core? If one decides to use etf core instead of the INSPIRE validator because UI is very hardly customizable can user expect exactly the same validation results (API and UI usage) like in INSPIRE validator?

The validation results and options available in the UI for the Executable Test Suites will be the same, as the source code loaded for the ETS is the same and the UI only acts as messenger to the backend. Currently there are only some differences: the INSPIRE Reference Validator support for the ETS for services (but this will be included in the upcoming release of the ETF), and some minor modifications that are purely on the performance (file size, queue size, etc.) or informative side (header and footer, log information, etc.).

Please let us know if you have additional feedback on any of these points, otherwise we propose to close this issue and open new ones in the future in case this will be needed.

**Comment by ghost** [comment]
Dear @MarcoMinghini,

I can confirm that all Negatives except "Multilinguality" can't be reproduced on the staging instance anymore. Thanks a lot for considering our feedback. 

Concernig your very detailed answers to my questions: 
Background of my questions was to discuss how INSPIRE-Validator with the new UI can be used as a tool for validating custom and INSPIRE conformance classes at the same time and have the same results like in INSPIRE Validator:
1. validation via UI for stakeholders
2. bulk validation using API

First option: Our current idea is to offer the possibility to validate against our metadata profile in GDI-DE Testsuite which is using INSPIRE-Validator in the backend setup. This means that there will be no need to address the points from your answer.

Second option: This is very good news, since we don't have to change our routines based on API for bulk validation and can have the correct results.

In my opinion this issue can be closed.

**Comment by MarcoMinghini** [comment]
Dear @DeordD, thanks for your comments. Feel free to open new issues if you see a need.
