### ISSUE TITLE
Bulk upload to ETF Validator

### ISSUE THREAD

**Issue by bcosyn** [INSPIRE-MIF/helpdesk-validator#457]
Is there a description on how a bulk upload should look like? If I upload an geonetwork bulk file export (.zip) it works. But in geonetwork there is the issue that during export all related records are also in the zip file. So I wrote my own procedure to only export datasets without the related services. But that upload fails. The zip file is a flat file with only xml metadatarecords. Is there any description on how this upload zip file should look like?
[result3290.zip](https://github.com/inspire-eu-validation/community/files/5592028/result3290.zip)

**Comment by ghost** [comment]
Hi @bcosyn

regarding the "problem" with the download of related-records in Geonetwork (tested in 3.10.3) there are two possibility how to export them without further customizing of Geonetwork:

1. mef.export by setting relation=false: https://github.com/geonetwork/core-geonetwork/issues/4065#issuecomment-535900908
2. directly in UI: https://github.com/geonetwork/core-geonetwork/issues/4065#issuecomment-653597128

I had the same problem. Hopefully this still can help you.

Kind regards,
Dejan

**Comment by carlospzurita** [comment]
Dear @bcosyn 
The zip file is being rejected not because of the file structure, but because of the content on each XML. It seems that the file contain an invisible character 0xFF that can't be encoded on UTF-8. Trying to validate the file with online tools or opening it with a Python script throws this error. 

You should check the encoding that you are employing in the procedure to generate the files. The structure of the ZIP file is correct as it is, and you don't need to change it in principle.

**Comment by bcosyn** [comment]
> Dear @bcosyn
> The zip file is being rejected not because of the file structure, but because of the content on each XML. It seems that the file contain an invisible character 0xFF that can't be encoded on UTF-8. Trying to validate the file with online tools or opening it with a Python script throws this error.
> 
> You should check the encoding that you are employing in the procedure to generate the files. The structure of the ZIP file is correct as it is, and you don't need to change it in principle.

Thx. Indeed the BOM. Ticket will be closed
