### ISSUE TITLE
Land Cover Vector - Not Recognizing Surface Geometry Type

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#458]
Hi Validator Team,

When running the Land Cover Vector test, we are seeing an error with the Conformance class: Application schema, Land Cover Vector test.

The error is happening under Constraints > LandCoverUnit geometry.

We're seeing the following two errors...

XML document 'service.xml', LandCoverUnit 'lcvLandCoverUnitS.4': The constraint 'The geometries of the LandCoverUnit feature types are points or surfaces' is violated. 
XML document 'service.xml', LandCoverUnit 'lcvLandCoverUnitS.9': The constraint 'The geometries of the LandCoverUnit feature types are points or surfaces' is violated. 

We're not exactly sure what this is looking for regarding the surface geometry. We have the following returned geometry nodes in the xml.
			<lcv:geometry>
				<gml:Polygon gml:id="lcvLandCoverUnitS.unitid.4.shape.Geom_0" srsName="http://www.opengis.net/def/crs/EPSG/0/4258" srsDimension="2">
					<gml:exterior>
						<gml:LinearRing>
							<gml:posList>46.558500818000 6.794617301000 46.286064795000 7.710798154000 45.943604845000 6.830545962000 46.558500818000 6.794617301000</gml:posList>
						</gml:LinearRing>
					</gml:exterior>
				</gml:Polygon>
			</lcv:geometry>

			<lcv:geometry>
				<gml:Polygon gml:id="lcvLandCoverUnitS.unitid.9.shape.Geom_0" srsName="http://www.opengis.net/def/crs/EPSG/0/4258" srsDimension="2">
					<gml:exterior>
						<gml:LinearRing>
							<gml:posList>45.868603464000 9.938375131000 45.918615644000 11.204860428000 45.233325326000 11.222824758000 45.226999541000 9.947357296000 45.868603464000 9.938375131000</gml:posList>
						</gml:LinearRing>
					</gml:exterior>
				</gml:Polygon>
			</lcv:geometry>

We've attached the complete returned XML for this test.

Thank you for your help.
 
[LC_LandCoverUnit.zip](https://github.com/inspire-eu-validation/community/files/5592172/LC_LandCoverUnit.zip)

**Comment by carlospzurita** [comment]
Dear @robblis 

The constraints here express that these geometries should be declared as `gml:Surface` or `gml:Point` (or any sub-type of those). In this case, `gml:Polygon` would not pass the constraint, as it is not a sub-type of `gml:Surface`. You can check it on the [geometry primitives xsd](http://schemas.opengis.net/gml/3.2.1/geometryPrimitives.xsd).

**Comment by robblis** [comment]
Hi @carlospzurita ,

Thank you for the clarification. We will work on getting this fixed.

Robert

**Comment by robblis** [comment]
Hi @carlospzurita,

After discussing this issue, we need to open this case again to get some direction.

It's our understanding both gml:Surface and gml:Polygon are derived from gml:AbstractSurface and should therefore fulfill the constraint. A Polygon is just a specific simple type of Surface.

See also the documentation in http://schemas.opengis.net/gml/3.2.1/geometryBasic2d.xsd [schemas.opengis.net]:

A Polygon is a special surface that is defined by a single surface patch (see D.3.6). The boundary of this patch is coplanar and the polygon uses planar interpolation in its interior. The elements exterior and interior describe the surface boundary of the polygon.

Can you re-asses this particular issue?

Thanks,
Robert

**Comment by robblis** [comment]
Hi @fabiovin ,

Can you clarify the state of this issue? 

I see that it has been marked "user-to-fix". Was the additional information we posted reviewed?

Thanks for any clarification,
Robert

**Comment by fabiovin** [comment]
Dear @robblis,

sorry for the late reply.

The gml:Polygon is an additional subtype of GM_Surface added in GML specification, but is not included in ISO 19107 referenced by INSPIRE.

Please have a look at section 5.5.1.2.1. of the TG, whose note clarifies this aspect:
![image](https://user-images.githubusercontent.com/46569952/112844769-66489080-90a4-11eb-8cc5-74f7ae65b59e.png)
![image](https://user-images.githubusercontent.com/46569952/112845749-80cf3980-90a5-11eb-868a-8d3b69ed4f4b.png)

**Comment by cportele** [comment]
The test is more restrictive than the requirements in the technical guidance (unless there is another constraint stated somewhere else, but that is not referenced from the abstract test case). The relevant facts are:

* The technical guidance restricts the geometries to GM_Surface or GM_Point as pointed out above.
* gml:Polygon is an XML implementation of the ISO 19107:2003 GM_Surface as pointed out in the comment above and in GML 3.2. See D.3.6 ("An additional subtype of GM_Surface is added in GML. 'Polygon' is a special surface that consists of a single GM_Polygon patch. Since only a single patch exists, the XML representation of the 'Polygon' object element skips the patch level and the exterior and interior boundary properties of the patch are represented as direct properties of the 'Polygon'.").
* Neither D2.7 or the Technical Guidance specifies a profile of GML that restricts the use of GML 3.2 geometry elements.

It is, therefore, valid to use gml:Polygon as the geometry of a LandCoverUnit. 

In practice that also makes sense, because gml:Polygon is a straight representation of a GM_Surface consisting of a single patch, which most surfaces are, also because in many cases the server implementation uses Simple Features at the backend, where surface geometries have the same constraint. This also simplifies the use of such GML in clients that use a Simple-Feature-based geometry model internally (which is often the case), because the geometry is guaranteed to be compatible with that model.

Note that other GML 3.2 geometry elements in the gml:Surface substitution group (e.g. gml:PolyhedralSurface) would also be valid, but are excluded by the current abstract test case. If that is not desired, then the Technical Guidance documents should be updated first, but the tests should not throw errors, if these are used.

_Edited to add: The previous comment stated that the NOTE in the technical guidance states that gml:Polygon cannot be used. This is not correct. The NOTE states that GM_Polygon cannot be used (which is implemented in GML by gml:PolygonPatch and its use would throw an error when XSD validation is used)._

**Comment by fabiovin** [comment]
Dear @cportele,

thank you for your clarification.

We will modify the test to accept gml:Polygon.

In addition, it seems that the other geometry elements in the gml:Surface substitution group are: gml:PolyhedralSurface and gml:TriangulatedSurface.
Is it right or there are other elements?

**Comment by cportele** [comment]
@fabiovin 

> In addition, it seems that the other geometry elements in the gml:Surface substitution group are: gml:PolyhedralSurface and gml:TriangulatedSurface. Is it right or there are other elements?

Yes, that is correct, I just checked the schema.

**Comment by robblis** [comment]
Hi @fabiovin,

Just an additional note, this issue is also occurring when testing the Building theme in the following test.

Conformance Class 'Application Schema, Buildings'
Constraints
Check that the geometry is of type GM_Point or GM_Surface or GM_MultiSurface.

I've attached the test report and the service XML.

Thanks, 
Robert
[BuildingTestArtifacts.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6280021/BuildingTestArtifacts.zip)

**Comment by fabiovin** [comment]
Dear @carlospzurita,

I updated the ATSs related to the two data themes involved, LC and BU.

Now, the XPaths of the "Constraints" tests are updated with all types of geometry allowed.

Could you please update the related ETSs?

Thanks,
Fabio

**Comment by dperezBM** [comment]
Dear @robblis,

Thank you for your feedback. We updated the ETS and added the fix to our [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Please, could you give us feedback once you tried this? 

Thank you and best regards.

**Comment by robblis** [comment]
Hi @dperezBM ,

I've re-ran the LC test. The test passed the geometry constraint test.

I also tested the BU Building theme and it passed the constraint test too.

Thanks for the fix.

Robert

**Comment by dperezBM** [comment]
Dear @robblis,

Thank you for your feedback. We are glad that the solution worked for you. However, we will keep the issue open until it goes into production.

Best regards.
