### ISSUE TITLE
production instance down?

### ISSUE THREAD

**Issue by tilmanb** [INSPIRE-MIF/helpdesk-validator#464]
When submitting a test with a remote URL in the production instance I get an empty test result as result where no tests have been run.

How to reproduce:
Choose metadata 2.0 tests (i chose common, 1 and 2b)
Use remote URL https://nibis.lbeg.de/geonetwork/srv/api/records/1dcc3786-fb81-4c4d-9e7e-f9e831ddb62b/formatters/xml 
start

Expected: normal test result

Actual: empty test result, https://inspire.ec.europa.eu/validator/v2/TestRuns/EID7ed5573b-52e7-462d-93bd-23ed15bcb8cc.html .

The staging instance works as expected. http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID19b8740c-7f12-4db4-a1fe-742f9eab0714.html

**Comment by carlospzurita** [comment]
Dear @tilmanb 

It seems that the validator is returning again normal Test Reports, as you can see in this one https://inspire.ec.europa.eu/validator/v2/TestRuns/EID50cf0073-5989-474a-8a7d-f51f2dcc4d39.html .

The error may be due to a momentanous overload on the system, as we did not detect any generalized error on the validator.

**Comment by carlospzurita** [comment]
We are closing this issue as it has not appeared again.
