### ISSUE TITLE
[Question] Health checks/probes

### ISSUE THREAD

**Issue by bor8** [INSPIRE-MIF/helpdesk-validator#465]
Does `/validator` have some health checks/probes available like `/ping` or `/health`?

So when I request `/ping` it will repsonse with `pong`. Or when I request `/health` it will response with `ok`.

Example GitLab:
https://docs.gitlab.com/ee/user/admin_area/monitoring/health_check.html

**Comment by carlospzurita** [comment]
Dear @bor8 

There are some method available to achieve this.

If you just need to check that the server is still up, you can use the HEAD operation `/v2/heartbeat`

```
~ curl --head https://inspire.ec.europa.eu/validator/v2/heartbeat

HTTP/1.1 204 No Content
Date: Fri, 04 Dec 2020 08:00:14 GMT
Server: nginx/1.16.1
X-Frame-Options: SAMEORIGIN
Access-Control-Allow-Origin: *
Access-Control-Allow-Origin: https://inspire.ec.europa.eu/validator/
Vary: Origin
Service-Status: GOOD
Name: INSPIRE Reference Validator
Version: 2.0.0-b191118T1324
Last-Modified: Fri, 04 Dec 2020 08:00:03 GMT
Expires: Fri, 04 Dec 2020 08:02:43 GMT
X-XSS-Protection: 1; mode=block
```
If you also need some more information about the status of resources (CPU, memory, disk space...), you can use `/v2/status`

```
~ curl --get https://inspire.ec.europa.eu/validator/v2/status

{"name":"INSPIRE Reference Validator","status":"GOOD","heartbeat":"1607069903520","willExpireAt":"1607070063520","version":"2.0.0-b191118T1324","uptime":"22783","allocatedMemory":"1067111696","presumableFreeMemory":"13378857712","totalSpace":"9223372036853727232","freeSpace":"9223372031738773504","cpuLoad":"0.007510"}

```
However, this checks can be deceiving, because if there has been some error on the validations, the TestDrivers may have crashed but the server is still running, it is better to use a "lighter" test run, like an small metadata record, to send to the validator and expect a `200 OK` response.

I hope that this summarizes everything for you. If you want further information, you can always use the API documentation at https://inspire.ec.europa.eu/validator/swagger-ui.html

**Comment by bor8** [comment]
Thank you! Would this be a valid feature request, that `/validator/v2/health` would do a simple/light test run and return that result?

**Comment by carlospzurita** [comment]
For now, it is not planned to modify the API of the validator, but this request will be taken into account for the future. You can easily monitor yourself with a POST request to `v2/TestRuns` as it is explained in the [training materials](https://github.com/inspire-eu-validation/community/tree/master/training%20material/2019-10-01%2B02%20JRC%20Workshop/Step-by-step%20example%20-%20API#create-a-new-testrun-using-the-testsuite-id-and-the-testobject-id) and substituting the `testObject` value for a JSON like this `{"resources":{"data":"[CSW_GetRecord_request]"}}`
