### ISSUE TITLE
ProductionFacility Test Reports Missing xlink:href for RiverBasinDistrictValue

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#478]
We're currently testing the Production and Industrial Facilities.

During the test for the ProductionFacility feature type we see the following error reported.

_Verify that any code list extensions are publicly accessible via HTTP, i.e. inspect extensible code list valued property elements. If a reference (@xlink:href) has a value that does not start with http://inspire.ec.europa.eu/codelist/, verify that a HTTP GET request to the URI retrieves a document.

Status | Failed
-- | --
Duration | 0.001 s

XML document 'service.xml', ProductionFacility 'pfProductionFacilityP.201': The attribute 'xlink:href' of the element 'RiverBasinDistrictValue' shall be provided._

However, in the ProductionAndIndustrialFacilities.xsd, there isn't an xlink:href attribute available for pf:riverBasinDistrict for the ProductionFacility feature type.

[PF_ProductionFacility.zip](https://github.com/inspire-eu-validation/community/files/5732233/PF_ProductionFacility.zip)

**Comment by carlospzurita** [comment]
Dear @robblis 

We are reviewing the ATS for ProductionFacility. In this, the element `pf:riverBasinDistrict` is not voidable, so that's the source of this error. The reason to have an href on this element is to link a value from the INSPIRE codelist. In this case, you would need to provide an href pointing to https://inspire.ec.europa.eu/codelist/RiverBasinDistrictValue

**Comment by fabiovin** [comment]
Dear @robblis,

in this case the element `pf:riverBasinDistrict` has multiplicity 0, so it could be not present in the dataset.
Because its data type is a codelist, if the element is present, it shall be encoded using an 'xlink:href' attribute.

The related codelist (https://inspire.ec.europa.eu/codelist/RiverBasinDistrictValue) is "empty", so the data provider should define its values and document them in a registry, providing the related URL in the 'xlink:href' attribute.

In your case, the encoding should be : 

` <pf:riverBasinDistrict xlink:href="URL of the related value in your registry">PO River Basin</pf:riverBasinDistrict>`

**Comment by robblis** [comment]
Hi @fabiovin ,

Here is the element from the ProductionAndIndustrialFacilities.xsd

![RiverBasinDistrict_Schema](https://user-images.githubusercontent.com/3453448/104644286-6c60d080-5662-11eb-842d-839fff2d56be.PNG)
	
The XML doesn't have any attributes (i.e. xlink:href) available for the pf:riverBasinDistrict in the schema.

Also, below is the XML copied from the .xsd. There is no <attribute> node in the pf:riverBasinDistrict element.
![RiverBasinDistrict_Schema2](https://user-images.githubusercontent.com/3453448/104645060-6cad9b80-5663-11eb-92e0-b75a29099039.PNG)

Can you please advise?

Thanks,
Robert

**Comment by robblis** [comment]
Hi @fabiovin,

Just checking if we can get any additional help on this issue.

Thanks,
Robert

**Comment by fabiovin** [comment]
Dear @robblis,

it seems there is an error in the xsd because the element should be encoded in this way:

![image](https://user-images.githubusercontent.com/46569952/114033612-b29e8800-987d-11eb-94cc-8ca71f6e0746.png)

It is strange that encoding using _xlink:href_ is possible by manually editing gml file but it is not possible through an ETL tool.

I tried using haleStudio and the pf:riverBasinDistrict element appears as a simple character string element. 

We will fix the error in xsd so that you can use it in your ETL tool.

**Comment by fabiovinci** [comment]
Dear @robblis,

the change has been implemented in the schema and released in the [2021.2 release](https://inspire.ec.europa.eu/schemas/pf/4.0/ProductionAndIndustrialFacilities.xsd).
