### ISSUE TITLE
Validation Character Encoding and Spatial Representation Type

### ISSUE THREAD

**Issue by LauraAlemany** [INSPIRE-MIF/helpdesk-validator#5]
Hello, 

When we use the inspire validator http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/
to check our metadata (all of them), we have the following errors: 

1. md-iop.a.5: Character Encoding
System error in the Executable Test Suite. Please contact a system administrator. Error information:
[err:FODC0002] "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml" (Line 1): Premature end of file. 
 (495/29)

2. md-iop.a.5: Spatial Representation Type
System error in the Executable Test Suite. Please contact a system administrator. Error information:
[err:FODC0002] "http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodelists.xml" (Line 1): Premature end of file. 
 (550/29)

We don’t know how to solve any of them. Could you please help us with this issue?
[we didn't have these errors before in any of our metadata, that's why we think it could be a problem or bug]

We attach you two metadata, for you to check in case you have any doubt with my explanation:
-	spaign_IGR_Transporte.xml  Dataset metadata
-	spaignwms_igr_transporte.xml  Service [metadata]
[SPAIN_MD.zip](https://github.com/inspire-eu-validation/community/files/2547788/SPAIN_MD.zip)

Thank you.

Yours sincerely,
Laura Alemany

**Comment by inakidiazdecerio** [comment]
Dear @LauraAlemany 

Thank you very much for reporting us the issue, and for using the community helpdesk. We are working to find a solution. The same happens for other metadata files, so after a first analysis, we have detecte that the problem shouldn be metadata file.

We will come back to you with the solution.

**Comment by carlospzurita** [comment]
Hello @LauraAlemany,

We checked on the INSPIRE validator, and on our deployment, and we encountered the same error downloading the schema hosted on http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml .

We downloaded the schema files, and changed the test to use the local copies. After that, the test run perfectly. It is unlikely that there is a problem with the firewall, because the file is reachable from inside the server. Maybe there is some problem with the downloading process on the validator, because there is a `<!--=== EOF ===-->` before the last tag, and it may be causing some trouble. Anyway, we will debug this and come back with more information.

**Comment by inakidiazdecerio** [comment]
Dear all,

We think that we have detected that the issue is related to the HTTP connection to http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodelists.xml and 
http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml files.

In our localhost environment we have used a **reverse proxy** instead of direct url and it worked fine.
That´s why, we think that there might be a modification in JRC´s server´s whitelists that is blocking http requests from ETF validator.

Thus, if JRC IT department adds http://standars.iso.org/publiclyAvailableStandards/ domain to server´s whitelist it should work. In order to test the validity of this solution, JRC IT staff can try to open this [url ](http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodelists.xml)from a browser.

Another solution could be to use a reverse proxy with access to that domain. In this case, we would need to know the address of this reverse proxy and modify the ETF/ETS code. 

Regards,

**Comment by df-git** [comment]
Dear @inakidiazdecerio,
Thank you for your suggestion. We tried to check using a wget on the Validator's server.
Both http and https request went fine. We notice that if you use the http there is a redirection (302) to https.
The problem could be related to the way the application is handling this redirect.
Can you please check?
Thank you,

![wget-test](https://user-images.githubusercontent.com/29379252/48352560-4065f100-e68d-11e8-80c9-6c3980a9c4e7.JPG)

**Comment by michellutz** [comment]
I would suggest implementing (1) as a quick fix in the ETS, and to create a bug report for the ETF on (2) to be discussed in the ETF TC/SG.

**Comment by cportele** [comment]
In the ATS discussion it was agreed to not expect clients to follow redirects, see
https://github.com/inspire-eu-validation/metadata#http-status-codes (similar text is in all ATS repositories). That is, the current behaviour is what has been specified.

Even if it would be considered a bug or if the ATS specifications would be changed, it is not something that is part of ETF. To change it, the Xqueries in the ETS repository would need to be changed.

**Comment by michellutz** [comment]
We would like to discuss the current rules for HTTPS redirects (see https://github.com/inspire-eu-validation/metadata#http-status-codes) in the sub-group tomorrow.

**Comment by aquaglia** [comment]
Considering that the INSPIRE implementations rely heavily on linking HTTP(S) resources,  I think that not requiring clients to follow redirects on HTTP GET requests is a very strong limitation which might hinder the usually required transition periods during the natural evolution of national SDIs.

Of course, automatic redirects on HTTP POST requests shall not be performed:

10.3 Redirection 3xx

This class of status code indicates that further action needs to be taken by the user agent in order to fulfill the request. The action required MAY be carried out by the user agent without interaction with the user if and only if the method used in the second request is GET or HEAD. A client SHOULD detect infinite redirection loops, since such loops generate network traffic for each redirection.
 (from https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html )

**Comment by inakidiazdecerio** [comment]
Dear @LauraAlemany,

We are happy to announce that the solution for this issue has been implemented in the INSPIRE Validator. We have prepared a testing environment with the solution. The solution passed our quality controls, but we will appreciate if you could test it before deploying it in production.

You will find the solution deployed in following link:

http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/

Thanks in advance for your help.

**Comment by LauraAlemany** [comment]
Good Morning Iñaki, 

I can't access that link, could you please verify the link is correct?

Thank you :)

**Comment by inakidiazdecerio** [comment]
Good morning @LauraAlemany,

The link is correct, the staging environment was down this morning. Now it is up.

Could you please try to test the solution again and return us your feedback?

Thank you.

**Comment by LauraAlemany** [comment]
Great Iñaki, 

I have passed one service metadata and one dataset metadata and there are no errors, so I guess the issue is fixed. 

Thank you :)
