### ISSUE TITLE
at42-getcapabilities-layer-default-style: wrong default style and missing style for BU

### ISSUE THREAD

**Issue by JPPauly** [INSPIRE-MIF/helpdesk-validator#512]
The ETS for default style name for Bulding (BU) contains `'BU.Building': ['BU.Building.default'], ` with a lower d `default `instead of the usual `Default`, also the second required style of the theme `BU.BuildingPart.Default` is not contained in the test at all.

This leads to correct wms services wrongly throwing an error in this test.

**Comment by carlospzurita** [comment]
Dear @JPPauly 

Thank you for opening this issue. We checked the ETS and it indeed was checking the wrong value of the default style and we are modifiying it. For the second required style, we have an open issue right now #491 that is also relevant for this issue, and we are working on it. The fix for that issue will reflect the fix in this one.

Kind regards.

**Comment by fabiovin** [comment]
Dear @carlospzurita,

the check for the `BU.BuildingPart.Default` style should also be present because `BU.BuildingPart` is an official layer (It is present on the registry: https://inspire.ec.europa.eu/layer/BU.BuildingPart).

Probably the error is due to a typo in the TG because in the section "_10.2.2 Styles for the layer BU.BuildingPart_" the "Style Name" is _BU.Building.default_ instead of _BU.BuildingPart.Default_.

Could you please add it to the ETS?

Thanks,
Fabio

**Comment by carlospzurita** [comment]
Dear @fabiovin 

We are adding this fix on the staging instance.

**Comment by carlospzurita** [comment]
Dear @JPPauly  

We have published a fix for this issue on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). Could you please check it out and give us some feedback?

Thank you

**Comment by JPPauly** [comment]
Dear @carlospzurita

Everything looks good to me and our BU-WMS does not show an error anymore for test at42 in the staging instance. 

Thank you.

**Comment by fabiovinci** [comment]
The related change proposal for the TG is [here](https://github.com/INSPIRE-MIF/technical-guidelines/issues/13).
