### ISSUE TITLE
XSD schema for validating XML files

### ISSUE THREAD

**Issue by mortenwh** [INSPIRE-MIF/helpdesk-validator#514]
I want to integrate validation against inspire in our testing scheme using the XML schema definition, and I'm looking for a valid xsd file. Do you know where to find that?

**Comment by carlospzurita** [comment]
Dear @mortenwh 

It is not very clear for us what you are trying to achieve. We understand that you want to use a deployment of the validator in your premises to validate files. Can you please elaborate more?

**Comment by mortenwh** [comment]
Ok - so I have an xml file which I want to check (I can upload one later if necessary, as I'll need to create it). In python, I could do as follows:
```
import lxml.etree as ET
xmlschema_mmd = ET.XMLSchema(ET.parse(xsd_schema))
xml_doc = ET.ElementTree(file=xml_file)
valid = xmlschema_mmd.validate(xml_doc)
```
`xsd_schema` is the one I'm looking for that should have the inspire definition, and `xml_file` is the file that is tested. If everything is ok, `valid=True`.

Thanks for helping out!

**Comment by iuriemaxim** [comment]
@mortenwh A short reply would be, that the INSPIRE XSD files are located here:  
https://inspire.ec.europa.eu/schemas/

However ...

Depending on the content of the dataset (which data themes it covers) different schemas should be used.

Here you may find the list of INSPIRE data themes:

https://inspire.ec.europa.eu/Themes/Data-Specifications/2892

Neither the creation, neither the validation of INSPIRE datasets and services is so simple as you describe it in your request, as it is not involving only XSD schemas (neither it is only one), but the XML should also follow other rules that that cant be expressed in an XSD schema. Furthermore, the XML files should be also provided trough INSPIRE compliant download service (ATOM, or preferably WFS and metadata trough CSW) that should fulfill also some specific rules.

The description below is reffering mainly to XMLs of features in a dataset, but you may find some information also about XMLs on metadata for datasets and services, as it seems that this is of interest to you.

Related to your approach, you should be aware that all INSPIRE features in a dataset are complex features, not simple features. All INSPIRE features are related to multiple XSD schemas and there are one to many relationships between elements (and features). 

To understand the complexity, below you may see some links to XML files served by a WFS service that are valid against the XSD schemas that are declared in the header of the XML files and are also valid against the Technical Guideline (TG) for the Environmental Monitoring Facilities, that can be found at https://inspire.ec.europa.eu/id/document/tg/ef and against other INSPIRE TGs related to this data theme.

In each XML file you will find links to other INSPIRE XML files and you can navigate from one INSPIRE XML to another INSPIRE XML and even back, of course each XML file being based on other XSD files.

https://inspire.meteoromania.ro/ids/EnvironmentalMonitoringNetwork.N100 - Example of short-URL to the N100 network. Similar URLs exist for each network: N301, N401, N402, N403, N501, N502, N650, N910, N920. 

https://inspire.meteoromania.ro/ids/EnvironmentalMonitoringFacility.15015 - Example of short-URL to the meteorological station 15015. Simmilar URLs exist for each meteorological station. The list of meteorological stations are found in the previous requests to various Monitoring Networks.

https://inspire.meteoromania.ro/ids/EnvironmentalMonitoringFacility.15015/WindSpeedSYNOP - Example of short-URL for the Wind Speed sensor from the meteorological station 15015. Similar URLs exist for each station that is part of the N100 network for each of the following sensors: RelativeHumiditySYNOP, WindDirectionSYNOP, TotalPrecipitationsSYNOP, TemperatureSYNOP, TemperatureMinimumDailyClimat, TemperatureAverageDailyCLIMAT, TemperatureMaximumDailyCLIMAT, TotalPrecipitationCLIMAT.

https://inspire.meteoromania.ro/ids/OM_Observation.EnvironmentalMonitoringFacility.15015.WindSpeedSYNOP.AllValuesWML20 - Example of Short-URL to retrieve the all data from WindSpeed sensor in the meteorological station 15015 in WaterML 2.0 format. Similar short-URLs exist for each sensor and each meteorological station that is part of the N100 network. 

https://inspire.meteoromania.ro/ids/OM_Observation.EnvironmentalMonitoringNetwork.N502.WindSpeedAverage10Years.GeoTIFF - Example of short-URL for observations declared as RectifiedGrid. Similar short-URLs exist for the observations of networks N910, N920 (AvailableWatercapacity) and for N501 (GlobalradaiationFluxYearlyAverage).

https://inspire.meteoromania.ro/ids/OM_Observation.EnvironmentalMonitoringNetwork.N301.AEROSComposed.BUFR - Example of short-URL provided the observation of the network N301. Similar short-URLs exist for the networks N401, N402, N403 and N650.

https://inspire.meteoromania.ro/data/M402.nc - Example of short-URL to the M402 meteorological product (Snow Depth) provided in NetCDF format. Similar short-URLs exist for all meteorological products provided as files: M910.tif, M920.tif, M501.tif, M502.tif, M301.bufr, M401.nc, M403.nc, M650.nc. M502 and M503 products are updated yearly. M910 and M920 that are updated every 10 days during the periods of sowing of maize and winter wheat. 

Data in XML files that are served trough WFS are updated daily, or even more frequent, as it represent meteorological data.

In order to check that the above XML files are valid against their corresponding INSPIRE Conformance Classes, you may use the INSPIRE Validator accessible at https://inspire.ec.europa.eu/validator/about/

You may try to use your approach in Python to validate the above XMLs, but this will cover only one of the first validation steps that are done in the INSPIRE Validator.

If you will test for example this XML file https://inspire.meteoromania.ro/ids/EnvironmentalMonitoringNetwork.N100
against the conformance classes for "Data Theme: Environmental Monitoring Facilities (Data Specification version 3.0)" ...

![image](https://user-images.githubusercontent.com/20813598/108917767-eeb4bb00-7638-11eb-9dff-c5f8eb4cecbb.png)

... then you will see that the validation is more complex than only to check the content of the XML against several XSD schemas.

![image](https://user-images.githubusercontent.com/20813598/108917524-8c5bba80-7638-11eb-9bee-f853dceaf20a.png)

If you intend to create only metadata files, than this is slightly more simple, but still not easy.

For example, the metadata of the dataset is accessible at https://inspire-staging.meteoromania.ro/WIGOS/MD-DS and there can be found more details about the dataset and how the data can be viewed and downloaded trough OGC services.

The XML file can be tested against the Metadata Conformance Class 2

![image](https://user-images.githubusercontent.com/20813598/108919923-7ea83400-763c-11eb-8592-abd974113861.png)

![image](https://user-images.githubusercontent.com/20813598/108920450-58cf5f00-763d-11eb-99b7-6e958933e486.png)

Other Metadata files created for INSPIRE services that alows for dataset view and download and that could be tested against the Conformance Class 4 are:
https://inspire-staging.meteoromania.ro/WIGOS/MD-WMS
https://inspire-staging.meteoromania.ro/WIGOS/MD-WFS

In both cases, for the XML files representing features within the dataset and for the XML files representing metadata files for the dataset and for the view and download services, the validation against the XSD schemas is only one step out of many.

Hope it helps

**Comment by MarcoMinghini** [comment]
Dear @mortenwh, we assume the answers provided were enough to solve your problem. Thus, we close this issue but please feel free to open it again in case you need some help on the validation of INSPIRE resources.
