### ISSUE TITLE
Release 2021.1 17/03/2021

### ISSUE THREAD

**Issue by carlospzurita** [INSPIRE-MIF/helpdesk-validator#528]
Dear INSPIRE users,

The next release of the INSPIRE reference validator has been scheduled to take place next Wednesday morning. We will notify when the validator will be shut down and report back when the service is restored. Please make sure to save any relevant information that you want to preserve.

Thank you.

**Comment by ghost** [comment]
Hi Carlos,

do you plan to include the fix for https://github.com/INSPIRE-MIF/helpdesk-validator/issues/525 in the new version? It would be nice to have this in the new release.

Many issues are marked as "[under development](https://github.com/INSPIRE-MIF/helpdesk-validator/issues?q=is%3Aopen+is%3Aissue+label%3A%22under+development%22)" and "[ready for testing](https://github.com/INSPIRE-MIF/helpdesk-validator/issues?q=is%3Aopen+is%3Aissue+label%3A%22ready+for+testing%22)". Do I owe some feedback for the next release?

Thanks in advance.

**Comment by manilly** [comment]
Dear Carlos,
I've seen, that there is already a pre-release for Validator v2021.1. When will the corresponding inspire-validator-2021.1.zip and ets will be available?
Thanks

**Comment by carlospzurita** [comment]
We had to delay the release of the validator as we encountered some problems in one of the issues to be included on the release. We hope to solve it along the morning.

Kind regards and sorry for the inconveniences.

**Comment by carlospzurita** [comment]
Dear @DeordD 

There is no pending actions from your side at the moment. Thank you very much for your offering.

**Comment by carlospzurita** [comment]
The release 2021.1 is already available on the [INSPIRE Reference Validator](https://inspire.ec.europa.eu/validator/). You can check it out [here](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2021.1)

**Comment by sraimund** [comment]
I get the error "Test Run initialization failure" when I start test runs in the online validator (e.g. Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records). Tried it with Firefox and Chrome.

**Comment by carlospzurita** [comment]
The release was completed and tested. The errors appeared afterwards, during the normal operations of the validator. The issue has been sorted out, but we are still investigating the cause of the error.

We are closing this issue. If other relevant errors appear on the validator, please follow the normal procedure of opening a new issue in the helpesk.

Kind regards.
