### ISSUE TITLE
Elevation Vector Test Not Finding 'Elevation' Feature Object Type

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#529]
Hi Validator Team,

We're working on our Elevation Vector GML output. 

We are getting the following validation error in the Conformance Class 'GML application schemas, Elevation' test.

_The XML documents representing the spatial data set do not contain a feature of any of the spatial object types in the 'Elevation' application schemas. Therefore, the spatial data set cannot conform to this conformance class. If you have expected to find spatial objects from the application schema in the data set, please consult the statistics information to see the spatial object types that have been found._

The returned XML contains the el-vec:BreakLine features.

Is the test looking for something else?

We've uploaded the output xml and the test report.

Thanks for your help,
Robert

[EL_BreakLine_Test.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6145024/EL_BreakLine_Test.zip)

**Comment by fabiovin** [comment]
Dear @robblis,

there is a typo in the related ETS (https://github.com/inspire-eu-validation/ets-repository/blob/data-el-staging/data-el/el-gml/ets-el-gml-bsxets.xml).

The validator is checking for the feature type "el-vec:Break**l**ine" instead of "el-vec:Break**L**ine", with capital "L".

I updated the related ATS (https://github.com/inspire-eu-validation/data-el/blob/master/el-gml/basic.md).

@carlospzurita, could you please upadate the ETS? 

Thanks

**Comment by carlospzurita** [comment]
Dear @robblis

The ETS has been updated with the fix on the Feature Object Type on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). Can yoy please check it out?

**Comment by robblis** [comment]
Hi @carlospzurita,

We just re-tested BreakLine and all the tests have passed.

Thank you for your assistance,
Robert
