### ISSUE TITLE
Help with 1.4 INSPIRE Theme Keyword and 1.10: Dataset Conformity

### ISSUE THREAD

**Issue by LauraAlemany** [INSPIRE-MIF/helpdesk-validator#536]
Hello, 

I am using the https://inspire.ec.europa.eu/validator/ to validate this [dataset metadata file](https://www.idee.es/csw-codsi-idee/srv/spa/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetRecordById&outputSchema=http://www.isotc211.org/2005/gmd&ElementSetName=full&ID=spaignLLM) (TG version 2.0). I have selected the following options of the ETS:
- Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records
- Conformance Class 1 (...)
- Conformance Class 2 (...)

I got some issues in the report that I don't know how to solve. Those errors had not appeared before. Are there some new changes in the tool?

 These are the issues I don't know how to solve: 

1) 1.4 INSPIRE Theme Keyword
Assertion URI: https://inspire.ec.europa.eu/validator//v2/TestRuns/EID96607530-0c2a-4ad2-9d26-aa714ee978b8.html?lang=es#EID59828fff-3e73-4ccc-a06b-2f331d1aab89
Message: "System error in the Executable Test Suite. Please contact a system administrator. Error information:
Code list http://inspire.ec.europa.eu/theme cannot be accessed."

2) 1.10: Dataset Conformity
Assertion URI: https://inspire.ec.europa.eu/validator//v2/TestRuns/EID96607530-0c2a-4ad2-9d26-aa714ee978b8.html?lang=es#EID100d72f9-d61e-48a1-9fba-0b251b46f953
Message: "System error in the Executable Test Suite. Please contact a system administrator. Error information:
[err:FODC0002] "http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_bul.xsd" (Line 1): Premature end of file. 
 (977/15)"

I would appreciate if you can help me to solve them.

Thank you.

Best regards,
Laura

**Comment by krimar58** [comment]
Hallo!
I also have problem with the ETF-validator not being able to access the codelists.
This is probably due to the redirect from http->https that was introduced a couple of weeks ago.

'System error in the Executable Test Suite. Please contact a system administrator. Error information:
Code list http://inspire.ec.europa.eu/codelist/GrammaticalNumberValue cannot be accessed.'

'System error in the Executable Test Suite. Please contact a system administrator. Error information:
Code list http://inspire.ec.europa.eu/codelist/GrammaticalGenderValue cannot be accessed.'


Are you working on this issue?

Best regards
Kristina Martinelle
SGU Sweden

**Comment by iuriemaxim** [comment]
Hello,

I can confirm as well that a metadata file that always passed the tests, from more than one year and a half, now it fails the Conformance Class 1.

Metadata of the dataset to test https://inspire-staging.meteoromania.ro/WIGOS/MD-DS, now fails with these two errors which are not indicating that that the data provider can do something to fix the issues:

**Error 1**

![image](https://user-images.githubusercontent.com/20813598/114093033-49416800-98c3-11eb-83b1-74b926cf294d.png)

**Error 2**

![image](https://user-images.githubusercontent.com/20813598/114093123-69712700-98c3-11eb-985b-3e359c9920e8.png)

**Comment by iuriemaxim** [comment]
A simmilar issue also appeared now on Conformance Class 3 with metadata files that were always passing the tests, such as https://inspire-staging.meteoromania.ro/WIGOS/MD-WFS

Now the following error appear, that is indicating an error that should not be fixed by the data provider:

**Error 3**

![image](https://user-images.githubusercontent.com/20813598/114094166-a7bb1600-98c4-11eb-9385-8bd7e08ded6e.png)

**Comment by iuriemaxim** [comment]
One of the problem seems to be due to the fact that the schemas were updated on 1 March 2021 as can be seen in the image below if accessing the https://inspire.ec.europa.eu/schemas/ 

Actually they were moved from http to https.

There is also this incident that was opened almost one month ago https://github.com/INSPIRE-MIF/helpdesk-validator/issues/525 which was solved and then re-opened.

It is not clear if the problem is only related to the INSPIRE schemas and/or schema caching mechanism.

![image](https://user-images.githubusercontent.com/20813598/114094790-64ad7280-98c5-11eb-9185-6a9b78fe0423.png)

**Comment by jmrubio82** [comment]
EEA is having also the same issue when validating previously compliant metadata:

System error in the Executable Test Suite. Please contact a system administrator. Error information:
Code list http://inspire.ec.europa.eu/theme cannot be accessed.

System error in the Executable Test Suite. Please contact a system administrator. Error information:
[err:FODC0002] "http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_bul.xsd" (Line 1): Premature end of file. 
 (977/15)

Thanks for checking!
Jose Miguel

**Comment by carlospzurita** [comment]
Dear all,

We checked this issue and rebooted the caching system for handling the redirection to the registry. The issue is no longer happening. We are aware of this problems and we are working on a way to prevent this from happening in the future.

Kind regards.

**Comment by iuriemaxim** [comment]
@carlospzurita I can confirm that the above errors are not triggered anymore

Result of testing https://inspire-staging.meteoromania.ro/WIGOS/MD-DS against Conformance Class 2

https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDf9166c5f-e580-4f10-8c30-75f7f94103f0.html

![image](https://user-images.githubusercontent.com/20813598/114276843-1ddc8b80-9a31-11eb-914a-08c9a3d63da1.png)

Result of testing https://inspire-staging.meteoromania.ro/WIGOS/MD-WFS against Conformance Class 4

https://inspire.ec.europa.eu/validator/v2/TestRuns/EID8cde2aa0-83e3-43dc-b8c1-b3311c097b68.html

![image](https://user-images.githubusercontent.com/20813598/114276895-57ad9200-9a31-11eb-882e-393172eaaa0b.png)

Incident 536 can be closed.

**Comment by LauraAlemany** [comment]
Thank you!
