### ISSUE TITLE
Error message INSPIRE VALIDATOR

### ISSUE THREAD

**Issue by yaizavalidador** [INSPIRE-MIF/helpdesk-validator#546]
Good morning,

I am trying to pass the INSPIRE Reference validator test to this service: https://wms-ine.idee.es/secciones?SERVICE=WMS&REQUEST=GetCapabilities

I don't understand the error message that appears:
_Test Run initialization failure. unable to find valid certification path to requested target._

What might be wrong in the capabilities?

Thanks for your help.

Yaiza.

![Captura](https://user-images.githubusercontent.com/83811743/117654712-6dc88280-b196-11eb-9884-e69660731766.PNG)
![Captura2](https://user-images.githubusercontent.com/83811743/117654715-6e611900-b196-11eb-87bc-4d091fc2280b.PNG)

**Comment by dperezBM** [comment]
Dear @yaizavalidador,

Thank you for your feedback. This issue is already reported on issue #543 and fixed on our [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html). Please feel free to test your WMS service there. 

If you have any other issues please let us know.

Best regards.
