### ISSUE TITLE
Not sure if I understand an error for at06-extended-capabilities-elements

### ISSUE THREAD

**Issue by nmtoken** [INSPIRE-MIF/helpdesk-validator#55]
Testing the following service for INSPIRE WCS conformance at (http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/):

http://ogc2.bgs.ac.uk/cgi-bin/GEMAS/ows?SERVICE=WCS&acceptVERSIONs=2.0.1&REQUEST=GetCapabilities&

It has an extended capabilities section scenario 2 and is schema valid against http://inspire.ec.europa.eu/schemas/inspire_dls/1.0/inspire_dls.xsd

I get an error 

    Test that the INSPIRE metadata is provided using the Metadata URL element or it is provided in the ExtendedCapabilities section.

    More information: Extended capabilities elements

    Status	Failed
    Duration	0.232 s
    Dependency	check-initial-testcase
    Test case ID	EID52f5767a-2f01-4fd8-a134-d5aa138ce591

but it's nested in a section that has an inner error that has 'check-other-mandatory-elements' and an error that is nothing to do with extended capabilities (ie. coverage summary), so I can't work out if this is a bug in the test, or something else ~ is there an issue with the ExtendedCapabilities as well as the Coverage Summary?

**Comment by bgsmase** [comment]
Failing test is in ETS https://github.com/inspire-eu-validation/ets-repository/blob/24380c2651b6e1e84fcc8b4bcadd344991f0418e/service/ds-wcs-core-soapui-project.xml#L294. This isn't directly mentioned in the ATS at https://github.com/inspire-eu-validation/download-service/blob/tg-ds-wcs-1.0/wcs-core/at06-extended-capabilities-elements.md but it refers to Table 16 of https://inspire.ec.europa.eu/id/document/tg/download-wcs where we see that ows:BoundingBox inside the CoverageSummary rather than in the ExtendedCapabilities as a mandatory element. So that probably accounts for the confusion of a check in the ExtendedCapabilities section referring to elements outside the ExtendedCapabilities section.

**Comment by nmtoken** [comment]
So it's an error in the test, I shouldn't get a fail for the valid extended capabilities (there should be two failures reported, not three)

Creating a static version of the GetCapabilities response (http://ogcdev.bgs.ac.uk/WCS/GEMASwCovSummBB.xml) with ows:BoundingBox info in the Coverage Summary, and no changes to the extended capabilities gives a **Status | Passed, manual checks required**

**Comment by danielnavarrogeo** [comment]
Dear @nmtoken 

Thank you for your comments.

We have tested the service you have provided:

http://ogc2.bgs.ac.uk/cgi-bin/GEMAS/ows?SERVICE=WCS&acceptVERSIONs=2.0.1&REQUEST=GetCapabilities&

We only got one TestStep failed 'check-other-mandatory-elements' which is in the TestCase 'at06-extended-capabilities-elements' which belongs to the TestModule 'Service_Metadata':
![imagen](https://user-images.githubusercontent.com/45062523/58967210-105e7680-87b4-11e9-8b23-d10339ae2e93.png)

Maybe there is some sort of confusion because the TestCase is 'at06-extended-capabilities-elements' and then, inside of it, there is two different TestSteps 'check-extended-capabilities' and 'check-other-mandatory-elements'. This is because TG requirement 6 mentions explicitly the elements of table 16 where CoverageSummary/BoundingBox appears.

In the ATS https://github.com/inspire-eu-validation/download-service/blob/tg-ds-wcs-1.0/wcs-core/at06-extended-capabilities-elements.md it is described that in scenario 2, the test "Check that all the mandatory elements shown in table 16 of INS TG WCS are provided."

Do you think it would be more clear to change the name of at06 to 'at06-extended-capabilities-elements-and-other-elements'?

Regards

**Comment by nmtoken** [comment]
at06 should be called just  '**Check all the mandatory elements**' to avoid confusion

**Comment by danielnavarrogeo** [comment]
Dear @nmtoken 

We have updated the test to avoid confusion based on your proposal.

The ATS and ETS has been renamed to at06-mandatory-metadata-elements.
ATS:
https://github.com/inspire-eu-validation/download-service/blob/tg-ds-wcs-1.0/wcs-core/at06-mandatory-metadata-elements.md

ETS:
![imagen](https://user-images.githubusercontent.com/45062523/59253381-5db46b00-8c2e-11e9-8f09-f68ca762905f.png)

Please let us know if this solves the issue.

Regards

**Comment by nmtoken** [comment]
that's fine by me

**Comment by MarcoMinghini** [comment]
Dear @nmtoken, thanks for your feedback. We marked the issue as 'solved', but we will keep it open until the solution is also included in the production instance of the Validator.
Thanks again for taking time to test the WCS ETS.
