### ISSUE TITLE
Problem with validating data on eu online validator

### ISSUE THREAD

**Issue by ganevbg** [INSPIRE-MIF/helpdesk-validator#554]
Hi there,
from couple of days we have problems validating any dataset with https://inspire.ec.europa.eu/validator/ . It gives us the same 2 errors with any dataset. Here is a link with validation results - https://inspire.ec.europa.eu/validator//v2/TestRuns/EID2476698f-4bb1-4ad7-871f-ab95d6ce334b.html 
 
Here are some images if the test result disapears for some reason.

![image](https://user-images.githubusercontent.com/11047121/120283817-46139880-c2c4-11eb-9007-b62064d316df.png)

![image](https://user-images.githubusercontent.com/11047121/120283867-51ff5a80-c2c4-11eb-8ec8-106c8d30c25d.png)

Greetings,
Ganev

**Comment by carlospzurita** [comment]
Dear @ganevbg 

We are checking the issue on the production instance. Can you please provide the metadata record you are trying to validate?

Thank you

**Comment by ganevbg** [comment]
Hi @carlospzurita,
Thanks for reaching out! Here is the file - 
[2e8360b9-ba88-4c7f-818a-32ac2e0f3806.txt](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6589161/2e8360b9-ba88-4c7f-818a-32ac2e0f3806.txt)

It is in txt format, becaouse the form does not support xml.

Greetings,
Ganev

**Comment by fabiovin** [comment]
Dear @ganevbg,

I tested your metadata and it is 100% valid (https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID21c0446d-0eb1-4442-8771-ae4bd33e4b4a).

Errors related accessing INSPIRE website/schemas are often due to temporary caching system problems.

I will close the issue, please open a new one if the error appears again.

Regards,
Fabio
