### ISSUE TITLE
Strict check on the attribute indeterminatePosition for temporal extent element

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/helpdesk-validator#557]
I tested this metadata record 
[c_d969-36c37888-4d92-4668-91d3-7ef5808176f2.xml.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6617069/c_d969-36c37888-4d92-4668-91d3-7ef5808176f2.xml.zip) and I got an error about the temporal extent element as the `indeterminatePosition` attribute is missing. I.e. the metadata record includes `gmd:temporalElement/gmd:EX_TemporalExtent/gmd:extent` element containing a `gml:TimePeriod` element with start and end dates of the period (i.e. elements `gml:startPosition` and `gml:endPosition`). The time period is open-ended with the `gml:endPosition` element empty but without the attribute `indeterminatePosition`.

Below the XML fragment:

```xml
<gmd:temporalElement>
       <gmd:EX_TemporalExtent>
           <gmd:extent>
                 <gml:TimePeriod gml:id="TP1">
                      <gml:beginPosition>2005-06-01</gml:beginPosition>
                     <gml:endPosition/>
                </gml:TimePeriod>
         </gmd:extent>
     </gmd:EX_TemporalExtent>
</gmd:temporalElement>
```

Here the Test Report: https://inspire.ec.europa.eu/validator/v2/TestRuns/EID28371e2a-541d-4fc7-adee-3ddd9b867a84.html

Here the Assertion URI: https://inspire.ec.europa.eu/validator//v2/TestRuns/EID28371e2a-541d-4fc7-adee-3ddd9b867a84.html?lang=it#EID7c0c2217-267c-4bc5-a262-ac631aaa2531

Based on the wording of the TG Requirement C.14, I think that no error should be raised in case of missing `indeterminatePosition` attribute. That requirement indeed states that " ... the elements gml:startPosition or gml:endPosition **MAY** be used with an empty value and the attribute indeterminatePosition", where the verbal form "may" (and not "shall") is used.

**Comment by fabiovin** [comment]
Dear @AntoRot,

our interpretation of the TG Requirement C.14 is that since the first sentence states "_... element **shall**
contain a gml:TimePeriod element containing start and end dates ..._" (in yellow) both values SHALL be provided and therefore shall not be empty and shall contain some information.

The next two sentences indicate how they may be encoded in the case there is no specific date, so the two conditions, _empty value and attribute indeterminatePosition_ (in orange and in blue for the two different cases), shall be fulfilled.

![image](https://user-images.githubusercontent.com/46569952/121331454-2d842d80-c917-11eb-86fa-996b93b72a15.png)

Therefore, if there is no specific date the attribute _indeterminatePosition_ shall be provided.

What do you think?

**Comment by AntoRot** [comment]
Dear @fabiovin,

Thank you for your feedback.

Your interpretation makes sense to me, consequently the issue may be closed.

Kind regards,
Antonio

**Comment by iuriemaxim** [comment]
@AntoRot @fabiovin

Most probably relevant to this discussion is also this one  https://github.com/INSPIRE-MIF/helpdesk-validator/issues/188, as it covers a simmilar subject and maybe it helps for a better formulation of the requirement.

**Comment by dperezBM** [comment]
Dear all,

Since this issue had no interaction time ago, we decided to close it. Please feel free to open a new one if needed.

Thank you and best regards.
