### ISSUE TITLE
Error when validating WFS

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#565]
Hi everyone,

When trying to validate a Direct WFS (I tried with https://haleconnect.com/ows/services/org.789.73624544-30b2-405a-83bb-52c45ae50f23_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0) an error occurs 
![grafik](https://user-images.githubusercontent.com/34163838/122725255-175e6180-d275-11eb-9691-b95d7e87643c.png)

This is the configuration I used 
![grafik](https://user-images.githubusercontent.com/34163838/122725370-33fa9980-d275-11eb-82b0-2e2225b13d5b.png)

Please let me know if you need any more information to investigate the issue.

All the best

Johanna

**Comment by jenriquesoriano** [comment]
Dear @johannaOtt,

we have tested the provided link in the production environment and we have not been able to reproduce the error indicated in the uploaded screenshot, getting the test run and its corresponding test report. 
Please see:
https://inspire.ec.europa.eu/validator/test-run/index.html?id=EIDa57c1edd-3a60-45a9-8bd0-a5e1836104a1

In this regard, we are not sure if the test has been performed on the production environment. 
If this is the case, it is possible that this issue was caused due to some punctual unavailability.
If the problem persists, please let us know.

Best,

**Comment by JohannaOtt** [comment]
Dear @jenriquesoriano 

Thank you for investigating. I can confirm that the test is currently starting and running.
There are two issues with the result though
1. The OGC Team Engine test is running into a timeout
2. The Pre-defined WFS conformance class is run although not configured.

Could you please check why that is?


All the best

Johanna

**Comment by fabiovin** [comment]
Dear @JohannaOtt,

regarding point 2 "_The Pre-defined WFS conformance class is run although not configured._", we added the dependency to this conformance class because the test included in it shall also be verified for a "Direct WFS".

See issue #476 for reference.

**Comment by marcusmohr** [comment]
Hello everyone, I get the same error as described by @JohannaOtt 

The browser console shows the following message:
`
responseJSON: Object { error: "Die Initalisierung des Testlaufs ist aufgrund eines internen Problems fehlgeschlagen. Bitte kontaktieren Sie Ihren Systemadministrator. ", timestamp: "1625735380281", url: "http://inspire.ec.europa.eu/validator/v2/TestRuns", … }
​​
error: "Die Initalisierung des Testlaufs ist aufgrund eines internen Problems fehlgeschlagen. Bitte kontaktieren Sie Ihren Systemadministrator. "
​​
id: "l.internal.testrun.initialization.error"`

The whole error log:
[console-export-2021-7-8_11-20-47.txt](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6783274/console-export-2021-7-8_11-20-47.txt)

Test Url:
https://inspire.brandenburg.de/services/ad_alkis_wfs?Request=GetCapabilities&Service=WFS&Version=2.0.0

**Comment by jenriquesoriano** [comment]
Dear @JohannaOtt , @marcusmohr , 
thansk for your contribution, we are currently analyzing the cause of this initial error.
We will keep you posted as soon as we identify the issue and provide a solution to this.
Best

**Comment by iuriemaxim** [comment]
@jenriquesoriano 

Same happen to me while testing 
https://inspire-staging.meteoromania.ro/WIGOS/WFS?service=wfs&version=2.0.0&request=GetCapabilities 
against the Direct-WFS Conformance class in production environment (https://inspire.ec.europa.eu/validator/test-selection/index.html), even if the service passed separately both Direct-WFS and Predifined-WFS in the old INSPIRE validator interface.

Therefore I tried to execute only the Predefined-WFS test in the new UI and currently the service is not passing this test, altrough it passed in the old UI:

![image](https://user-images.githubusercontent.com/20813598/125157049-5ba49980-e171-11eb-9939-0f17844d9a24.png)

Link to test report in the production environment:

https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID33823118-ddf0-4eb0-8e7b-3fc80de86cd9

Testing it again few minutes later in production environment it provided another error:

![image](https://user-images.githubusercontent.com/20813598/125157603-af64b200-e174-11eb-8337-62cf430b6037.png)

Link to test report: https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDee2a5109-dd4f-4fec-9a85-2e3f17cee439

Link to log file: https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDee2a5109-dd4f-4fec-9a85-2e3f17cee439/log

10.07.2021 08:52:59 ERROR startup failed:
Script1.groovy: 113: expecting '}', found 'if' @ line 113, column 121.
   operationXPath+owsValueXPath) if(values.

Validating the same service against the Predefined-WFS in the staging environment of the new UI provides another eror:

![image](https://user-images.githubusercontent.com/20813598/125157334-28630a00-e173-11eb-8a9b-d125cd682039.png)

![image](https://user-images.githubusercontent.com/20813598/125157366-42045180-e173-11eb-9293-169f1aa71ebc.png)

Link to test report in the staging environment:
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EIDbbac56fb-073c-407d-afd2-807a66bad741

While looking in the log (http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/TestRuns/EIDbbac56fb-073c-407d-afd2-807a66bad741/log), it appears the following:

10.07.2021 08:32:26 ERROR org.xml.sax.SAXException: Fatal error: org.xml.sax.SAXParseException; systemId: **http://inspire.ec.europa.eu/schemas/inspire_dls/1.0/inspire_dls.xsd; lineNumber: 1; columnNumber: 1; Premature end of file.** Response did not validate against schema 'http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd http://inspire.ec.europa.eu/schemas/inspire_dls/1.0 http://inspire.ec.europa.eu/schemas/inspire_dls/1.0/inspire_dls.xsd'.

It appears that in order to fix the Direct-WFS conformance class validation, it needs to be fixed first the Predefined-WFS conformance class, which worked correctly in the past (at least two-three month ago it worked as expected).

All the best,
Iurie Maxim

**Comment by zguo** [comment]
Any recent updates on this issue? it looks  like we have the same issue with the following service, it said

ERROR
An error has occurred

http://inspiredemo.esri.com/arcgis/rest/services/hy1081_int_wc/MapServer/exts/InspireFeatureDownload/service?VERSION=2.0.0&SERVICE=wfs&REQUEST=getcapabilities

Thanks,

ZhongPing

**Comment by nmtoken** [comment]
Just adding that I have the same error today, trying to test Direct Access WFS:

https://inspire.lneg.pt/arcgis/rest/services/CartografiaGeologica/CGP1M/MapServer/exts/InspireFeatureDownload/service?SERVICE=WFS&request=GetCapabilities&acceptversions=2.0.0

I tried too against predefined WFS test and no test seems to run ~ no red box error as above, just a _skipped_ reponse

Report: https://inspire.ec.europa.eu/validator/test-reports/details.html?id=EID8359a434-f4a5-47f5-b4dd-0f4538f5f7cf

**Comment by carlospzurita** [comment]
Dear all,

This issue was related to the dependency between WFS Direct and the OGC TEAM engine test, which had an error loading the available tests. We have updated the staging instance with a fix, and now the WFS Direct is available. You are able to test it on http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html

Kind regards.

**Comment by zguo** [comment]
Thanks @carlospzurita, the error is gone. I can run the  WFS validation test on the staging site now.

**Comment by JohannaOtt** [comment]
When I just tried testing [this WFS](https://haleconnect.com/ows/services/org.789.f5f15dcd-b11a-491e-a37c-bec458c8c1b6_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0) in the staging instance, the error still occurred. So I would not agree that the error is gone.
![grafik](https://user-images.githubusercontent.com/34163838/132225244-65ff63e7-ddb5-4928-a99e-0529d1c0c13a.png)

**Comment by carlospzurita** [comment]
Dear @JohannaOtt 

This issue has relation to an error coming from the integration of the validator with the OGC TEAM engine. The WFS Direct test has a dependency with the WFS test suite of that service, and if the latter is not loaded then the test is deactivated on the INSPIRE Validator.

The error is due to changes in the response format of the TEAM Engine and the way this responses are processed by the validator.  We applied a fix in response to the change from XML to JSON in the format of the service, however it seems they have reverted this feature and the response is back to XML. We have an [open discussion](https://github.com/opengeospatial/teamengine/issues/469) on their repository about this.

We will keep you posted and try to solve this situation as soon as possible.

**Comment by carlospzurita** [comment]
Dear @JohannaOtt 

We have published a fix for the WFS direct load issue on the staging instance. Please, go to http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html and test the integration. We would like to have your feedback to solve this issue.

Kind regards.

**Comment by JohannaOtt** [comment]
I can confirm that I do not see the red error message any longer when trying to validate a WFS.

**Comment by JohannaOtt** [comment]
I have to take that back - just happened again when trying to validate [this WFS](https://haleconnect.com/services/bsp/org.292.6cef2128-a227-4aa7-bc74-0e3797644d51/md/service/id_direct_download). 
![grafik](https://user-images.githubusercontent.com/34163838/135447889-3769191a-f330-441a-abf4-a3a196edde63.png)

**Comment by carlospzurita** [comment]
Dear @JohannaOtt 

I don't know if that link is correct, because it is returning a Metadata Records and not a GetCapabilities from a WFS. Could you please check again?

We executed a Direct test with [this](https://www.juntadeandalucia.es/institutodeestadisticaycartografia/geoserver-ieca/grid/wfs?request=GetCapabilities&service=WFS) WFS and it works. Check the [test report](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EID2644d13b-0cd9-4864-a7f9-20856420103f).

Kind regards

**Comment by JohannaOtt** [comment]
Ah sorry, thanks!

**Comment by nmtoken** [comment]
> 
> We have published a fix for the WFS direct load issue on the staging instance. Please, go to http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html and test the integration. We would like to have your feedback to solve this issue.
> 

I tried today, test ran for some time then I got at error

![image](https://user-images.githubusercontent.com/1692891/135613431-8bc583b0-aed7-49bf-8c6f-e45a526ad940.png)

**Comment by jenriquesoriano** [comment]
Dear @JohannaOtt 

his issue has been solved, we have tried a direct WFS and it worked fine.
![imagen](https://user-images.githubusercontent.com/25343632/149943565-ec5572eb-0c15-48a5-86b6-94d7e5a59ee4.png)

In case it raises again, we kindly ask you to create a new issue reporting the problem encountered.
We take the chance to thank you again for your contribution and feedback.

Best regards

**Comment by JohannaOtt** [comment]
@jenriquesoriano I can confirm that the test is running.
