### ISSUE TITLE
md common req C.5: Language Code & md datasets-and-series 1.6: Resource Language

### ISSUE THREAD

**Issue by alitka** [INSPIRE-MIF/helpdesk-validator#567]
- [x] description of the steps:
1. go to http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp and select `Metadata` AND `Version 2.0` AND `Data sets and data set series`
2. start the test and upload external file: [de_language_codeList_dataset.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6691974/de_language_codeList_dataset.zip)
- [x] used browser and version: Firefox Browser Extended Support Release 78.11.0esr (64-bit)
- [x] screenshot of the problem:
md common req C.5: Language Code: ![grafik](https://user-images.githubusercontent.com/29542183/122874123-ea708400-d332-11eb-8656-62bdf0a8831e.png)
md datasets-and-series 1.6: Resource Language: ![grafik](https://user-images.githubusercontent.com/29542183/122874200-01af7180-d333-11eb-8d0f-fb04db3f09d9.png)
- [x] Test Report: [de_language_codeList_report.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6691977/de_language_codeList_report.zip)
- [x] failed Tests: 
1. md common req C.5: Language Code 
2. md datasets-and-series 1.6: Resource Language

An agreement in the former MIWP 2017.4 was ([meeting #11 2019-07-17](https://webgate.ec.europa.eu/fpfis/wikis/display/InspireMIG/2017.4+meeting+%2311+2019-07-17)): 
> that the Validator should only check the value of the codeListValue attribute, and not the value of the codeList attribute. 

Based on this, the JRC planned to update the TG as follows:
1. remove all the footnotes and updating the corresponding requirements (if needed)
2. add a recommendation at the beginning of the TG (e.g. in Section 2.1.1) listing the recommended URIs of the ISO code lists

Furthermore, this issue was fixed for MD TG 1.3 (see [v2020.1.1 27/03/2020 - #260 Relax test md-iso.a.5 from MD 1.6 - #432](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2020.1.1)), but never for MD TG 2.0.1.

Could you please check the above-mentioned circumstances and correct them if necessary?
Thanks & regards.

**Comment by fabiovin** [comment]
Dear @alitka,

there were long discussions about this aspect (check of the value of the `codeList` attributes for which the related URL is only mentioned in the TG footnotes) in the past and in the end, it was decided to relax all tests **except** the one for the LanguageCode element (TG Req. C.5 and 1.6) since the related codelist is clearly mentioned inside the requirement (see discussion #52).

The value "http://www.loc.gov/standards/iso639-2/" seems the only usable value since that site is the official site of the ISO 639-2 Registration Authority and thus is the only one authorized by ISO.

> Furthermore, this issue was fixed for MD TG 1.3 (see v2020.1.1 27/03/2020 - #260 Relax test md-iso.a.5 from MD 1.6 - #432), but never for MD TG 2.0.1.

Regarding the fix you mentioned, there is probably an error in the title (Relax test md-iso.a.5 from MD 1.6) since the related issue fixed (#260) is not related to this aspect.

Since there is now in place the process for the governance and release of the TGs (in the dedicated [GitHub repository](https://github.com/INSPIRE-MIF/technical-guidelines)), could you please open an issue proposing the related TG modification?

Thanks,
Fabio

**Comment by heidivanparys** [comment]
> The value "http://www.loc.gov/standards/iso639-2/" seems the only usable value since that site is the official site of the ISO 639-2 Registration Authority and thus is the only one authorized by ISO.

Note that the Library of Congress, the [Registration Authority for ISO 639-2](https://www.iso.org/maintenance_agencies.html#4767), has established a Linked Data Service that

> provides interactive and machine access to the Library's authority and bibliographic metadata, along with commonly-found standards and vocabularies used and/or maintained by the Library of Congress. Each controlled vocabulary list has a resolvable URI, as does each data value within it. 

see also https://id.loc.gov/about/.

The ISO 639-2 code list is available there as well, see http://id.loc.gov/vocabulary/iso639-2, so I would like to argue that this link would be as valid to use as value for the codeList XML attribute as http://www.loc.gov/standards/iso639-2/.

To be discussed in https://github.com/INSPIRE-MIF/technical-guidelines/issues/8.

**Comment by fabiovinci** [comment]
Dear all,

the changes proposed for the MD TG was endorsed and already released, see the related [release changelog](https://github.com/INSPIRE-MIF/technical-guidelines/releases/tag/2022.1).

The checks in the validator about the attribute "codeList" were already relaxed in the past, so no checks are performed on this attribute but only on the attribute "codeListValue".

The only check on the attribute "codeList" is related to the ISO 639-2/B code list required by TG Requirement C.5 and TG Requirement 1.6.

Since the TG Req. C.5 and Req. 1.6 were amended introducing an additional codelist value, I updated the relevant ATSs: [Metadata Language](https://github.com/inspire-eu-validation/metadata/blob/2.0/common/metadata-language-code.md) and [Resource Language](https://github.com/inspire-eu-validation/metadata/blob/2.0/datasets-and-series/resource-language.md).

@arantzaetxebarria, could you please also update the relevant ETSs? Thanks

**Comment by arantzaetxebarria** [comment]
Dear @alitka and @fabiovinci 

The updates in the ETSs for C.5 and 1.6 requirements are in the [staging ](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) environment, could you please confirm that all is working properly? Thanks

Regards

**Comment by fabiovinci** [comment]
Dear @arantzaetxebarria,

thank you for the fix, I tested it and confirm that the solution works correctly.

**Comment by alitka** [comment]
Dear @arantzaetxebarria,
I tested also and everything is working properly.
Best regards.
