### ISSUE TITLE
US dataset: schema validation error (gmlas.b.2: validate XML documents)

### ISSUE THREAD

**Issue by Dnoack49** [INSPIRE-MIF/helpdesk-validator#593]
Hello,

we have mapped several **US-GOVSERV datasets**, for example:

Locations of governmental services in the German state of Brandenburg
https://inspire.brandenburg.de/services/us-govserv_bhvz_wfs?SERVICE=WFS&version=2.0.0&REQUEST=GetFeature&Count=10&typename=us-govserv:GovernmentalService

and

Locations and areas of the police services in the German state of Brandenburg
https://inspire.brandenburg.de/services/us-govserv_polbb_wfs?SERVICE=WFS&version=2.0.0&REQUEST=GetFeature&Count=10&typename=us-govserv:GovernmentalService

**GML-Files** 
[us-govserv.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6923739/us-govserv.zip)

We’ve tested the datasets with the productive as well as the staging instance, with same results. For both (and several other datasets) errors occur regarding the schema validation (_Conformance class: INSPIRE GML application schemas, General requirements / Schema validation / gmlas.b.2: validate XML documents_) 

**Error Report**
[EID3f671f05-ed15-4f0d-8690-afc3a0ee6755](https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID3f671f05-ed15-4f0d-8690-afc3a0ee6755)

**Error-Message**
_XML document 'us-govserv_bhvz_wfs.gml': 7:24: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.opengis.net/gml/3.2":description}'. One of '{"http://www.opengis.net/gml/3.2":name, "http://www.opengis.net/gml/3.2":boundedBy, "http://www.opengis.net/gml/3.2":location, "http://inspire.ec.europa.eu/schemas/us-govserv/4.0":areaOfResponsibility, "http://inspire.ec.europa.eu/schemas/us-govserv/4.0":beginLifespanVersion}' is expected._

![grafik](https://user-images.githubusercontent.com/8046960/128010955-363aa627-4f38-4aa2-a185-f9cde422468a.png)

According to the validator the errors concern 5 attributes. But when looking at the dataset-xml these relevant properties
- description, 
- name, 
- areaOfResponsibility and 
- beginLifespan

were (in our opinion) correctly mapped. The other 2 elements (location and boundedBy) are missing because these are in general _optional_ attributes. Therefore our expectation would be a valid dataset. 

However, we've noticed that if we switch the order of the gml-elements so that <gml:description> is placed before <gml:identifier> in the feature store configuration, like this:

![grafik](https://user-images.githubusercontent.com/8046960/128361724-7082da80-5320-47e4-bc57-c0e9629e336d.png)

the error disappears.

Would you get back to us about why this error occurs. Does it really originate from the harmonized dataset or could it be an error regarding the validator test class?

Kind regards,
Dajana

**Comment by dperezBM** [comment]
Dear @Dnoack49,

Thank you for your message. 
We have been testing your datasets on staging and production instance via URL, and only [us-govserv_polbb](https://inspire.brandenburg.de/services/us-govserv_polbb_wfs?SERVICE=WFS&version=2.0.0&REQUEST=GetFeature&Count=10&typename=us-govserv:GovernmentalService) raised us an error on gmlas.b.2. Otherwise, if we test the .gml files attached to the message above, the error is raised on both reports.

[Reports-URL.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6953269/Reports-URL.zip)
[Reports-file.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6953270/Reports-file.zip)

We have also checked these dataset on Oxygen XML Editor, which comes with an XML Validator included, and the same errors are raised.

![image](https://user-images.githubusercontent.com/33548409/128685553-5f404d24-cf60-44b2-a077-07fd8cbb0f47.png)

We will analyze if your datasets should be validate against the schema and we will come back to you as soon as possible.

Best regards.
David.

**Comment by Dnoack49** [comment]
Dear @dperezBM 

thank you for your response. 
Meanwhile (and before you undertook the tests) we have modified the configuration of **us-govserv_bhvz** .
The error was thrown due to the wrong order of gml-elements. According to the [gml-Schema](http://schemas.opengis.net/gml/3.2.1/gmlBase.xsd)    _gml:description_ which needs to be placed before _gml:identifier_ which agani has to be placed before _gml:name_. 
In [us-govserv_polbb](https://inspire.brandenburg.de/services/us-govserv_polbb_wfs?SERVICE=WFS&version=2.0.0&REQUEST=GetFeature&Count=10&typename=us-govserv:GovernmentalService) it is still in the incorrect order (_gml:description_ appears after _gml:identifier_ and _gml:name_). 
Consequently we have found an explanation to the problem and the issue can be closed.
