### ISSUE TITLE
Validation of MapServer WMS service fails schema validation

### ISSUE THREAD

**Issue by petbod-lm** [INSPIRE-MIF/helpdesk-validator#616]
When validating a WMS service Get capabilities file the schema validation test fails.

URL: https://maps.lantmateriet.se/capabilities/elf/basemap/wms/v1?request=GetCapabilities&service=WMS&version=1.3.0
(See also the attached file ELF_Basemap_WMS_service_XML.txt
[ELF_Basemap_WMS_service_XML.txt](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7243350/ELF_Basemap_WMS_service_XML.txt)
)

Test that fails:
at04-getcapabilities-xml-schema-validation > check-xml-schema-valid

Test message:
Schema not valid: [org.xml.sax.SAXException: Fatal error: org.xml.sax.SAXParseException; lineNumber: 72; columnNumber: 47; cvc-elt.2: The value of {abstract} in the element declaration for '_ExtendedOperation' must be false. Response did not validate against schema 'http://inspire.ec.europa.eu/schemas/inspire_vs/1.0/inspire_vs.xsd'.]

Link to test failure:
https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDfa3012ad-6123-46af-a367-5ee84e60a10f.html#

Looking at the GetCapabilities file (see URL or attched file above) it contains sld:GetLegendGraphic which is a valid substitution Type for the Abstract type _ExtendedOperation 
See the schema definition http://schemas.opengis.net/sld/1.1.0/sld_capabilities.xsd

Why does this test fail with an error regarding the abstract type when a valid substitution type is used?

**Comment by carlospzurita** [comment]
Dear @petbod-lm 

Sorry for the delay on the response to this issue. We are going to check the schemas for this tests and analyze the response of your GetCapabilities.

Kind regards.

**Comment by alitka** [comment]
Just a note: I guess, this related to the issue [#44 View Service WMS: Capabilities XML schema validation fails with SLD operations](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/44)

**Comment by fabiovin** [comment]
Dear @petbod-lm,

the test fails because the validator uses the official schema (https://inspire.ec.europa.eu/schemas/inspire_vs/1.0/inspire_vs.xsd) and not the schemas declared in the schemaLocation element.

The inspire_vs.xsd schema should be modified to include the SLD capabilities schema (http://schemas.opengis.net/sld/1.1.0/sld_capabilities.xsd).

Now that the process of governance and release of application schemas is underway, you can open an issue in the dedicated repository (https://github.com/INSPIRE-MIF/application-schemas). 

You could also integrate the issue with a PullRequest on the involved schema (https://github.com/INSPIRE-MIF/application-schemas/blob/main/schemas/inspire_vs/1.0/inspire_vs.xsd).

Thank you,
Fabio

**Comment by fabiovinci** [comment]
Dear @petbod-lm,

since the proposed change in the schema has been endorsed and released in the [last schema release](https://github.com/INSPIRE-MIF/application-schemas/releases/tag/v2022.2), could you please confirm that the error is no more present and we can close the issue?
Thanks

**Comment by petbod-lm** [comment]
Thank you for getting this update into the latest release.
Services are passing at04-getcapabilities-xml-schema-validation > check-xml-schema-valid.
I will close this issue
