### ISSUE TITLE
I can't understand error at47-getcapabilities-layer-style-legend-url

### ISSUE THREAD

**Issue by pdorio** [INSPIRE-MIF/helpdesk-validator#618]
I try to validate my WMS service, but it fails on: at47-getcapabilities-layer-style-legend-url

https://inspire.ec.europa.eu/validator/test-reports/details.html?id=EID29b2b41d-eda1-43a3-a3fb-fa87fb8feed5

This is my service:
https://demo-geoservices8.civis.bz.it/geoserver/p_bz-Inspire/ows?service=wms&version=1.3.0&request=GetCapabilities&language=eng

Each style contains LegendUrl and the URL is valid

Can someone help me?
Regards

**Comment by pdorio** [comment]
can someone help me?

**Comment by carlospzurita** [comment]
Dear @pdorio 

Sorry for the delay on our response. We are going to check the xPath of this ETS  and its definition on the ATS, and see if the GetCapabilities document is compliant with the Abstract Test Suite in order to fix the implementation.

KInd regards.

**Comment by dperezBM** [comment]
Dear @pdorio,

We updated our [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). We added a more specific error message to help users to have a better understanding of what is not compliant. Could you please provide us feedback about this?

Thank you and best regards.

**Comment by grigoriouelena** [comment]
Hello everyone,

I used the staging instance to test a WMS. The aformentioned test fails for my resource also, because the /Layer/Style/LegendURL/Format is not 'application/xml', as expected by the validator, but image/png. 

Looking for more information on this requirement, I see in the test method that the test should check if the legend is a valid image and not a specific format.

I am wondering whether the test is too strict, since I was not able to find any sort of requirement for a specific format of the legend graphic.

My resource is: http://beta.geoportal.ypen.gr/geoserver/aqd-wms/ows?service=WMS&version=1.3.0&request=GetCapabilities
and the legend graphic is here: http://beta.geoportal.ypen.gr/geoserver/wms?REQUEST=GetLegendGraphic&VERSION=1.3.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=aqd-wms:AM.AirQualityManagementZone

Thank you in advance,

Elena

**Comment by pdorio** [comment]
@dperezBM I tested the WMS again and I still don't understand the problem

[Here](https://geoservices8.civis.bz.it/geoserver/p_bz-Inspire/ows?version=1.3.0&service=WMS&request=GetCapabilities) my WMS getcapabilities

[Here ](https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID827d6b09-7660-4273-a4ed-4ba3cbf0392a) my report result

i obtain the following error at the same point: at47-getcapabilities-layer-style-legend:

```import de.interactive_instruments.etf.suim.TranslatableAssertionError;
def tc = testRunner.testCase.testSuite.project.testSuites["GetCapabilities_Operation"].testCases["initial-testcase"];
def response = tc.getTestStepByName("http-request").getPropertyValue("Response");
def capabilities = new XmlSlurper(false, true).parseText(response);

testRunner.testCase.setPropertyValue('language', '');
testRunner.testCase.setPropertyValue('legendEndpoint', '');
def defaultLanguage = capabilities.Capability.ExtendedCapabilities.SupportedLanguages.DefaultLanguage.Language.toString();
def supportedLanguages = [];
supportedLanguages << capabilities.Capability.ExtendedCapabilities.SupportedLanguages.DefaultLanguage.Language;
for (x in capabilities.Capability.ExtendedCapabilities.SupportedLanguages.SupportedLanguage){
	supportedLanguages << x.Language;
}

def tsGetCapabilities = testRunner.testCase.testSuite.project.testSuites["GetCapabilities_Operation"].testCases["at47-getcapabilities-layer-style-legend-url"].getTestStepByName('http-getcapabilities-specific-language');
def tsGetLegend = testRunner.testCase.testSuite.project.testSuites["GetCapabilities_Operation"].testCases["at47-getcapabilities-layer-style-legend-url"].getTestStepByName('http-getlegend');

for (x in supportedLanguages){
	testRunner.testCase.setPropertyValue('language', x.toString());
	tsGetCapabilities.setDisabled(false);
	tsGetCapabilities.run(testRunner, context);
	capabilitiesLanguaged = new XmlSlurper(false, true).parseText(tsGetCapabilities.getPropertyValue("Response"));

	def layers = capabilities.Capability.depthFirst().findAll{it.name()=='Layer'};
	layers.each{layer ->
		def styles = layer.Style;
		styles.each{style ->
			if(style.LegendURL.size() == 1){
				if(style.LegendURL.OnlineResource.size() != 1){
					String[] assertParams = ['element', 'Layer/Style/LegendURL/OnlineResource'];
					throw new TranslatableAssertionError('TR.multiplicityShallBeOne', assertParams);
				}
				if(style.LegendURL.OnlineResource.@'xlink:href'.toString().length() != 0){
					testRunner.testCase.setPropertyValue('legendEndpoint', style.LegendURL.OnlineResource.@'xlink:href'.toString());
					tsGetLegend.setDisabled(false);
					tsGetLegend.run(testRunner, context);
					if(tsGetLegend.testRequest.response.responseHeaders.get('Content-Type')[0] != style.LegendURL.Format.toString()){
						throw new TranslatableAssertionError("TR.invalidLegendFormat");
					}
				}
				else{
					String[] assertParams = ['element', 'Layer/Style/LegendURL/OnlineResource/@xlink:href'];
					throw new TranslatableAssertionError('TR.valueShallNotBeEmpty', assertParams);
				}
			}
			else if(style.LegendURL.size() != 0){
				String[] assertParams = ['element', 'Layer/Style/LegendURL'];
				throw new TranslatableAssertionError('TR.multiplicityShallBeZeroOrOne', assertParams);
			}
		}
	}
}
tsGetCapabilities.setDisabled(true);
tsGetLegend.setDi
```

**Comment by fabiovinci** [comment]
Dear @pdorio,

looking at the WMS of your last comment, it seems that in the LegendURL elements the WMS is missing.

For instance, this URL (https://geoservices8.civis.bz.it/geoserver/p_bz-Inspire/ows?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=AD.Address) generates the following exception:

```xml
<ows:Exception exceptionCode="MissingParameterValue" locator="version">
<ows:ExceptionText>Could not determine version</ows:ExceptionText>
</ows:Exception>
```
If you add the parameter `version=1.3`, the response is OK:

![image](https://user-images.githubusercontent.com/22212406/159032544-77d54c3f-5a08-45f6-bcf3-75ff69ebde43.png)

This generates the error in the "_at47-getcapabilities-layer-style-legend_" test.

Could you please verify your implementation and testing again?

**Comment by fabiovinci** [comment]
Dear @pdorio,

please note that the `version` parameter is not mandatory for a _GetLegendGraphic_ request, but your server should reply considering the default one (e.g. https://msdi2.data.gov.mt/deegree/services/wms?request=GetLegendGraphic&service=WMS&layer=AM.StrategicLandUseDesignations&style=AM.StrategicLandUseDesignations&format=image/png).

We will modify the error messagge in order to better clarify that the response of the _GetLegendGraphic_ request generates an exception.

**Comment by pdorio** [comment]
@fabiovinci thank you for modifying the error message.

I know that the problem is generated by an issue of the software:
https://osgeo-org.atlassian.net/jira/core/projects/GEOS/issues/GEOS-10336

**Comment by arantzaetxebarria** [comment]
Dear @fabiovinci 

We have modified the error message and it is ready in staging environment where you can check it.

Note: With the changes made during this issue, this one [703 ](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/703) has also been solved.

Regards

**Comment by fabiovinci** [comment]
Deat @arantzaetxebarria,

the fix is ok for me.

@pdorio, Now the error message is "_The legend format is invalid. The validator is expecting 'image/png', but the defined legend format is 'application/xml'. Please, review your code and try again._".

We think it is more understandable now, you confirm?

**Comment by fabiovinci** [comment]
Dear @pdorio,

Do you confirm that the error message is clearer now?
Thank you
