### ISSUE TITLE
Validation error on Dataset Conformity

### ISSUE THREAD

**Issue by alitka** [INSPIRE-MIF/helpdesk-validator#63]
Testing a metadata record with the "new TG 2.0 tests" causes an error concerning the dataset conformity

- [x] a description of the steps to reproduce your issue 
1. go to http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp and
    select "Conformance Class 1: INSPIRE data sets and data set series baseline metadata" (under Metadata (TG versio 2.0) - BETA)
2. start the test and upload an externale xml-file
[dataset_DE_ConformityError.zip](https://github.com/inspire-eu-validation/community/files/3257387/dataset_DE_ConformityError.zip)

3. the error message returned for the test "Distribution > md datasets-and-series 1.10: Dataset Confomity"
`System error in the Executable Test Suite. Please contact a system administrator. Error information:
[err:XPTY0004] Item expected, sequence found: (text {"VERORDNUNG (EU) Nr. 1253.... 
(912/3)`

- [x] the browser and version used
`Firefox Quantum 66.0.5 (64-Bit)`

- [x] a screenshot illustrating the problem
![errormessageDatasetConformity](https://user-images.githubusercontent.com/29542183/58960085-b4412580-87a6-11e9-8344-8ea101237f4b.PNG)

- [x] the Test Report (ideally as an attachment to the issue)
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID4b0d6385-620f-4866-b4af-a322389552ff.html

- [x] the name of the Test that failed or better: change the `Level of Detail`
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID4b0d6385-620f-4866-b4af-a322389552ff.html?lang=de#EID19fd6dd9-87cc-4075-b019-03b57750ab1b

The test claims an error concerning the additional conformity statement
- VERORDNUNG (EU) Nr. 1253/2013 DER KOMMISSION vom 21. Oktober 2013 zur Änderung der Verordnung (EU) Nr. 1089/2010 zur Durchführung der Richtlinie 2007/2/EG hinsichtlich der Interoperabilität von Geodatensätzen und -diensten 
and
- VERORDNUNG (EU) Nr. 102/2011 DER KOMMISSION vom 4. Februar 2011 zur Änderung der Verordnung (EU) Nr. 1089/2010 zur Durchführung der Richtlinie 2007/2/EG des Europäischen Parlaments und des Rates hinsichtlich der Interoperabilität von Geodatensätzen und -diensten

Related to TG Requirement C.20: metadata/2.0/req/common/conformity, there is no limitation of the gmd:DQ_ConformanceResult elements: "The multiplicity of this element is 1..*." and taking account of TG Requirement C.21: metadata/2.0/req/common/conformity-specification, each gmd:report/gmd:DQ_DomainConsistency/gmd:result/gmd:DQ_ConformanceResult element include a gmd:specification/gmd:CI_Citation element (with the official title and the date of publication of the document).

**Comment by danielnavarrogeo** [comment]
Dear @alitka 

There was a bug that it is now fixed in staging environemnt. You can try in:
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/

However your xml still does not pass the test because the text provided is not valid. At least one of the conformity declarations shall be one of the regulation 1089/2010. With the specific text in any of the available languages of the regulation:
https://publications.europa.eu/en/publication-detail/-/publication/6c9b0d4b-831f-47fe-b551-ac13604d9797/language-en

For instance, in Spanish:

> REGLAMENTO (UE) N o 1089/2010 DE LA COMISIÓN de 23 de noviembre de 2010 por el que se aplica la Directiva 2007/2/CE del Parlamento Europeo y del Consejo en lo que se refiere a la interoperabilidad de los conjuntos y los servicios de datos espaciales

Or in German:

> VERORDNUNG (EG) Nr. 1089/2010 der Kommission vom 23. November 2010 zur Durchführung der Richtlinie 2007/2/EG des Europäischen Parlaments und des Rates hinsichtlich der Interoperabilität von Geodatensätzen und -diensten

Here is the link to the ATS:
https://github.com/inspire-eu-validation/metadata/blob/master/metadata%20TG%202.0/datasets-and-series/conformity.md

Attached is a modified version of your xml that passes the test.

Regards

[dataset_DE_ConformityError_modified.zip](https://github.com/inspire-eu-validation/community/files/3358385/dataset_DE_ConformityError_modified.zip)

**Comment by josemasensio** [comment]
Dear @alitka,

Does this solution work?

Regards.

**Comment by alitka** [comment]
Dear @bilbomaticaue,

Sorry for my late response. I have tested the xml-file again and everything is working properly. Furthermore thanks for mentioning the spelling mistake, I didn't notice the missing "G" in the regulation text "VERORDNUNG (E) Nr. 1089/2010 DER KOMMISSION ..." 

Best regards.
