### ISSUE TITLE
Errors in OGC WFS 2.0 Conformance Test Suite

### ISSUE THREAD

**Issue by Claudia-WE** [INSPIRE-MIF/helpdesk-validator#658]
To help us investigate the issue, you may want to include:
I tried to due an INSPIRE Validation Test on the following WFS Download Service: **https://haleconnect.com/ows/services/org.923.c06ef455-1a6b-4259-a31d-b59bb8c7bf09_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0**

And  received a set of error messages that I can't understand: **http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EIDa2e15dc8-b218-493c-9ef9-60d372a68b8a** (in the staging version as well as in the production version)

Could you please feedback which are platform related and which are WFS related ?

**Comment by dperezBM** [comment]
Dear @Claudia-WE,

Thank you for your message. We have analysed your report. 

In one hand, for the issue from 'Conformance class: Download Service - Pre-defined WFS' > 'Capabilities' > 'Extended Capabilities' > 'GetCapabilities' > 'xsi:schemaLocation contains the INSPIRE Download Services schema' the problem is that as explained on the [corresponding ATS](https://github.com/inspire-eu-validation/download-wfs/blob/3.1/wfs-pre-defined/extended-capabilities.md), the xsi:schemaLocation must contain 'http://inspire.ec.europa.eu/schemas/inspire_dls/1.0/inspire_dls.xsd' URL. Please, update your service in order to correct this issue.

On the other hand, the errors from the 'WFS 2.0 (OGC 09-025r2/ISO 19142) Conformance Test Suite',  are directly extracted from the [OGC Validator](https://cite.opengeospatial.org/teamengine/). Maybe you can find more information on the [corresponding repository](https://github.com/opengeospatial/ets-wfs20/issues).
Please, let us know if you have any other questions.

Best regards.

**Comment by Claudia-WE** [comment]
Thanks for the feedback.
I opened the following issue https://github.com/opengeospatial/ets-wfs20/issues/211 related to the Spatial Filter problems

**Comment by fabiovinci** [comment]
Dear @Claudia-WE,

since the issue opened in the external repository and linked to this issue is closed, we close also this one.

Please feel free to reopen the issue or to open a new one if the problem persists.
