### ISSUE TITLE
"An error has occured" when trying to validate WFS

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#670]
- [ ] a description of the steps to reproduce your issue
Try to test [this WFS](https://haleconnect.com/ows/services/org.789.ffa9f2a0-54d8-4f18-961c-196230496a0a_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0) with the INSPIRE Validator
When hitting "Start test", a red error badge with the message "An error has occured" is being displayed and the test is not executed.
- [ ] the browser and version used
Firefox 91.3.0esr for Windows (behavior is the same with Chrome)
- [ ] a screenshot illustrating the problem
![grafik](https://user-images.githubusercontent.com/34163838/144858495-4f9a3336-53f9-44ac-a71d-ef91435d07ca.png)
- [ ] the Test Report (ideally as an attachment to the issue)
No test report as test won't stop
- [ ] the name of the Test that failed
Download Service - WFS - Direct WFS
- [ ] the URL of your service / the file you have uploaded or referenced (as
an attachment).
https://haleconnect.com/ows/services/org.789.ffa9f2a0-54d8-4f18-961c-196230496a0a_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

**Comment by JohannaOtt** [comment]
Jus happened again on the production instance for a [different WFS](https://haleconnect.com/ows/services/org.892.5674b355-41ef-41ca-b465-d0c37428c1dd_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0)

**Comment by JohannaOtt** [comment]
Happening again right now when trying to test https://haleconnect.com/ows/services/org.789.7c19845a-d2c0-45df-b9f6-e5438ab0c505_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

**Comment by jenriquesoriano** [comment]
Dear @JohannaOtt ,

thank you for your input.

Since some changes have been introduced in the past days to prevent this and other issues from happening, it should have been solved (also related to #668).

We have tested the provided services in order to check it. Please find the results below:

- https://haleconnect.com/ows/services/org.789.ffa9f2a0-54d8-4f18-961c-196230496a0a_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0 and obtained the corresponding test report: 
https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID5dbcc549-a79f-415f-90be-fbb9ca76144c
- https://haleconnect.com/ows/services/org.892.5674b355-41ef-41ca-b465-d0c37428c1dd_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0 , obtaining https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID08a324e6-40b5-4bba-9a92-fddcbe766567
- https://haleconnect.com/ows/services/org.789.7c19845a-d2c0-45df-b9f6-e5438ab0c505_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0 , with this test report https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID467022d5-fa68-4077-ac74-05bce17a1ea0

@JohannaOtt  We kindly ask you to confirm if this issue is solved accordingly.

Best regards,

**Comment by JohannaOtt** [comment]
@jenriquesoriano Thank you for the upate.
I can confirm that at least for two of the services, the test is now running (the third one is still in progress and seems to take longer, but that also means that it got further than it used to). So I will close the ticket now.
Concerning the reports you linked, I cannot open them - the page is loading for a long time but does not display any results. So you might want to check if there is anything wrong with the tests stored in the system.

**Comment by jenriquesoriano** [comment]
Dear @JohannaOtt 

thanks for your feedback and please excuse the broken links. 
After posting them, we have executed some internal maintenance operations which have resulted in the full restart of the tests reports stored, so they are not present in the instance anymore.
In any case, if you find an issue, please feel free to report it again.

Best regards,
