### ISSUE TITLE
files >9mb not uploading

### ISSUE THREAD

**Issue by xiv21** [INSPIRE-MIF/helpdesk-validator#677]
Hi, I'm using the online validator (file size limit 50mb) to validate a batch of files that have all been generated using the same method. All files smaller than 9mb have uploaded successfully and produced reports while all files 12-26mb in size have failed to upload (Error Code - 0). The Staging version gives Error Code 503 - Service Unavailable. The same errors occurred at 21:45 GMT on Sunday evening.

**Comment by JohannaOtt** [comment]
@xiv21 I think this is addressed in https://github.com/INSPIRE-MIF/helpdesk-validator/issues/668

**Comment by jenriquesoriano** [comment]
Dear @xiv21 , @JohannaOtt ,

thanks for your contribution and feedback.

As the issue seems to be related with #668 (ready for testing), it should be already solved.

@xiv21  , we kindly ask you to test it again and provide us with feedback whether the test is successfull or not.

In case it is not successful, if possible, we kindly ask you to provide us with more detailed information in order to reproduce the reported issue.
In case it may help, please find a link on how to [report a problem](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/new?template=problem.md), so we may have enough information to check and solve it.

Kind regards,

**Comment by xiv21** [comment]
Hi, this issue has been resolved, thanks.
