### ISSUE TITLE
INSPIRE View Service Validation - Legend Url

### ISSUE THREAD

**Issue by grigoriouelena** [INSPIRE-MIF/helpdesk-validator#680]
I am trying to provide an INSPIRE compliant view service using geoserver 2.20.1.
My service is: http://beta.geoportal.ypen.gr/geoserver/aqd-wms/ows?service=WMS&version=1.3.0&request=GetCapabilities

When testing it with a national instance of the validator, I get an error for test a47-getcapabilities-layer-style-legend-url (validation report here: 
[WMS_Validation.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7760954/WMS_Validation.zip)

I tried to test the same resource with the staging instance of the validator. The same test fails and I get the following message:
![image](https://user-images.githubusercontent.com/55238073/147056767-cf13f7b2-1741-4d18-b9c0-f4ae3a7783f9.png)

Trying to find more information on the issue, I see [here](https://github.com/inspire-eu-validation/view-service/blob/review-ats-tg_3.11/iso-19128/at47-getcapabilities-layer-style-legend-url.md) that the requirement is that the response of the GetLegendGraphic request to the WMS should be a valid image. My legend graphic is an image/png format, which is a valid image format. 

If I changed the legend format to application/xml, as indicated by the validation report, the capabilities response does not contain the LegendURL element and the test passes, since this element is not mandatory.

Could you please provide me with some guidance on how to provide a valid and correct legend information?

Thank you in advance.

Elena

**Comment by pawelsoczewski** [comment]
Hi Elena,
Despite prior discussion, in my opinion the cause of this issue is missing version parameter in GetLegend request of service capabilities. In the test, the validator uses URL of GetLegend from Capabilities and it returns XML response with error. According to the test method the validator is expecting a valid image.

<img width="785" alt="Zrzut ekranu 2021-12-22 o 19 37 31" src="https://user-images.githubusercontent.com/44895671/147140225-898eb8b8-84bf-4ec3-9c47-5f077efafea9.png">

**Comment by grigoriouelena** [comment]
Hey Pawel,

Thanks for the input! The problem is probably the one you describe, indeed.

The error message from the validator is a bit confusing though.

It seems that in order to use geoserver to provide OGC or INSPIRE services, one has to make some developer's work to fix things like that.

I am closing the issue.
