### ISSUE TITLE
Metadata dataset: The attribute code list is not correct

### ISSUE THREAD

**Issue by idevisser** [INSPIRE-MIF/helpdesk-validator#69]
I got on several metadata elements the unexpected error The code list attribute is not correct. The attribute code list shall be 'http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#XXXXX'

TG Requirement C.3: metadata/2.0/req/common/code-list-value
The code list value shall be encoded using the codeListValue attribute of the relevant ISO 19139 element. The value shall be the identifier of the code list value, as defined in the name column of the tables in [ISO 19115], Annex B.

This requirement requires only a correct value 

As the TG metadata further describes;

Both the value of the codeList attribute (a URL that references a code list definition within a register or a code list catalogue) and the textual content of the ISO 19139 element are purely informative. The codeList value may e.g. point to the code list dictionary in the ISO 19139 repository at http://standards.iso.org/iso/19139/resources/codelist/, and if a text is provided, it may contain the translation of the code list value in the language of the metadata.

The validation check  on the attribute codelist looks like not correct

**Comment by josemasensio** [comment]
Dear @idevisser,

Thank you for your message. We have checked the TG and it seems that you are right.

Could you send us a metadata example please? We need it to test on the validator and check the error.

Best regards.

**Comment by idevisser** [comment]
Hello 

Herby the complete metadata example file, used by all issues I reported yesterday.

[test dataset.zip](https://github.com/inspire-eu-validation/community/files/3349064/test.dataset.zip)

Best regards Ine

**Comment by idevisser** [comment]
Hi,

Same problem with the service metadata, Is it necessary to make a separate issue for that?

Best regards Ine

**Comment by inakidiazdecerio** [comment]
@idevisser after reviewing the ATS of [Metadata Point of Contact](https://github.com/inspire-eu-validation/metadata/blob/2.0/metadata%20TG%202.0/common/md-point-of-contact.md) and the [inspire-tg-metadata-iso19139-2.0.1](https://inspire.ec.europa.eu/sites/default/files/documents/metadata/inspire-tg-metadata-iso19139-2.0.1.pdf) (page 34), in both it is said that 'the attribute codeList of the Role node is "http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_RoleCode"'.

So you should change the values of the codeList attributes in gmd:CI_RoleCode elements to solve the error, "http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_RoleCode" instead of "http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode".

Best regards.

**Comment by josemasensio** [comment]
@idevisser after reviewing the ATS of [Metadata Point of Contact](https://github.com/inspire-eu-validation/metadata/blob/2.0/common/md-point-of-contact.md) and the [inspire-tg-metadata-iso19139-2.0.1](https://inspire.ec.europa.eu/sites/default/files/documents/metadata/inspire-tg-metadata-iso19139-2.0.1.pdf) (page 34), in both it is said that 'the attribute codeList of the Role node is "http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_RoleCode"'.

So you should change the values of the codeList attributes in gmd:CI_RoleCode elements to solve the error, "http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_RoleCode" instead of "http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode".

Best regards.

**Comment by idevisser** [comment]
Can you tell me in which requirement you find this? I can't find it (on page 34)

**Comment by josemasensio** [comment]
I attach an image.

![RoleCode](https://user-images.githubusercontent.com/50206416/60576129-188edf00-9d7d-11e9-9939-f8bf66a14828.PNG)

**Comment by idevisser** [comment]
ah, I see it's in the foodnotes, but this is not in line with wat is written in chapter 2.1.1 Encoding of code list values of the TG.
There is a clear statement that "Both the value of the codeList attribute (a URL that references a code list definition within a register or a code list catalogue) and the textual content of the ISO 19139 element are purely informative."

So I can't agree on a test that refuse  the same codelists, published by international standardisation organisations on another location.

**Comment by michellutz** [comment]
I think this issue should be discussed in the 2017.4 sub-group.

**Comment by AntoRot** [comment]
A similar discussion (with regard to language code) was addressed in the issue #52. I agree that the test should only check if the codeListValue is one of the values coming from the ISO Standard (as code lists and their values provided in ISO Standard 19115 are normative, as we can read in the section 6.7 in that Standard) and no check should be done on codelist attribute, except for language metadata element for the reasons I explained in the mentioned issue #52. 
Consequently the footnotes should be reworded to be aligned to the TG section 2.1.1.

**Comment by LauraAlemany** [comment]
I agree with Antonio, 

The footnotes should be reworded to be aligned to the TG section 2.1.1. 

Best regards,
Laura

**Comment by MarcoMinghini** [comment]
**2017.4 meeting 2019-07-17**

- It is agreed that the Validator should only check the value of the `codeListValue `attribute, and not the value of the `codeList `attribute.
- JRC is in contact with ISO, but there seems to be some confusion also on their side on what is the recommended authoritative URI.
- [ ] JRC to draft a change proposal to the TG to:
  - remove all the footnotes and updating the corresponding requirements (if needed)
  - add a recommendation at the beginning of the TG (e.g. in Section 2.1.1) listing the recommended URIs of the ISO code lists
- a similar solution might be done for the case of issue #52 about the language code list

**Comment by josemasensio** [comment]
Dear @idevisser,

We uploaded the solution to [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). Can you try here and give your feedback?

Regards.

**Comment by josemasensio** [comment]
Afert some internal tests, we checked that everything is working fine, so we will mark as solved this issue.

Regards.

**Comment by danielnavarrogeo** [comment]
Now the codeList is only checked in 'C.5 Language Code' and '1.6 Resource Language' tests. https://github.com/inspire-eu-validation/community/issues/131
