### ISSUE TITLE
New IDs for "WFS 2.0 Conformance Test Suite" after Validator Release

### ISSUE THREAD

**Issue by Dnoack49** [INSPIRE-MIF/helpdesk-validator#692]
Dear validator team,

after the recent release v2022.0 there were changes in the **WFS 2.0 (OGC 09-025r2/ISO 19142) Conformance Test Suite** output. We have noticed that all IDs of the _Testsuite_, _Testmodule_, _Testcase_ , _Teststep_ etc. are different from prior the Update. Here is a comparison between before (left) and after (right) the last release:
![grafik](https://user-images.githubusercontent.com/8046960/150548992-ceb2eb32-9fa2-4d30-a813-86cfa98ee4fe.png)

We are using these IDs in a workflow, therefore we have 2 questions:
- Will these change in the future, every time there is a new version of the validator or could they possibly remain constant?
- Is there any equivalent ets-repositry-file these IDs are listed (as it is for example the case for the Test Suite '[Conformance Class: Download Service - Direct WFS](https://github.com/inspire-eu-validation/ets-repository/blob/master/service/ds-wfs-direct-soapui-project.xml)')?

Kind regards

**Comment by jenriquesoriano** [comment]
Dear @Dnoack49  ,

thank you for your feedback on the deployed version.

The EIDs are generated by the ETF and depend on the test-driver compilation, i.e. they will change if changes are introduced in the test-drivers where a new compilation is required.
Since changes were introduced in the etf-tetd test driver (related to a detected bug in the dependency between WFS Direct and the OGC TEAM engine test and the OGC API-Features), these EIDs have been modified and, therefore, all those tests that, like WFS 2.0, depend on them.
In this sense, since no immediate developments are planned for the time being, there should be no changes in the existing EIDs as of release v2022.0.

With regard to the list of EIDs, you can locate the TestSuites IDs at:
http://inspire.ec.europa.eu/validator/v2/ExecutableTestSuites

We hope we have clarified your question.

Best regards

**Comment by Dnoack49** [comment]
Dear @jenriquesoriano ,

alright, thank you very much for the explanation.
