### ISSUE TITLE
Metadata dataset: limitations on public access (C.17)

### ISSUE THREAD

**Issue by idevisser** [INSPIRE-MIF/helpdesk-validator#71]
I got an unexpected error on the limitations on public access, md common requiremnt C.17

Comment: 
The required value  of the INSPIRE code list for LimitationsOnPublicAccess is given
all  limitations on public access are described in one gmd:MD_LegalConstraints

Message
The metadata record set has 1 record(s) with errors for this assertion.
XML document 'test dataset.xml', record 'C2DFBDBC-5092-11E0-BA8E-B62DE0D72085': 
No valid resource constraint limitations is provided for this record.
Limitations on public access (or lack of such limitations) for the described resource shall be described using exactly one gmd:resourceConstraints/gmd:MD_LegalConstraints element. This element shall not be the same one as used for describing conditions applying to access and use.
A metadata record must have a gmd:accessConstraints element with a gmd:MD_RestrictionCode element with code list value "otherRestrictions".
Additionally, at least one instance of gmd:otherConstraints shall be given describing the actual limitations.
If limitations apply, the gmd:otherConstraints shall include a gmx:Anchor element pointing to one of the values from the INSPIRE code list for LimitationsOnPublicAccess
If no limitations apply, the gmd:otherConstraints shall include a gmx:Anchor element pointing to the value "noLimitations" in the INSPIRE code list LimitationsOnPublicAccess (http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations)

XML sniplet:
			<gmd:resourceConstraints>
				<gmd:MD_Constraints>
					<gmd:useLimitation>
						<gco:CharacterString>Gebruiksbeperkingen (*), Toepassingen waarvoor de data niet geschikt is.</gco:CharacterString>
					</gmd:useLimitation>					
				</gmd:MD_Constraints>
			</gmd:resourceConstraints>
			
			<gmd:resourceConstraints>
				<gmd:MD_LegalConstraints>
					<gmd:accessConstraints>
						<gmd:MD_RestrictionCode codeListValue="otherRestrictions" codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode"/>
					</gmd:accessConstraints>   
					<gmd:otherConstraints>
						<gmx:Anchor xlink:href="https://creativecommons.org/publicdomain/mark/*/deed.nl">Geen beperkingen</gmx:Anchor>
					</gmd:otherConstraints>
					
					<gmd:otherConstraints>
						<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/noConditionsApply">geen voorwaarden</gmx:Anchor>
						</gmd:otherConstraints>
				</gmd:MD_LegalConstraints>
			</gmd:resourceConstraints>
			
					
			 
			<gmd:resourceConstraints>
				<gmd:MD_LegalConstraints>
					<gmd:accessConstraints>
						<gmd:MD_RestrictionCode codeListValue="otherRestrictions" codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode"/>
			
		</gmd:accessConstraints>
					<gmd:otherConstraints>
						<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations">geen beperkingen</gmx:Anchor>
					</gmd:otherConstraints>
				</gmd:MD_LegalConstraints>
			</gmd:resourceConstraints>

**Comment by fantamir** [comment]
This problem is analogous to the **Metadata dataset: conditions for access and use (C.18) #72**

Metadata item 8.2 „Limitations on public access“ currently allows following URI only:.
http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations
http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/INSPIRE_Directive_Article13_1a
…
http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/INSPIRE_Directive_Article13_1h

**Modification of the validator code to allow free URI in the Anchor element is suggested** (see comment in https://github.com/inspire-eu-validation/community/issues/72 for details).

**Comment by josemasensio** [comment]
Dear @idevisser,

Please, see the ATS of [Limitations on Public Access](https://github.com/inspire-eu-validation/metadata/blob/2.0/metadata%20TG%202.0/common/limitations-on-public-access.md) or the page 46 of the [TG](https://inspire.ec.europa.eu/sites/default/files/documents/metadata/inspire-tg-metadata-iso19139-2.0.1.pdf).

Your metadata must pass all validations. In the provided metadata the following checks are not success:

- The Restriction Code element has attribute codeList that starts with "http://standards.iso.org/iso/19139/resources/gmxCodelists.xml"
- One Anchor element which xlink:href attribute is a URL starting with "http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/"

Best regards.

**Comment by idevisser** [comment]
Dear 

The anchor element with  xlink:href containing http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations is available in the XML.

Why is it not passing the test (except the codelist attribute issue)?

best regards Ine

**Comment by josemasensio** [comment]
Dear @idevisser,

Sorry, you are right. The Anchor element is correct.

We have review the test code and the error appears because the codeList attribute of Restriction Code element has not a correct value. The correct values are:

- http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode
- http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodelists.xml#MD_RestrictionCode
- http://schemas.isotc211.org/19139/resources/gmxCodelists.xml#MD_RestrictionCode
- https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode
- https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodelists.xml#MD_RestrictionCode
- https://schemas.isotc211.org/19139/resources/gmxCodelists.xml#MD_RestrictionCode

Best regards.

**Comment by idevisser** [comment]
Dear @
Ok, it's good news that more locations of the codlist are accepted, but why is 
https://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode
not accepted? This is published by an international standardisation body and has the scope Codelists for description of metadata datasets compliant with ISO/TC 211 19115:2003 and 19139

Best regards Ine

**Comment by josemasensio** [comment]
@michellutz maybe this issue should be discussed in the 2017.4 sub-group.

**Comment by AntoRot** [comment]
See my comment in the issue #69

**Comment by MarcoMinghini** [comment]
**2017.4 meeting 2019-07-17**

- The solution regarding the ISO code list is the one agreed in #69, i.e. the Validator should only check the value of the `codeListValue `attribute, and not the value of the `codeList `attribute.
- Regarding the use of `Anchor `with a URI different than those allowed by the TG, it is agreed that the Validator should check that there is at least one instance of the `gmd:otherConstraints` with either an `Anchor `pointing to a URI or a `gco:CharacterString`.
- the same issue is discussed in #72. 
- [ ] JRC to change the test, accordingly.

**Comment by josemasensio** [comment]
Dear @idevisser,

We relaxed the test so now you will have not problems with the codeList attribute.

Regards.

**Comment by josemasensio** [comment]
Dear @idevisser,

Does this solution worked?

Regards.

**Comment by josemasensio** [comment]
Afert some internal tests, we checked that everything is working fine, so we will mark as solved this issue.

Regards.
