### ISSUE TITLE
Statistical Units Vector - geometry test for GM_MultiSurface is too strict

### ISSUE THREAD

**Issue by ulbrichtd** [INSPIRE-MIF/helpdesk-validator#714]
Hi,

currently the validation of GML in the data theme Statistical Unit (Vector) fails when "gml:Surface" is used to characterize the area, i.e. the test "su-vector-as.b.2: Area Statistical Units" fails with the message "Check that the reference geometry of an area statistical units is a GM_MultiSurface.".

According to the specification for Statistical Unit ( https://inspire.ec.europa.eu/documents/Data_Specifications/INSPIRE_DataSpecification_SU_v3.0.pdf ) the UML class diagram for "Vector package" (figure 7 in section 5.3.1.2.3) suggests that GM_Object is allowed to describe the geometry.

I think the validation test is to strict and should allow gml:Surface.

Link to the data file: https://fbinter.stadt-berlin.de/fb/atom/SU/SU_BLK.zip
Link to the test report: [SU_BLK_2021_06_29_Test.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8133486/SU_BLK_2021_06_29_Test.zip)

Best regards and many thanks
Damian

**Comment by fabiovinci** [comment]
Dear @ulbrichtd,

we will investigate the check performed by the validator since your encoding should be ok.

As you mentioned the dataType of the `geometry `element is `GM_Object`, there is a specific constraint for the spatial object type `VectorStatisticalUnit` which states: "_Vector statistical units with a reference geometry instance of GM_MultiSurface must be instances of the specialised class AreaStatisticalUnit._", but in your case, a "gml:Surface" geometry should be valid for the spatial object type `AreaStatisticalUnit`.

**Comment by fabiovinci** [comment]
Dear @ulbrichtd,

I had a deep look at the ATS and the related constraints defined by the IR 1089 and its amendment [Commission Regulation (EU) No 1253/2013](https://eur-lex.europa.eu/eli/reg/2013/1253) defines a constraint about the geometry type of the AreaStatisticalUnit feature type.
See below:

![image](https://user-images.githubusercontent.com/22212406/157081602-b977a89a-03f0-46bc-ba64-7044e0fc2638.png)

The test in the validator reflects this constraint, although it is probably not well formulated since it is a constraint but makes use of the verb "should", which is, in general, used for recommendations.

Moreover, this constraint is not present in either the TG or the UML.

I think we can move the discussion to the [TG repository](https://github.com/INSPIRE-MIF/technical-guidelines), opening an issue for the inclusion of the constraint in the TG and asking feedback about its implementation, i.e. if it can be considered as a recommendation.

Could you please open the relevant issue in the TG repository?

**Comment by fabiovinci** [comment]
According to the conclusions of the related TG issue, the [related ATS](https://github.com/inspire-eu-validation/data-su/blob/master/su-vector-as/constraints.md) has been modified and the test will be relaxed in the Validator.

**Comment by arantzaetxebarria** [comment]
Dear @ulbrichtd 

We have done the changes in the ETS in order to relax the test, now you can test it in [staging ](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html)environment. Let us know if all is correct, thanks in advance.

Regards,

Arantza

**Comment by ulbrichtd** [comment]
Thank you for the fix. The validator in the staging area accepts now files with "su-vector:geometry/gml:Surface" and "su-vector:geometry/gml:MultiSurface".

Best regards,
Damian

**Comment by arantzaetxebarria** [comment]
Dear @ulbrichtd 

The issue will remain open until the next release 2022.2 when the changes will be put into the production environment.

Regards
