### ISSUE TITLE
Metadata dataset: conditions for access and use (C.18)

### ISSUE THREAD

**Issue by idevisser** [INSPIRE-MIF/helpdesk-validator#72]
I got an unexpected error on the limitations on access and use, md common requirement C.18

Comment:
The required value of the INSPIRE code list for  ConditionsApplyingToAccessAndUse is given
all limitations on access and use  are described in one gmd:MD_LegalConstraints

Messages
The metadata record set has 1 record(s) with errors for this assertion.
XML document 'test dataset.xml', record 'C2DFBDBC-5092-11E0-BA8E-B62DE0D72085': 
No valid resource constraint conditions is provided for this record.
A metadata record must have an gmd:accessConstraints or gmd:useConstraints element with an gmd:MD_RestrictionCode element with code list value "otherRestrictions".
Additionally, at least one instance of gmd:otherConstraints shall be given describing the actual conditions:
If no conditions apply, gmd:otherConstraints shall include a gmx:Anchor element pointing to the value "noConditionsApply" of the INSPIRE code list ConditionsApplyingToAccessAndUse. (http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/noConditionsApply)
If the conditions are unknown,gmd:otherConstraints shall include a gmx:Anchor element pointing to the value "conditionsUnknown" of the INSPIRE code list ConditionsApplyingToAccessAndUse (http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/conditionsUnknown).
In other cases, gmd:otherConstraints shall include a non-empty free text element with a textual description of the conditions in the language of the metadata.

XML sniplet:
gmd:resourceConstraints
gmd:MD_Constraints
gmd:useLimitation
gco:CharacterStringGebruiksbeperkingen (*), Toepassingen waarvoor de data niet geschikt is.</gco:CharacterString>
</gmd:useLimitation>
</gmd:MD_Constraints>
</gmd:resourceConstraints>

gmd:resourceConstraints
gmd:MD_LegalConstraints
gmd:accessConstraints
<gmd:MD_RestrictionCode codeListValue="otherRestrictions" codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode"/>
</gmd:accessConstraints>
gmd:otherConstraints
<gmx:Anchor xlink:href="https://creativecommons.org/publicdomain/mark/*/deed.nl">Geen beperkingen</gmx:Anchor>
</gmd:otherConstraints>

gmd:otherConstraints
<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/noConditionsApply">geen voorwaarden</gmx:Anchor>
</gmd:otherConstraints>
</gmd:MD_LegalConstraints>
</gmd:resourceConstraints>

				
		 
		<gmd:resourceConstraints>
			<gmd:MD_LegalConstraints>
				<gmd:accessConstraints>
					<gmd:MD_RestrictionCode codeListValue="otherRestrictions" codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode"/>
		
	</gmd:accessConstraints>
				<gmd:otherConstraints>
					<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations">geen beperkingen</gmx:Anchor>
				</gmd:otherConstraints>
			</gmd:MD_LegalConstraints>
		</gmd:resourceConstraints>

**Comment by fantamir** [comment]
Based on our finding, **item „Conditions for Access and Use“ allows following URI only:.**
http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/noConditionsApply
http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/conditionsUnknown

Therefore, the problem described above is probably in the element 
`<gmx:Anchor xlink:href="https://creativecommons.org/publicdomain/mark/*/deed.nl">Geen beperkingen</gmx:Anchor>`
In this element, different URI than the validator allows is used. We have the same problem. We intend to use an URI to Creative Commons licenses (e.g.  https://creativecommons.org/licenses/by/4.0/ ) or to other licenses in the Anchor element rather than only plain text. 
Using of Creative Commons licenses is recommended by many authorities and it is possible to expect, it will be widely used for harmonisation of licenses and conditions of INSPIRE data and services in the near future.
According to the INSPIRE Guideline, the metadata item 8.1 should contain either string available in the vocabulary ("No conditions apply", "Conditions unknown") or free text. Currently, filling of URI in the Anchor element is allowed for mentioned 2 vocabulary items only.

**Suggestion for deveolopers of the validator:**
Is it possible to check only if there is a string present in the element instead of current explicit checking of gco:CharacterString? 
Current validator code:
`and not(string-length($x/gmd:otherConstraints/gco:CharacterString) = 0) `
Proposed code modification:
`and not(string-length($x/gmd:otherConstraints/*) = 0)`

**Comment by idevisser** [comment]
I think your analyse is not solving  the issue.

The comment is on the validator Metadata (TG version 2.0) - BETA
The check on (character) string is not correct, the use of an anchor is required see C.18;

If no conditions apply the gmd:otherConstraints shall include a gmx:Anchor element pointing to the value "noConditionsApply" in the code list ConditionsApplyingToAccessAndUse28. If the conditions are unknown gmd:otherConstraints shall include a gmx:Anchor element pointing to the value "conditionsUnknown" in the code list ConditionsApplyingToAccessAndUse29.

The string  of the anchor element should not be used for validation, it is for human consumption, it contains the dutch translation of the value.  Please check in the anchor the value of the xlink:href. This should contain the URI of the value and is equal for all natural languages and for machine consumption.

**Comment by josemasensio** [comment]
Dear @idevisser,

We have review the test code and the error appears because of two reason. 

1. The codeList attribute of Restriction Code element must start with "http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode" value. 

2. The xlink:href attribute of Anchor (into gmd:otherConstraints element) must be:

   - http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/noConditionsApply
   - http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/conditionsUnknown

Best regards.

**Comment by idevisser** [comment]
Dear @bilbomaticaue 

1. The codelist attribute is a  general issue shall we discuss that in  #69 ?
2. In the xlink:href in the Anchor contains http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/noConditionsApply is available,  and in my opinion conform the INSPIRE requirements

a new test with the accepted codelist attribute gives no errors.

Can the messages be more specific,, in this case somthing like , the expected codelist attribute is not available? i now got the impression that something was wrong with the limitations on public access.

**Comment by josemasensio** [comment]
@idevisser the test has only one general error, so if any check fails this will return this generic error. 

@michellutz @MarcoMinghini maybe the message should be more specific? We can divide the general error into sub-errors.

**Comment by MarcoMinghini** [comment]
There are probably two reasons for the error:
1. the code list attribute (to be discussed together with #69)
2. the use of the `Anchor` encoding with `xlink:href` pointing to a URI which is different than the 2 specified in the TG Requirement C.18 (in this case to point to a CC license)

For point 2., we agree with @fantamir that the use of the `Anchor` encoding to specifiy other conditions (different than the two mentioned in C.18) should be allowed. Therefore, this should become a manual test.

This is supported by the following extract from C.18:

> In other cases gmd:otherConstraints shall include a Non-empty Free Text Element with a textual description of the conditions in the language of the metadata. This text shall include descriptions of terms and conditions, including where applicable, the corresponding fees **or an URL pointing to an online resource** where these terms and conditions are described.

and the following extract from page 18:

> Non-empty Free Text Element is an XML element with textual content encoded either using gco:CharacterString, gmx:Anchor or gmd:PT_FreeText element of the ISO 19139 XML Schema. See section 2.2 for more information.

We can discuss this in the next sub-group 2017.4 meeting.

**Comment by MarcoMinghini** [comment]
**2017.4 meeting 2019-07-17**

- The solution regarding the ISO code list is the one agreed in #69, i.e. the Validator should only check the value of the `codeListValue `attribute, and not the value of the `codeList `attribute.
- Regarding the use of `Anchor `with a URI different than those allowed by the TG, it is agreed that the Validator should check that there is at least one instance of the `gmd:otherConstraints` with either an `Anchor `pointing to a URI or a `gco:CharacterString`.
- the same issue is discussed in #71. 
- [ ] JRC to change the test, accordingly.

**Comment by josemasensio** [comment]
Dear @idevisser,

We have chacked the validation and there was no modification needed. Please, can you check that there is everything working smoothly?

Bes regards.

**Comment by josemasensio** [comment]
Dear @idevisser,

Does this solution worked?

Regards.

**Comment by josemasensio** [comment]
Afert some internal tests, we checked that everything is working fine, so we will mark as solved this issue.

Regards.
