### ISSUE TITLE
Metadata validation running into Gateway Timeout and Conflict

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#720]
- [ ] a description of the steps to reproduce your issue
I tried to validate a dataset metadata set

- [ ] the browser and version used
Firefox 97.0.2

- [ ] a screenshot illustrating the problem
![grafik](https://user-images.githubusercontent.com/34163838/157404528-e05f2a20-0509-4070-933d-0c4e0111c957.png)

- [ ] the Test Report (ideally as an attachment to the issue)
no test report as test does not start

- [ ] the URL of your service / the file you have uploaded or referenced (as
an attachment).
The file is confidential but I assume that this is more a system issue.

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,

the validator works fine now, it was a temporary unavailability/overload.

Please reopen the issue if the problem recurs.

**Comment by JohannaOtt** [comment]
@fabiovinci Issue is back
Seems like I cannot reopen the issue.
![grafik](https://user-images.githubusercontent.com/34163838/157683653-920ea56f-d0d8-47f5-b1c1-4df9b005f789.png)

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,

it seems it works now (https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID13bd658d-ed7f-432c-b827-fdb48540a684).

We will try to verify the error from your screenshot but without the resource under test, we are not able to reproduce the error.

I would advise you, if you use the validator on a daily basis, to install your own instance in order not to have problems of possible unavailability of the public instance, due, for instance, to an overload.

**Comment by jenriquesoriano** [comment]
Dear @JohannaOtt 

given the information provided, the most likely cause of this issue is, as @fabiovinci comments, an eventual overload that has prevented the data from being loaded. 
However, another option, following the information in the screenshot provided, may be that there is a problem with the cache in your browser and that it is storing old versions, as a CORS error does not seem appropriate for such a request.

Therefore, and given that we cannot reproduce it, we would recommend the installation of the validator on your premises following the [dockerfile deployment](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2022.0) to avoid these eventual unavailability at times of high concurrency of the service.

Regards,

**Comment by fabiovinci** [comment]
Since there were no further interactions we will close the issue.
Please reopen the issue or open a new one if the error persists.
