### ISSUE TITLE
er-gml.a.1: check for existence of Energy Resources features fails even if such features are present

### ISSUE THREAD

**Issue by florianesser** [INSPIRE-MIF/helpdesk-validator#729]
Dear Validator team,

When trying to validate an Energy Resources dataset in the INSPIRE Validator, we noticed that the test `er-gml.a.1` reports that there are no Energy Resources features present. I believe this to be caused by the respective check in the test case being too strict.

I have added a [reproduction case](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8303340/er-gml-a-1-repro.zip) including a minimal example that in my opinion should not cause er-gml.a.1 to fail and the respective validator report.

I have created [a patch](https://github.com/florianesser/ets-repository/commit/e3fbaba4f28a11b21ce9f4560fdd25186cbf230b) in my fork of the ets-repository which solves the problem for my test case.

**Comment by fabiovinci** [comment]
Dear @florianesser,

thank you for the patch, there is for sure an error for the data theme name but the check for the feature type should be ok, since it checks the presence of the `er-v:RenewableAndWasteResource` element.

In any case, we will review your suggestion.

I saw you used version 3 of the application schema which is no more supported, so I modified your dataset changing the schema from version 3 to 4 and it validates (see [report](https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID65a37945-ab58-4863-8c87-a34930bf6567)).

Attached the modified gml: [ER_vector_sample.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8306566/ER_vector_sample.zip).

I suggest you use the latest version of the application schemas.

**Comment by florianesser** [comment]
Dear @fabiovinci,

Thanks a lot for pointing me to the old schema version, I had totally missed checking that. I'm sorry for the fuss!

**Comment by fabiovinci** [comment]
Dear @florianesser,

No problem, glad I could help.

We will reopen this issue to take a trace of the fix of the typo you identified.

**Comment by arantzaetxebarria** [comment]
Dear @florianesser and  @fabiovinci 

We have updated the typo in the description of Conformance class: GML application schemas, Energy Resources, now it is on [staging ](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html)environmet. Could you test that it is correct? thanks

Regards

**Comment by fabiovinci** [comment]
The fix of the typo is fine.
We will include it in the next release.
