### ISSUE TITLE
Conformance Class 2c: 'INSPIRE data sets and data set series metadata for IACS' missing after local Installation of actual docker image

### ISSUE THREAD

**Issue by g-weber** [INSPIRE-MIF/helpdesk-validator#735]
In the local Installation (Docker Desktop) with the actual Docker image 
![image](https://user-images.githubusercontent.com/63788779/159899297-ce694911-98ba-448c-bc07-c7ec5b96fe09.png)

the optional Conformance Class 2c: 'INSPIRE data sets and data set series metadata for IACS' is missing and can't be selected.
![image](https://user-images.githubusercontent.com/63788779/159900237-28e471f7-6064-43ef-ace2-9968f9a86707.png)

**Comment by jenriquesoriano** [comment]
Dear @g-weber , 

we have checked the .zip file provided in the release and it seems to be correct.
![imagen](https://user-images.githubusercontent.com/25343632/159914343-b5fd9b62-ec01-4150-8fb5-91f8bec1253d.png)

Since the changes in the UI are in the javascript code, it is possible that some side-effects with the browser cache are present.
Could you please try to clean the browser cache and check it?

Thanks in advance. 

Best regards,

**Comment by g-weber** [comment]
Dear @jenriquesoriano ,

thanks a lot, cleaning of the cache solved my issue

Best regards
