### ISSUE TITLE
Metadata service: Spatial Data Service Type (MD SDS 3.5)

### ISSUE THREAD

**Issue by idevisser** [INSPIRE-MIF/helpdesk-validator#74]
I got an unexpected error on MD SDS 3.5: Spatial Data Service Type 

Message 
XML document 'Voorbeeld_Metadata_Services_2019.xml', record 'C2DFBDBC-5092-11E0-BA8E-B62DE0D72085': The element LocalName shall have an attribute codeSpace with value "http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType". Invalid: ''.

Based on the text in TG metadata i didn't conclude that the codeSpace attribue is required.

**Comment by josemasensio** [comment]
@idevisser it seems you are right. 

We have review the [SDS Type ATS](https://github.com/inspire-eu-validation/metadata/blob/2.0/metadata%20TG%202.0/sds/sds-type.md) and the [page 85 of TG](https://inspire.ec.europa.eu/sites/default/files/documents/metadata/inspire-tg-metadata-iso19139-2.0.1.pdf) and there is no reference about the codeSpace attribute value must be "http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType".

@michellutz @MarcoMinghini have we got to modify the ETS?

**Comment by michellutz** [comment]
@idevisser You are right - there is no requirement in the TG to refer to the http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType code list - even though for consistency with other requirements there probably should be. The code list is also used in the example.

I see two options - relax the ATS and ETS to comply with the current wording in the TG or modify the TG to be consistent with other requirements.

We should discuss this in the 2017.4 sub-group.

**Comment by idevisser** [comment]
other problem when  refering to the http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType code list, the translated values, for instance the dutch value "Raadpleegdienst" as translation of "view" are not accepted

**Comment by pvgenuchten** [comment]
See also https://inspire.ec.europa.eu/forum/discussion/view/261142/what-is-meant-with-language-neutral-value-tg-metadata-20

**Comment by AntoRot** [comment]
The use of codespace attribute should be only recommended.

**Comment by LauraAlemany** [comment]
Hello, 

In my opinion, in this case the best option is the second that @michellutz proposes: modify the TG to be consistent with other requirements.

Regarding to what @idevisser says, maybe you can tell the correct translation of "view" in dutch and I think the value could be changed, couldn't it @MarcoMinghini @michellutz ?

I have read the link @pvgenuchten has shared and I think is a good idea to use the gmx:anchor@xlink:href (http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoMapAccessService) in order to have no ambiguity.

Best regards, 
Laura

**Comment by MarcoMinghini** [comment]
**2017.4 meeting 2019-07-17**

- The use of `Anchor` would make it possible to use labels in national languages.
- However, the use of `xlink:href` inside `Anchor `instead of `codeSpace `inside `LocalName` is not allowed by the schema.
- [x] JRC to provide a proposal to solve the issue.

**Comment by michellutz** [comment]
It could be a solution to make the `codeSpace` attribute mandatory and use it in the same way as the Anchor, i.e. (in the example of a view service) use `http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/view` as the `codeSpace` attribute value, and then use the label of the value (e.g. "View Service") in the metadata language as the value of the element.

However, this would not be consistent with the definition of the type `gml:CodeType` (in ISO 19136 / GML 3.2.1), to which the spatial data service type metadata element is mapped: 

> `gml:CodeType` is a generalized type to be used for a term, keyword or name. (...)
>
> It adds an XML attribute `codeSpace` to a term, where the value of the `codeSpace` attribute (if present) shall indicate a dictionary, thesaurus, classification scheme, authority, or pattern for the term.

I.e. the `codeSpace` attribute identifies the vocabulary as a whole, not the value. The value, in turn should be given as the value of the element. This is why the TG currently mandates to include the code list value (e.g. view) in the element.

An alternative solution could therefore be to require the use of the **label** of the value (e.g. "View Service") in the metadata language as the value of the element and to recommend adding a reference to `http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/view` in the `codeSpace` attribute.

However, this would require changing the 
- Requirement 4.1  for Network Services, which currently requires the use of "view", "download", "discovery" or "transformation" as the value of the element.
- Requirement 5.1 for Invocable Services, which currently requires the use of "other" as the value of the element.

Also, it would make validation quite complicated, since we would have to check for all possible translations of the code list values.

All that said, I would recommend leaving the current TG requirements and tests as they are.

**Comment by fabiovin** [comment]
I quote Michael's recommendation and in my opinion, the test could be relaxed to not check the codespace attribute but it should still verify that the element value (`srv:serviceType/gco:LocalName`) is one of **_language-neutral_** **values defined in Part D3 of the IR** [Regulation 1205/2008].

I think that the use of a language-neutral value can improve the interoperability of the service because it could be easily identified by a search engine.

In my opinion, looking also at the note after the TG Requirement 3.5,

> NOTE Since the value domain of this metadata element is restricted to the values defined in Part D3 and the multiplicity of the element is 1, it is not possible to provide a more detailed type for the service (e.g. OGC:WMS or OGC:WMTS for a view service). Such addirional information can be provided in several ways in the metadata, e.g. using keywords, the srv:serviceTypeVersion element or the gmd:protocol element nested inside the gmd:transferOptions.

other metadata elements could be used to insert the service type using a value in the metadata language.

**Comment by AntoRot** [comment]
I agree with @fabiovin. 
I would add only a recommendation in the TGs on the use of the optional attribute codeSpace for the citation of the relevant register (http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType), keeping the example 4.3 including that attribute.

**Comment by josemasensio** [comment]
Dear @idevisser,
We just relaxed the test. Please, could you try it now and give us your feedback?

Best regards
