### ISSUE TITLE
language-affects-capabilities error for WFS

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#774]
Hi,

I am receiving a lot of generic server errors for the Language affects Capabilities tests. 
![grafik](https://user-images.githubusercontent.com/36956461/170275916-11f0ad75-3ed0-4f79-9a82-ca9fe3a7f24f.png)

The validator makes the following request: 
`https://test.haleconnect.de:443/ows/services/org.473.c5941548-88c4-4533-b65a-1e3e46015edb_wfs?#GETCAPABILITIESONLINERESOURCE=%23getCapabilitiesOnlineResource&LANGUAGE=&REQUEST=GetCapabilities&SERVICE=WFS&VERSION=2.0.0`

This request works as expected, however:
`https://test.haleconnect.de/ows/services/org.473.c5941548-88c4-4533-b65a-1e3e46015edb_wfs?REQUEST=GetCapabilities&LANGUAGE=&SERVICE=WFS&VERSION=2.0.0`

Can you please explain to me how the URL used by the validator is constructed and what it's testing?

Test report: 
[Test.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8771564/Test.zip)

Test WFS: https://test.haleconnect.de/ows/services/org.473.c5941548-88c4-4533-b65a-1e3e46015edb_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

Tested on staging instance.

Thank you.

Kind regards,
Kate

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

please consider that there are some errors in your GetCapabilities document:

1. The URL of the INSPIRE DLS schema is wrong:

![image](https://user-images.githubusercontent.com/22212406/170950321-f082a732-a1af-4539-91b1-cc64fa50999e.png)

2. The namespace of the ExtendedCapabilitie section should be "ows":

![image](https://user-images.githubusercontent.com/22212406/170950717-e0ebde7e-6b1b-4b23-aeee-dfe779ed3a3b.png)

I tried to validate a sample "static" xml GetCapabilities file and there are fewer errors.

Could you please try to correct the errors and re-validate the service?
Thanks

**Comment by Kate-Lyndegaard** [comment]
Dear @fabiovinci,

Thank you very much for spotting the issue with the incorrect namespace. That has now been fixed. Unfortunately my service is still receiving the same errors on staging. Is it really necessary to change the namespace prefix?

Service: https://test.haleconnect.de/services/bsp/org.473.c5f8123e-5003-4f01-a7ba-a2fa5d494a04/md/service/id_direct_download

Kind regards,
Kate

**Comment by Kate-Lyndegaard** [comment]
Dear @fabiovinci,

I just re-tested the original WFS linked in this issue description on production, and now all tests are failing.

![grafik](https://user-images.githubusercontent.com/36956461/175241693-27ea0cc8-0e2e-4109-84ca-abb3e624e1b4.png)

Test WFS: https://test.haleconnect.de/ows/services/org.473.c5941548-88c4-4533-b65a-1e3e46015edb_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

[Test run on 08 49 - 23.06.2022 with test suite Conformance Class Direct WFS.html.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8965021/Test.run.on.08.49.-.23.06.2022.with.test.suite.Conformance.Class.Direct.WFS.html.zip)

From my perspective this service should be error free.

Kind regards,
Kate

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

regarding the error you reported in the first comment, i.e. "_Language affects Capabilities tests_", the validator tries to retrieve the "SupportedLanguage codes" from this path: _/wfs:WFS_Capabilities/ows:OperationsMetadata/ows:ExtendedCapabilities/inspire_dls:ExtendedCapabilities[1]/inspire_common:SupportedLanguages/inspire_common:SupportedLanguage/inspire_common:Language_ (as indicated in the [ATS](https://github.com/inspire-eu-validation/download-wfs/blob/3.1/wfs-pre-defined/language-affects-capabilities.md#supported-languages)), and in your case it fails since your WFS has a different namespace.

So regarding your question:

> Is it really necessary to change the namespace prefix?

the answear is "yes".

Could you try to fix this error and re-validate the WFS?

**Comment by Kate-Lyndegaard** [comment]
Dear @fabiovinci,

I will fix it and get back to you.

Thank you.

Kind regards,
Kate

**Comment by stempler** [comment]
Dear @fabiovinci ,

I support @Kate-Lyndegaard on this matter and created a service where the namespace prefix for the extended capabilities was adapted according to your suggestion ([Capabilities link](https://test.haleconnect.de/ows/services/org.325.e008624c-433a-4a0e-ae10-05565d2f7fe5_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0)).

The "Request GetCapabilities in SupportedLanguage" test now succeeds, but the "Loop through Supported Language codes" test fails.

The "Request GetCapabilities in SupportedLanguage" test, even though it says it succeeds looks very suspicious, because it mentions a duration of `0.001 s` and as request this:

```
?#GETCAPABILITIESONLINERESOURCE=%23getCapabilitiesOnlineResource&LANGUAGE=&REQUEST=GetCapabilities&SERVICE=WFS&VERSION=2.0.0
```

Are these expected values?
Can you provide any hint on what could be the problem here?
Can you maybe share an example WFS where this test succeeds for comparison?

Thank you!

Test report: [Test run on 10_29 - 05.08.2022 with test suite Conformance Class Direct WFS.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9267062/Test.run.on.10_29.-.05.08.2022.with.test.suite.Conformance.Class.Direct.WFS.zip)

**Comment by Kate-Lyndegaard** [comment]
Dear @fabiovinci,

Would it be possible for you to provide an update on this issue? We would like to solve the problem, if possible.

Kind regards,
Kate

**Comment by Kate-Lyndegaard** [comment]
@fabiovinci Do you have an example service where this is working as expected?

**Comment by fabiovinci** [comment]
Dear all,

I tested the [latest WFS](https://test.haleconnect.de/ows/services/org.325.e008624c-433a-4a0e-ae10-05565d2f7fe5_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0) you provided and there is a schema validation error due to an empty element `<FeatureTypeList>`.

Could you please check?


![image](https://user-images.githubusercontent.com/22212406/219356166-3e8d4408-c748-4bbf-98af-65ccb07558a3.png)

**Comment by Kate-Lyndegaard** [comment]
Dear Fabio,

Thank you very much for your investigation. We will look into this issue and get back to you.

Kind regards,
Kate

**Comment by Kate-Lyndegaard** [comment]
Dear Fabio,

It is not clear to me that the empty `FeatureTypeList` is related. I tested two services- one with an empty `FeatureTypeList`, and one with a populated `FeatureTypeList`, and both services receive identical, failed reports. 

**Non-empty `FeatureTypeList` WFS:** https://haleconnect.com/ows/services/org.892.d331cd74-f3af-4c8c-916c-b94befc7660c_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

Failed ETF test report: 

[non-empty.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/10896040/non-empty.zip)

**Empty `FeatureTypeList` WFS:** https://test.haleconnect.de/ows/services/org.473.c5941548-88c4-4533-b65a-1e3e46015edb_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

Failed ETF test report:

[empty.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/10896051/empty.zip)

Do you have an example service where the test in the ticket description is passing, so that we can take a look?

Kind regards,
Kate

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

thank you for the sample WFS, looking again at your service it seems the error could be related to the wrong response of your server when the port number is added to the URL (see [my comment on issue 877](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/877#issuecomment-1323536979)).

In addition, it seems your service does not respond in the correct way when parameters are missing (see screenshot below). The right response should be `400 Bad Request`.
Could you please check?

![image](https://user-images.githubusercontent.com/22212406/223151245-83cd3cb9-155c-462c-8f2b-d3f330b53da4.png)

This is a WFS 100% valid: https://services.bioportal.hr/inspire/geos1/ps/wfs?ACCEPTVERSIONS=2.0.0&request=GetCapabilities&service=WFS&version=2.0.0 (see [report](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-reports/details.html?id=EID36e1a072-d619-48e2-acfa-c3596d08da0e)).

**Comment by Kate-Lyndegaard** [comment]
Dear @fabiovinci,

Unfortunately we have not yet been able to identify what is cauing this issue and why we are still seeing #772 for so many services. 

Can you please send me the exact request that the validator is making with the port number added? 

We would like to verify the response and reported exception.

Kind regards,
Kate

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

it seems there is an error on the server side since it does not respond if port 443 is added to the URL, e.g. https://haleconnect.com:443/ows/services/org.892.d331cd74-f3af-4c8c-916c-b94befc7660c_wfs?REQUEST=GetCapabilities&SERVICE=WFS&VERSION=2.0.0.
The URL works in the browser but it doesn't work in the validator or in other tools like Postman:

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/22212406/bf698462-47f1-41d7-bae9-594ffb0ae01c)

We investigated why the validator adds port 443 to the URL, but we didn't find the reason. This situation seems to occur with all services coming from the domain "https://haleconnect.com".

@stempler Could you please verify why your URLs do not respond if port 443 is added?

We will try to verify again why the validator adds the port **only** to "haleconnect.com" services.

**Comment by stempler** [comment]
@fabiovinci Thank you for further looking into this!

> We will try to verify again why the validator adds the port only to "haleconnect.com" services.

Why the port information is added is quite clear, since that's how the URLs are advertised in the GetCapabilities for the WFS operations - at least I assume that's what the validator uses. This is due to some functionality in deegree that adds the port to the URLs in case specific headers are set (I think it may be `X-Forwarded-Port`).

However I would not see any reason why that should matter, as `443` is the default HTTPS port and thus implicit in the URL without port.
I can't reproduce any different behavior.

Is there maybe a way to export the exact request you make from Postman? e.g. as a `curl` command?

If you can share with me date and time when you did such a request I could check if I can identify anything in the logs that would point to why it is treated differently. Otherwise it could be that it was just a temporary system problem and did have nothing to do with the presence of a port or not.

**Comment by fabiovinci** [comment]
Dear @stempler,

> Why the port information is added is quite clear, since that's how the URLs are advertised in the GetCapabilities for the WFS operations - at least I assume that's what the validator uses. 

Thanks for the hint, I hadn’t noticed before that the URLs in the GetCapabilities document contained the port. So, I think the reason is exactly this one.

I sent a GET request with Postman at 16:22, I'm not able to export any other detail, but I think you could reproduce the request by yourself.

**Comment by Kate-Lyndegaard** [comment]
Dear Fabio,

Once again, thank you for your continued patience and support in identifying the source of this problem. We tested removing the explicit port declaration in the URL and our service is now passing this test. 

I will close this issue.

Kind regards,
Kate

**Comment by fabiovinci** [comment]
Hi @Kate-Lyndegaard,

you are welcome. Happy to hear that the problem has finally been identified and solved.
