### ISSUE TITLE
I get an "error occured" message when starting dataset soil validation test

### ISSUE THREAD

**Issue by Claudia-WE** [INSPIRE-MIF/helpdesk-validator#778]
Dear Helpdesk Team,
it is not possible for me to validate a SOIL dataset. Neither with the staging version nor with the current official version.
1) Upload is successful
2) Click on Start Test also
--> An error occured...

[exporttest_lwf_boden.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8813235/exporttest_lwf_boden.zip)

Is this a problem with the platform ?
Best regards
Claudia

**Comment by jenriquesoriano** [comment]
Dear @Claudia-WE ,

we have just run the tests using your datasets in production and staging and have produced the test reports accordingly:
- [Production](https://inspire.ec.europa.eu/validator/test-reports/details.html?id=EID71d2a288-4525-4a71-be52-4626a619b4d8)
- [Staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EID2c5d3249-dd69-454b-8808-3046105fc0e5)

As we are not able to reproduce the issue consistently, we may presume it could be caused a temporary issue in the INSPIRE Reference Validator which could not assume the work load.

In case this issue happens in a recurrent basis, please, let us know.

Best regards,

**Comment by fabiovinci** [comment]
Dear @Claudia-WE,

as an additional comment, I would suggest you use the official schemas, so you should use https://inspire.ec.europa.eu/schemas/so/4.0/Soil.xsd instead of https://inspire.ec.europa.eu/draft-schemas/so/4.0/Soil.xsd. If there will be updates in the schema they will be published in the official schema repository (https://inspire.ec.europa.eu/schemas).

**Comment by fabiovinci** [comment]
Dear @Claudia-WE,

I confirm that the error was due to the temporary unavailability of the Validator, see the report of the validation excecuted some minutes ago (https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID79857405-fccf-41ee-99e1-9d899264b33e).

I'm closing the issue, please reopen it or open a new one if the error persists.
