### ISSUE TITLE
Geometry Validation Errors Reported for Correct Geometry in Administrative Boundary

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#788]
We are seeing errors when testing the AministrativeBoundary feature type in the Administrative Units theme.

We had originally opened the following case but due to delays in updating our services behavior we had it closed until we could re-evaluate and add certain capabilities to our service results.

Original case: https://github.com/INSPIRE-MIF/helpdesk-validator/issues/421

The validation error is the following…

_Conformance Class 'Data consistency, Administrative Units' > Boundary > au-dc.f.1: The geometry of each instance administrative boundary corresponds to an edge in the topological structure formed by the complete boundary graph, including the boundaries of all levels.
The dataset has 1 feature(s) with errors for this assertion.
XML document 'service.xml', AdministrativeBoundary 'auAdmBoundaryL.1727': The feature does not correspond to an edge in the topological structure formed by the complete boundary graph of all AdministrativeUnit features. It is not on the boundary of any AdministrativeUnit in the dataset._

The request URL is: https://inspiredemo.esri.com/arcgis/rest/services/au2/MapServer/exts/InspireFeatureDownload/service?REQUEST=GetFeature&VERSION=2.0.0&SERVICE=WFS&TYPENAMES=au:AdministrativeBoundary&COUNT=1&Namespaces=xmlns(au,http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fau%2F4.0)

We updated our service to return the Adminstrative Units geometry as internal links within the returned XML as suggested in the original case. The following request returns this format.

https://inspiredemo.esri.com/arcgis/rest/services/au2/MapServer/exts/InspireFeatureDownload/service?REQUEST=GetFeature&VERSION=2.0.0&SERVICE=WFS&TYPENAMES=au:AdministrativeBoundary&COUNT=1&Namespaces=xmlns(au,http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fau%2F4.0)&RESOLVE=local&RESOLVEDEPTH=1

However, we then get the following additional error...

_The dataset has 1 feature(s) with errors for this assertion.
XML document 'service.xml', AdministrativeBoundary 'auAdmBoundaryL.1727', property 'admUnit': The property references a resource at '#auAdmUnitS.110616', but no XML element with this ID can be found.
XML document 'service.xml', AdministrativeBoundary 'auAdmBoundaryL.1727', property 'admUnit': The property references a resource at '#auAdmUnitS.121206', but no XML element with this ID can be found._

I've attached a more detailed Word document, the Validation reports, and the downloaded service XML.

Can we get some assistance on this?

Thanks,
Robert

[AdminBoundary_GeometryIssue.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8911751/AdminBoundary_GeometryIssue.zip)

**Comment by fabiovinci** [comment]
Dear @robblis,

the error you mentioned is due to the "strange" encoding of the two AdministrativeUnit feature types, they are nested inside the "`<wfs:additionalObjects>/<wfs:SimpleFeatureCollection>`" element.

![image](https://user-images.githubusercontent.com/22212406/174017937-ead1c905-917d-4786-b69d-bf112e337b80.png)

If you correct the encoding, the dataset validates (see report https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDcd68e277-8e67-42b0-b15c-dc7b777cfe77).

![image](https://user-images.githubusercontent.com/22212406/174018571-a67019a8-70dd-4049-b7cb-aa438e3fa430.png)

As for the last remaining error, you need to use the INSPIRE codelist: http://inspire.ec.europa.eu/codelist/AdministrativeHierarchyLevel.

**Comment by robblis** [comment]
Hi @fabiovinci ,

Our developer pointed out that that using the wfs:additionalObjects/wfs:SimpleFeatureCollection is defined in the OGC WFS 2.0 standard in section 11.2.4. https://docs.opengeospatial.org/is/09-025r2/09-025r2.html#191

Is this not valid in this case?

Thanks,
Robert

**Comment by fabiovinci** [comment]
Dear @robblis,

your implementation is valid against OGC WFS specifications, even if not commonly used in INSPIRE implementations.

I suggest to move to a more simple structure, avoiding the further nesting of the AdministrativeUnit feature types.

In any case, if you want to keep it, we will investigate the error you received and try to fix it.

**Comment by robblis** [comment]
Hi @fabiovinci ,

I think we are going to need a fix for the error.

The developer pointed out that they wanted to keep the structure as is because it complies with the OCS WFS standard.

Thanks,
Robert

**Comment by fabiovinci** [comment]
Ok, @robblis, we will work on it.

@dperezBM, @arantzaetxebarria, could you please verify why the internal href links (in green) are not resolved?

It seems due to the nesting structure of the AdministrativeUnit feature types (in red).

![image](https://user-images.githubusercontent.com/22212406/175484049-0ec6297e-620c-4ec5-bcad-e3a9d26c42e4.png)

**Comment by arantzaetxebarria** [comment]
Dear @robblis 

The fix for the second example https://inspiredemo.esri.com/arcgis/rest/services/au2/MapServer/exts/InspireFeatureDownload/service?REQUEST=GetFeature&VERSION=2.0.0&SERVICE=WFS&TYPENAMES=au:AdministrativeBoundary&COUNT=1&Namespaces=xmlns(au,http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fau%2F4.0)&RESOLVE=local&RESOLVEDEPTH=1 is in staging environment, could you please verify that au-dc.f1 and au-ia.b8 tests are correct now?

Regarding the first example, as Administrative Units are referenced externally (with a URL) we will try to put au-dc.f1 as manually. When this  fix is implemented, we will back to you.

Regards

**Comment by robblis** [comment]
Hi @arantzaetxebarria 

We have re-tested the AU AdminstrativeBoundary test using RESOLVE and RESOLVEDEPTH parameters. The test succeeded with no errors regarding the missing AdministrativeUnits. We are now testing other themes (i.e. HY, TN) that also had the same problem with validating geometry.

Thanks for getting this fix applied,
Robert

**Comment by arantzaetxebarria** [comment]
Dear @robblis 

We have put the test au-dc.f.1 manual in case the Administrative Units are referenced externally like the first example https://inspiredemo.esri.com/arcgis/rest/services/au2/MapServer/exts/InspireFeatureDownload/service?REQUEST=GetFeature&VERSION=2.0.0&SERVICE=WFS&TYPENAMES=au:AdministrativeBoundary&COUNT=1&Namespaces=xmlns(au,http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fau%2F4.0) The update is in staging instance. Could you test and verify? thanks

Regards

**Comment by robblis** [comment]
Hi @arantzaetxebarria ,

We re-tested without using the RESOLVEDEPTH parameter and the test was successful.

Thank you for the fix. We'll test other themes that had the same issue.

Thanks,
Robert

**Comment by robblis** [comment]
Hi @arantzaetxebarria 

Has the additional fix been implemented in the TN theme?

Seems I still have to use the RESOLVEDEPTH parameter to pass the node on the end of a link feature.

Thanks,
Robert

**Comment by fabiovinci** [comment]
Dear @robblis,

thanks for the confirmation, we will include the fix in the next release.

The fix was not implemented for the TN theme, could you please open a dedicated issue?
