### ISSUE TITLE
Dataset validation : SpeciesDistributionUnit (SD-Theme)

### ISSUE THREAD

**Issue by Dnoack49** [INSPIRE-MIF/helpdesk-validator#798]
Dear all, 

I have validated these two SD-Datasets:

**SpeciesDistributionDataSet**
https://inspire.brandenburg.de/services/sd_arten_wfs?service=WFS&version=2.0.0&request=GetFeature&typenames=sd:SpeciesDistributionDataSet&Count=10

**SpeciesDistributionUnit**
https://inspire.brandenburg.de/services/sd_arten_wfs?service=WFS&version=2.0.0&request=GetFeature&typenames=sd:SpeciesDistributionUnit&Count=10

Here the zipped Testreports for both: [TestReports Annex III - Species distribution (SD).zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8990229/TestReports.Annex.III.-.Species.distribution.SD.zip)

For the **SpeciesDistributionUnit** I receive the following error in the **GML application schemas, Species Distribution** conformance class (_Basic test / sd-gml.a.1: Species Distribution feature in dataset_)

![grafik](https://user-images.githubusercontent.com/8046960/175900717-d270a75b-2da6-4453-bf39-f111aa2cfdcd.png)

As you see from the request above the Unit-file is not empty and has the required attributes. The Unit-objects are referenced in the Dataset via the member-association.

I came across the issue   [LU - Test ExistingLandUseSample returns Empty Spatial Dataset when selu:dataset node is populated #440 ](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/440)
in which a similar problem is described between the  Dataset and its Sample-features. At last the ATS was revised and ETS updated. Now my question is: Should only the **SpeciesDistributionDataSet** be validated for this theme (as there is no reference in the Units to the Dataset) or does the ATS/ETS need to be altered here as well?

Kind regards.

**Comment by fabiovinci** [comment]
Dear @Dnoack49,

the scope of the basic test is to advise the user that the "main" feature type is not present in the dataset, as in the case of the _SpeciesDistributionDataSet_ feature type.

This test may have a limitation when using a GetFeature request, as the response may contain only one specific feature type, in your case only the _SpeciesDistributionUnit_ feature type.

We are analyzing the issue, we could probably modify the ATS/ETS by adding also the the _SpeciesDistributionUnit_ feature type since elements of this feature type could exist also if the parent element (element of the _SpeciesDistributionDataSet_ feature type) does not exist.

**Comment by Dnoack49** [comment]
Dear @fabiovinci ,

thank you for your response. In fact, I have come across the same type of error for the AF-Theme regarding the FeatureTypes **Holding** and **Site** (TestReports: [test suite Annex III - Agricultural and aquaculture facilities (AF).zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9018396/test.suite.Annex.III.-.Agricultural.and.aquaculture.facilities.AF.zip))

Should I perhaps open another, separate issue for this?

Kind regards

**Comment by fabiovinci** [comment]
> Should I perhaps open another, separate issue for this?

It is very useful to have a separate issue even if the problem is similar.
We would be grateful if you could do that.

**Comment by fabiovinci** [comment]
The related [ATS](https://github.com/inspire-eu-validation/data-sd/blob/master/sd-gml/basic.md) has been modified accordingly, the change will be soon added in staging for test.

**Comment by arantzaetxebarria** [comment]
Dear @Dnoack49 

The implemented fix is in [staging ](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html) environment, could you please verify that now is working as expected?

Regards

**Comment by Dnoack49** [comment]
Dear @arantzaetxebarria ,
I have tested it and I confirm, that the error does not occur any longer and it works as expected.
Thank you!

**Comment by Dnoack49** [comment]
Dear @arantzaetxebarria 

as I said above the tests for the feature type SpeciesDistributionUnit are ok now.
Meanwhile I have tested the feature type SpeciesDistributionDataSet (for which no error was thrown at first).

However now I do receive the following error (tested on staging instance):
`XML document 'sd_arten_wfs.gml', SpeciesDistributionDataSet 'SpeciesDistributionDataSet_arten': The property 'SpeciesDistributionDataSet.member' has a value 'https://inspire.brandenburg.de/services/sd_arten_wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&OUTPUTFORMAT=application%2Fgml%2Bxml%3B+version%3D3.2&STOREDQUERY_ID=urn:ogc:def:query:OGC-WFS::GetFeatureById&ID=SpeciesDistributionUnit_10kmE464N322_92#SpeciesDistributionUnit_10kmE464N322_92' that cannot be retrieved using HTTP.`

![grafik](https://user-images.githubusercontent.com/8046960/178496346-76abd1e2-610d-42a0-af8a-667d2219ff4e.png)

Here is the Test Report:
[Test run on 10 34 - 12.07.2022 with test suite Annex III - Species distribution (SD).zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9093031/Test.run.on.10.34.-.12.07.2022.with.test.suite.Annex.III.-.Species.distribution.SD.zip)

could you give me a feedback on this, please.

Kind regards

**Comment by dperezBM** [comment]
Dear @Dnoack49

I have recentlychecked the sd-ia.b.1 validation of SpeciesDistribution DataSet (https://inspire.brandenburg.de/services/sd_arten_wfs?service=WFS&version=2.0.0&request=GetFeature&typenames=sd:SpeciesDistributionDataSet&Count=10) and it displays no errors on staging and production. 

So it may be due to a temporary unavailability or overload. I attach the reports in staging and production:
[Test run on 07_51 - 20.07.2022 with test suite Annex III - Species distribution (SD)_staging.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9147497/Test.run.on.07_51.-.20.07.2022.with.test.suite.Annex.III.-.Species.distribution.SD._staging.zip)

[Test run on 07_50 - 20.07.2022 with test suite Annex III - Species distribution (SD)_production.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9147498/Test.run.on.07_50.-.20.07.2022.with.test.suite.Annex.III.-.Species.distribution.SD._production.zip)

Regards.

**Comment by Dnoack49** [comment]
Dear @dperezBM 

I have run the test several times but still get  similar errors:

[Test run on 11 18 - 09.08.2022 with test suite Annex III - Species distribution (SD).zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9290598/Test.run.on.11.18.-.09.08.2022.with.test.suite.Annex.III.-.Species.distribution.SD.zip)

However, I noticed when I only include the member-elements in the gml which are listed in the error message ([sd_arten_wfs_k.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9290698/sd_arten_wfs_k.zip) the test passes:

[Test run on 14 36 - 09.08.2022 with test suite Annex III - Species distribution (SD).zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9290735/Test.run.on.14.36.-.09.08.2022.with.test.suite.Annex.III.-.Species.distribution.SD.zip)

Therefore, I also conclude that the error occurs due to an overload or too many member-elements.
