### ISSUE TITLE
We need more quota of request/week to call the inspire validator via token

### ISSUE THREAD

**Issue by pdorio** [INSPIRE-MIF/helpdesk-validator#810]
we are setting up our system and doing validation tests.

At this first stage, the 200 calls per week you have allocated to us are too few.

When fully operational it will certainly be enough, but for now we ask that you increase the calls to 2000 per week if possible.

**Name of the organisation:** _Ripartizione 28: Natura, paesaggio e sviluppo del territorio - Ufficio 28.1: Pianificazione territoriale e cartografia_

**Comment by fabiovinci** [comment]
Dear @pdorio,

the implementation of an API gateway to access the Validator was decided for limiting the massive use of the API by external organisations in order to prevent possible overload and unavailability of the service. 

The idea is that, if organisations need a higher use of the Validator compared to the limits that we set, they should deploy and use their own version of the Validator - which is indeed our suggestion for your specific case.

We are very sorry, but we already rejected similar requests in the past, so we cannot accept your request.
