### ISSUE TITLE
WFS Tests do not start

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#814]
Hi,

Currently I cannot start tests for WFS on production or on staging. My issue is similar to the issue reported in https://github.com/INSPIRE-MIF/helpdesk-validator/issues/778. I receive an "An error has occurred" message in a red toaster. 

I have received this error multiple times, testing on different days since the latest release. I would like to request a more descriptive error message when the validator cannot be accessed for testing purposes, if this is indeed the issue. I would like to understand if there is a problem with my resource, or a temporary, or other, issue with the validator. 

Test dataset series: https://geodienste.komm.one/ows/services/org.107.95c2b997-a6c1-4aa9-84b1-cf38fe9b2c4f_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

![grafik](https://user-images.githubusercontent.com/36956461/178735816-87f285b6-1682-4c98-b9f5-170afdc46aca.png)

Kind regards,
Kate

**Comment by robblis** [comment]
I'm getting the same errors testing Datasets.

**Comment by jenriquesoriano** [comment]
Dear @robblis , @Kate-Lyndegaard , 
during the time you experienced the issue, the validator was suffering of a massive usage where the queue was overflowing (16+ tests).
This usage momentarily prevented the proper operation of the validator by delaying its responses, so you obtained the reported behaviour. 
Subsequently, after processing the tests and decreasing the input rate, it returned to normal operation.
Currently the reported test has been able to run, please see:
https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID2fb0ac5a-4238-4409-928e-d747356a49fb

We are constantly monitoring the validator performance in order to try to prevent and improve the service, so thank you very much for reporting this issue and, if it happens again, please do not hesitate to contact us.

Regards,

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

I confirm that the error was due to the temporary unavailability of the Validator, see the report of the validation executed some minutes ago (https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDcf0cf350-ae0f-4616-877d-99c41fb24bb8).

I'm closing the issue, please reopen it or open a new one if the error persists.
