### ISSUE TITLE
Spatial Object Constraint Tests Failing for Sub Features

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#816]
Hi Validator Team,

When testing the BuildingPart feature with the Validator we get the following error.

The XML documents representing the spatial data set do not contain a feature of any of the spatial object types in the 'Buildings' application schemas. Therefore, the spatial data set cannot conform to this conformance class. If you have expected to find spatial objects from the application schema in the data set, please consult the statistics information to see the spatial object types that have been found.

Here is a GetFeature request available: https://agsinspire1.esri.com/arcgis/rest/services/buc/MapServer/exts/InspireFeatureDownload/service?REQUEST=GetFeature&SERVICE=WFS&VERSION=2.0.0&TYPENAMES=bu-core2d:BuildingPart&COUNT=10&namespaces=xmlns(bu-core2d,http://inspire.ec.europa.eu/schemas/bu-core2d/4.0)

This error is expected when testing for a 'Buildings' spatial object type within the BuildingPart feature type, we do want to still validate our BuildingPart schema is correct. There are other themes that have this issue. For example in the AF theme the af:Holding has a 'Holding' spatial object but when testing af:Site there would not be a 'Holding' spatial object but the current validator will test for this regardless of which feature being tested in the AF theme. 

LandCoverUnit feature also has the same issue which I had submitted in issue https://github.com/INSPIRE-MIF/helpdesk-validator/issues/789. From that issue we are advised not to test using LandCoverUnit.

Looking at these other features that have the same issue, maybe a document should be developed listing features that are not recommended testing using the GetFeature request, Or is it possible to put a condition in for these specific spatial object constraint tests to skip if the feature being tested is not relevant?

Thanks for any advice on this,
Robert

**Comment by fabiovinci** [comment]
Dear @robblis,

as for the other data themes, the scope of the basic test is to advise the user that the "main" feature type is not present in the dataset, as for the case of the _Building_ feature type.

In particular, for Building this is more relevant since the association between `Building` and `BuildingPart` is a composition, which means that BuildingPart(s) cannot exist if the related Building is not present.

In any case, due to the limitation when using a GetFeature request for the validation, as the response may contain only one specific feature type, we will relax the test by adding the `BuildingPart` feature type.

I updated the related [ATS](https://github.com/inspire-eu-validation/data-bu/blob/master/bu-gml/basic.md), @dperezBM, @arantzaetxebarria, could you please update the related ETS? Thanks

Please note that the fix for AF theme has been already introduced, see issue #809.

**Comment by arantzaetxebarria** [comment]
Dear @robblis 

The updated ETS is in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html) environment, could you please verify that now is working as expected?

Regards

**Comment by robblis** [comment]
Hi @arantzaetxebarria ,

We've re-tested BuildingPart. Tests succeeded.

Thanks,
Robert
