### ISSUE TITLE
WMS test fails because layer-name is not correct according with the harmonised layer given in INSPIRE collection

### ISSUE THREAD

**Issue by LoekRomer** [INSPIRE-MIF/helpdesk-validator#822]
The layer 'PS.ProtectedSitesNatureConservation' is configured as defined in the Technical Guidelines for the spatial data theme Protected Sites. When we look at our configuration and the GetCapabilities from the WMS, the layer name is configured in conformence with the Technical Guidelines and is exactly the same as it has been defined in the Technical Guidelines.

![image](https://user-images.githubusercontent.com/92917712/182100210-02e98267-80d7-4f45-a1f9-2b1724dd3c9c.png)

```
<Layer queryable="1">
<Name>PS.ProtectedSitesNatureConservation</Name>
```

WMS Capabilities: https://service.pdok.nl/provincies/aardkundige-waarden/wms/v1_0?request=getcapabilities&service=wms

It looks like an invalid test failure. Could you please give some insight in why this test fails? Is this an error in the inspire validator or is someting wrong with the WMS configuration?

**Comment by fabiovinci** [comment]
Dear @LoekCegeka,

you are, currently, receiving this error because there is only one layer name (`PS.ProtectedSite`) defined for Protected Sites theme by the IR 1089.

![image](https://user-images.githubusercontent.com/22212406/182416130-59a1a05f-a6b3-45ac-8e7b-6c88123f73c9.png)

The others are only "_Recommended_" by the TG.

In any case, due to the already endorsed and published change proposals ([see changes for WMS TG](https://github.com/INSPIRE-MIF/technical-guidelines/releases/tag/v2022.2)), this test will be changed or a new Conformance class will be added in order to validate WMS containing "additional" layers not defined by IR.

**Comment by fabiovinci** [comment]
Dear @LoekCegeka,

the changes to the WMS TG have been released in the [2022.2 TG release](https://github.com/INSPIRE-MIF/technical-guidelines/releases/tag/2022.2).

The related changes have been introduced in the ATSs (see [Abstract Test Suite: INSPIRE View Services Technical Guidance](https://github.com/inspire-eu-validation/view-service/tree/3.2.0)) and they will be implemented in the next release of the Validator.

**Comment by dperezBM** [comment]
Dear @LoekCegeka,

The solution is available in staging instance. Could you check that the solution is correct?

Regards

PS: @fabiovinci could you also check the solution?

**Comment by fabiovinci** [comment]
The solution is correct.
We can include the fix in the next release.
