### ISSUE TITLE
Direct WFS tests in locally running docker image

### ISSUE THREAD

**Issue by hwbllmnn** [INSPIRE-MIF/helpdesk-validator#826]
Hi,

when running the Direct WFS tests with the official docker image we constantly run into trouble. It doesn't matter which service is tested, the behaviour can be reproduced with any service URL.

Oftentimes the error will be `Object with EID EID670aad3a-d495-3f6c-87ba-c2052c539208 not found`, at other times we get a HTTP 500 - Executable Test Suite does not possess test items.

It is also possible to get the validator into a state where it can't run the tests any more just by running the WFS tests.

The same behaviour is observed when using our own docker image using the `.war` with the official ETS zip.

Due to the various ways this fails and due to it failing with many different service URLs it is unfortunately very hard for us to do a more thorough report without debugging deep into the test suite/the ETF code.

This might be related to #812

**Comment by jenriquesoriano** [comment]
Dear @hwbllmnn 

we have downloaded the official docker image with the command 

`docker run -it --name inspire-validator -p 8090:8090 docker.pkg.github.com/inspire-mif/helpdesk-validator/inspire-validator:2022.2`

Then we have tested some direct WFS tests but it didn't cause any error. 
Moreover, we don't know where to expect to appear the error which could help in the analysis of this issue. 

Could you provide us more information regarding your issue? 
Some tests that results in error, if the error is before or after the execution of the test or if it's after, which test step exactly results in error.

Furthermore, you mentioned that the Validator at some moments can't run more tests, this could be because you have reached the limit of the queue for running tests. This limit depends on the hardware you are using.

Please note that direct WFS relies on OGC Team Engine exectuion and it can take up to 20 minutes, so it may make the queue full and also can lead to different behaviours in the results.

Best,

**Comment by hwbllmnn** [comment]
Unfortunately I cannot give more details, I'd have to debug the validator/scripts a lot deeper in order to obtain more info.

I don't think the queue is the problem, the whole ETF becomes completely unresponsive after a couple of tests.

Regarding at what step the tests fail, it looks like the tests don't even start when getting the `Object with EID EID670aad3a-d495-3f6c-87ba-c2052c539208 not found` error.

**Comment by fabiovinci** [comment]
Dear @hwbllmnn,

do you still have the issue?
Did you try the latest version?

**Comment by hwbllmnn** [comment]
Looks like the issue was related to the https://github.com/etf-validator/etf-client/ , sorry for the noise.
