### ISSUE TITLE
HY Theme - hy-n:HydroNode The node is not located at the start or end of any link feature in the data set.

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#852]
Hi Validator Team,

We are testing our HY theme services and are seeing the following error.

Conformance Class 'Application schema, Hydrography - Network' > Geometry > hy-n-as.b.1: No free hydrographic nodes

The dataset has 1 feature(s) with errors for this assertion.
XML document 'service.xml', HydroNode 'netElementP.300501': The node is not located at the start or end of any link feature in the data set.

Here is the service we are using: https://inspiredemo.esri.com/arcgis/rest/services/hy_test/MapServer/exts/InspireFeatureDownload/service?REQUEST=GetFeature&VERSION=2.0.0&SERVICE=WFS&TYPENAMES=hy-n:HydroNode&COUNT=1&Namespaces=xmlns(hy-n,http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fhy-n%2F4.0)

We must use Resolve and ResolveDepth parameters to avoid the errors.

Can you add the fix for HY to recognize external links similar for the fix applied to the AU theme?
See the following issue for similar resolutions. https://github.com/INSPIRE-MIF/helpdesk-validator/issues/788

Thanks,
Robert

**Comment by fabiovinci** [comment]
Dear @robblis,

the test fails since the validator is not able to verify the geometries of the related `WatercourseLink` elements that are referenced in the `spokeEnd `and `spokeStart` elements.
It can only verify if the node is at the start or end of a watercourse link that is available in the same datasets.
Since you are validating single feature types (as in this case, only the HydroNode) the test doesn't work.

We are revising the related [ATS](https://github.com/inspire-eu-validation/data-hy/blob/master/hy-n-as/geometry.md) and we should change the first check from automated to automated/manual, so in case `WatercourseLink` elements are not available in the dataset you are testing, a manual check will be required.

In any case, I would suggest validating such types of datasets using the Resolve and ResolveDepth parameters, so you are sure your dataset conforms to all requirements.

**Comment by fabiovinci** [comment]
Dear @robblis,

we updated the [Geometry test](https://github.com/inspire-eu-validation/data-hy/blob/master/hy-n-as/geometry.md) in the ATS to report a message that requires manual checks if the HydroNode and the WatercourseLink feature types are not contained in the same dataset.

We will apply the fix in the ETS and let you know when it will be available in staging for testing.

**Comment by dperezBM** [comment]
Dear @robblis 

The fix for this issue is available in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) environment. Could you verify it?

Regards

**Comment by fabiovinci** [comment]
Dear all,
I tested the solution in staging and it works fine.

**Comment by robblis** [comment]
Hi @fabiovinci ,

I've ran a new test and no validation errors occurred.

Thanks for the fix.

Robert
