### ISSUE TITLE
Conformance Class 2c: IACS data sets GEMET theme keyword test not consistent

### ISSUE THREAD

**Issue by petbod-lm** [INSPIRE-MIF/helpdesk-validator#868]
I am updating our metadata editor to support the IACS code list and have found an issue with the Validator test 
Conformance Class 2c: INSPIRE data sets and data set series metadata for IACS

In the step IACS Dataset keyword | Keyword GEMET value the test will the URL in a gmx:Anchor element for the keyword.

The same metadata will pass the Conformance Class 1: INSPIRE data sets and data set series baseline metadata suite of tests with no errors: test step Identification | md datasets-and-series 1.4: INSPIRE Theme keyword checks that the keyword value of either a gmx:Anchor or gco:characterString are found in the Inspire Themes list.

Looking at the Technical Guidelines for IACS metadata  https://publications.jrc.ec.europa.eu/repository/handle/JRC121450  
TG 9 and TG 10 say that specific keyword values shall be provided in the GEMET themes keywords.
Nothing is mentioned about URLs GEMET theme keyword element.

Why is the Keyword GEMET value test in the Conformance Class 2c test suite looking for specific URLs when the TG says the correct keyword value is sufficient to pass the requirements?

I would suggest that the Keyword GEMET value test in the Conformance Class 2c test suite follow the same patten used in the Conformance Class 1 test suite so that the tests are consistent.

Here is the results of validating one of my test data set metadata files:
https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID27826da6-2c93-4fae-89cf-60dd7dc0a1ac

**Comment by fabiovinci** [comment]
Dear @petbod-lm,

thank you for opening the issue.

There seems to be a corner case since the two tests should be consistent.

Could you please send us the metadata under test to verify the encoding and to replicate the error? Thanks.

**Comment by petbod-lm** [comment]
[csw-inspire (50).xml.txt](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9930462/csw-inspire.50.xml.txt)
Here is the sample dataset I used in the Inspire Validadator test linked above

**Comment by dhdeangelis** [comment]
@fabiovinci is there anything new with this issue?

**Comment by fabiovinci** [comment]
Dear all,

we analyzed the error and the behavior of the validator and verified that the test related to Requirement 1.4 checks that the INSPIRE Theme keyword is provided as "_a Non-empty Free Text Element content in the language of the metadata_", so the encoding used in the metadata (see below) passes the test, even if the element is encoded as _Anchor_ and the link in the `href` attribute is wrong. In this case, the test strictly follows the TG Requirement 1.4, since the use of the anchor encoding is only recommended (TG Recommendation 1.5).

```xml
      <gmd:descriptiveKeywords>
        <gmd:MD_Keywords>
          <gmd:keyword>
            <gmx:Anchor xlink:href="http://rdfdata.eionet.europa.eu/inspirethemes/themes/17">Markanvändning</gmx:Anchor>
          </gmd:keyword>
```

On the contrary, the test related to the IACS keyword takes into consideration the encoding, as it should be, so in this case, the value checked is the URL in the `href` attribute, and since the URL is wrong the test fails.
For this reason, an encoding like the example below passes the test:

```xml
        <gmd:MD_Keywords>
          <gmd:keyword>
            <gmx:Anchor xlink:href="http://inspire.ec.europa.eu/theme/lu">Markanvändning</gmx:Anchor>
          </gmd:keyword>
```

What do you think about this behavior?

**Comment by petbod-lm** [comment]
Hi Fabio,
thanks you looking at this issue.  While i am not happy with the reasoning I do accept that our metadata is not using a current URL for Inspire themes in the gmx:anchor element.
I worry that as more tests are added to the Inspire validator they will add further confusion by repeating tests that return different results.  I would rather the ETF validator tests be consistant in what they are testing and how they test.
/Pete

**Comment by petbod-lm** [comment]
We have updated our catalogue to use the URLs expected by the IACS test.  I am happy to close the issue now
