### ISSUE TITLE
Conformance class 2c IACS: topicCategory = "farming" is not compliant to 2015/2008 Annex D2

### ISSUE THREAD

**Issue by Anja-AjLo** [INSPIRE-MIF/helpdesk-validator#873]
In TG metadata for IACS topicCategory has to be "farming". This is not compliant to IR 2015/2008 Annex D2, because "farming" does not match land use oder land cover. According to Annex D2 the correct match for land use is  'planningCadastre' and the correct match for land cover is 'imageryBaseMapsEarthCover'. So 'farming' only can be used as an additional topicCategory.

Therefore you need at least two topicCategory in the dataset-metadata. One is farming, the other is the one either matching land use (planningCadastre) or land cover (imageryBaseMapsEarthCover).

Running the tests comes up with an error, because the test for topicCategory  is not able to see there are two given topicCategories.

Here is the dataset-metadata for testing:
[feldbloecke_ni.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9952672/feldbloecke_ni.zip)

The example dataset for IACS (https://github.com/INSPIRE-MIF/helpdesk-validator/blob/master/examples/IACS_dataset_metadata_2.0_example.xml) has to be corrected as well. It is not compliant to 2015/2008 Annex D2. Although, the INSPIRE-validator cannot see the error because it does not check the matches between annex-theme / topicCategory from 2015/2005 Annex D2.

**Comment by fabiovinci** [comment]
Dear @Anja-AjLo,

thanks for identifying this error, since multiple values can be provided for the _topicCategory_ element your metadata should pass the test.
We will implement the related fix and let you know when it is available.

Regarding the example, I will add the additional topicCategory related to the declared data theme, leaving it commented until the fix is available in the production instance.

@arantzaetxebarria, @dperezBM, I improved the test method description in the [ATS](https://github.com/inspire-eu-validation/metadata/blob/2.0/iacs/IACS-datasets.md), could you please implement the related fix?

**Comment by dperezBM** [comment]
Dear @Anja-AjLo

The fix for this issue is available in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) environment. Could you verify it?

Regards

**Comment by fabiovinci** [comment]
Dear all,

I tested the solution in staging and it works fine.

**Comment by fabiovinci** [comment]
Dear @Anja-AjLo,

could you please confirm that the fix is ok? Thanks

**Comment by GDIAnja** [comment]
Sorry for the delay.

I tested with http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html (staging) for the official one is not available and has errors all of the time, getting worse every week.

In my opinion you fixed only half of the problem. 

I test the record having two topicCatergory farming / imageryBaseMapsEarthCover >> metadata is ok, that´s fine
I test the record having only the topicCategory imageryBaseMapsEarthCover >> metadata is wrong, that´s fine for farming is missing
I test the record having only the topicCategory farming >> metadata is ok, that´s wrong for imageBaseMapsEarthCover is missing. 

We have to have imageryBaseMapsEarthCover as well because of the INSPIRE-Annex "Bodenbedeckung" ("land cover"). Every keyword from GEMET - INSPIRE themes, version 1.0 has to have a matching Topic Category. But this test does not exist in INSPIRE Validator at all.

This affects all of dataset/series-metadata.

So if you ask me, if this ticket is ok? The test can see two topicCategories and one of the TopicCategories has to be farming, that´s true. But all  the rest of it is not tested for any dataset / series-metadata. This is perhaps another issue you would like to deal with.

In German Testsuite (GDI-DE Testsuite) we have the test for comparing INSPIRE-themes-keyword and TopicCategory. Metadata without the matching TopicCategory is not conformant in Germany. In EU it is ok concerning validaton via EU-Validator.

**Comment by fabiovinci** [comment]
Dear @GDIAnja,

thank you for your analysis, I think the issue you are raising needs to be managed in a separate issue.
From our point of you, this specific issue can be considered solved.
