### ISSUE TITLE
Validator returns an error for the theme Human health and safety (Safety) for allowed value

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#875]
Dear all,
why does the INSPIRE Validator return an error:  "Attribute 'nilReason' is not allowed to appear in element 'hh-sa:eventDescription'" when in the data specification for Human health and safety (Application schema Safety) this attribute is voidable? The dataset I'm testing is http://servisi.azo.hr/inspire/geos1/hh-sa/wfs?service=WFS&version=2.0.0&request=GetFeature&StoredQuery_Id=http://inspire.ec.europa.eu/operation/download/GetSpatialDataSet&CRS=http://www.opengis.net/def/crs/EPSG/0/3765&DataSetIdCode=0039&DataSetIdNamespace=http://geoportal.nipp.hr/hr/nipp/pp/&Language=eng 
and the report http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EID8a961b48-f2e8-49f1-ba6d-6d0bf6172311

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

the error is related to the test "Validation against declared schema" and it is present because you are using an old schema (https://inspire.ec.europa.eu/draft-schemas/hh-sa/3.0/HumanHealthSafety.xsd).

![image](https://user-images.githubusercontent.com/22212406/202201089-8da706c9-470b-4ffa-9c2e-ea4c14d4ed79.png)

The test "Validation against INSPIRE official schema" passes.

![image](https://user-images.githubusercontent.com/22212406/202202211-b13e9be0-5258-444b-8155-e081b2ef257a.png)

**Comment by Ana-SGA** [comment]
Dear @fabiovinci ,
thanks a lot!

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,
since the fix is on your side, we will close the issue.
