### ISSUE TITLE
Incorrect description of validation rule in quality of service README

### ISSUE THREAD

**Issue by arbakker** [INSPIRE-MIF/helpdesk-validator#880]
Issue concerns https://github.com/inspire-eu-validation/metadata repo.

Description of validation rule in quality of service [README](https://github.com/inspire-eu-validation/metadata/blob/2.0/sds-interoperable/quality-of-service.md)  is incorrect:

> Check that [Measurement Name](https://github.com/inspire-eu-validation/metadata/blob/2.0/sds-interoperable/quality-of-service.md#measurementName) element exists and it has an attribute xlink:href with URL value starting with "http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteriaCode/" and postfixed with one of values of code list QualityOfServiceCriteriaCode, see [Annex D.4 TG](https://github.com/inspire-eu-validation/metadata/blob/2.0/sds-interoperable/README.md#ref_TG_MD).

The url `http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteriaCode/` is not correct it should be `http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteria/`, see https://github.com/inspire-eu-validation/ets-repository/blob/28b66265aab8fc8228672283887475818aade1ab/metadata/2.0/sds/ets-md-sdsinteroperable-bsxets.xml#L299

Assuming that the situation in [ets-repository](https://github.com/inspire-eu-validation/ets-repository/blob/28b66265aab8fc8228672283887475818aade1ab/metadata/2.0/sds/ets-md-sdsinteroperable-bsxets.xml#L299)is  the correct implementation. Otherwise the issue is in the ets test :)

**Comment by fabiovinci** [comment]
Dear @arbakker,

thank you for raising that issue, we introduced the change in the ETS two years ago when we decided to consider that the right URL is http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteria ([see related issue](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/432#issuecomment-722252904)).

Now that the governance process for TG change proposals is in place, the issue should be discussed in the TG repository since there are discrepancies in the MD TG:

- In the section [4.4.3.1. Minimum estimated Quality of Service](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/metadata/metadata-iso19139/metadata-iso19139.adoc#4431-minimum-estimated-quality-of-service), there is the value "http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteriaCode/":

![image](https://user-images.githubusercontent.com/22212406/204286389-35af90f6-f7de-428d-a00e-0ad836f36f26.png)

- on the contrary, in [Annex D.3](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/metadata/metadata-iso19139/metadata-iso19139.adoc#d3-quality-of-service-criteria-code) there is the value "http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteria":

![image](https://user-images.githubusercontent.com/22212406/204286593-e51f93b1-1cdb-4bac-8888-b7cbbd6a93d5.png)

Could you please open a related [change proposal](https://github.com/INSPIRE-MIF/technical-guidelines/issues/new/choose) in the TG repository? Thanks

**Comment by fabiovinci** [comment]
Since the related TG change proposal was endorsed and the related changes will be included in the next TG release (due by the end of July), the codelist URL has been already updated in the [related ATS](https://github.com/inspire-eu-validation/metadata/blob/2.0/sds-interoperable/quality-of-service.md).

This issue can therefore be considered closed.
