### ISSUE TITLE
Element nz-core:specificExposedElementType not recognized

### ISSUE THREAD

**Issue by aquaterra** [INSPIRE-MIF/helpdesk-validator#883]
In theme Natural Risk Zones (NZ) the specificExposedElementType is not recognized in the validator: The property 'nz-core:specificExposedElementType' shall be provided.
But in the gml it is mapped as it should be:
![specificexposedelementtype](https://user-images.githubusercontent.com/12964257/203811529-e2f9bf37-cd23-4792-8f55-69b472439e93.PNG)

[ExposedElement.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/10085487/ExposedElement.zip)

**Comment by fabiovinci** [comment]
Dear @aquaterra,

it seems there is an error in the checks and/or in the error message for these two elements.

Regarding the first element, `exposedElementCategory`, your dataset should fail since the INSPIRE codelist value is in https (it should be in http).

Regarding the second one, `specificExposedElementType`, the value you provided is not correct since the related codelist is empty.

Moreover, the namespace you used is "nz" but it should be "nz-core", is probably for this reason that the element is not detected, so you should update your dataset.

In any case, we will analyze the related tests.

**Comment by aquaterra** [comment]
The tests do not give me an error on https/http. For none of the href's I have been using in this theme. There are at least 3 of them in this gml.

The codelist is empty for specificExposedElementType, but at least the validator should give another type of error. Even if I give an xsi:nil="true" the test still gives me the same error (as it could not find specificExposedElementType). It looks as no matter what I would give for this element, it still is not recognized.

The schema is nz-core as is given in the namespace definitions part. I only name it "nz" as alias, so I don't see what is wrong with it.

**Comment by dperezBM** [comment]
Dear @aquaterra

We have performed some changes in SpecificExposedElementType and the solution is available in staging. Could you check if it is correct?

Regards

**Comment by aquaterra** [comment]
Validator shows now all tests are OK.

![validator_OK](https://user-images.githubusercontent.com/12964257/208410904-f9d33317-2555-40c8-a81a-89a8e11b09b5.PNG)

Thank you for the changes!
