### ISSUE TITLE
Direct WFS Conformance Class is checking if the WFS conforms with the Pre-Defined WFS Conformance Class

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#890]
Hi,

I would like to request a repeal of the decision to include the WFS Pre-Defined WFS Conformance Class as a prerequisite for the Direct WFS Conformance Class in #476 

We provide Direct WFS services which are compliant with the IRs and Chapter 7 of the TGs. I cannot find any official guidance that states that a Direct WFS should provide stored queries. Stored queries are a requirement for WFS Pre-defined access described in Chapter 6 of the TGs, not Direct WFS. This, I assume, is why the WFS Pre-Defined WFS Conformance Class was not previously a prerequisite for the Direct WFS Conformance Class.

We serve WFS Direct Access services and ATOM feeds for Pre-defined access to the dataset instead of WFS Pre-defined and I do not think it is valid that we receive validation errors for Direct WFS services which do not support stored queries.

Thank you,
Kate

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,
thank you for raising the question and for sharing your implementation of a compliant Download Service.

In the end, you implemented a Download Service using an "hybrid implementation", so, you are right that your WFS doesn't need to follow the requirements contained in Chapter 6 of the TG.

![image](https://user-images.githubusercontent.com/22212406/207618061-df52ff90-52f9-46b3-950d-522fa9d07f84.png)

The solution is to remove the dependency of the "Conformance Class 'Direct WFS'" from the "Conformance Class 'Pre-defined WFS'", leaving this last one selected by default (in case of validation of a Download Service implemented only through WFS).

In case of validation of a Download Service implemented through "hybrid implementation" the "Conformance Class 'Pre-defined WFS'" can be deselected.

![image](https://user-images.githubusercontent.com/22212406/207620802-d02d4f90-7191-4e81-8646-19a96d66c78c.png)

**Comment by Kate-Lyndegaard** [comment]
Dear @fabiovinci,

Thank you so much!

Happy holidays,
Kate

**Comment by iuriemaxim** [comment]
@fabiovinci Probably more correct would be to add a new option here: 
![image](https://user-images.githubusercontent.com/20813598/211369722-bdf311b7-afd1-4545-bdac-026988e8fa37.png)
and to not remove the Predefined WFS Conformance class for WFS Download services.

I do not think is ok to declare a "WFS Download Service" being conformant without fulfilling Pre_defined WFS Conformance Class as this is de facto WFS implementation and this is the understanding of a "WFS Download Service" implementation according to the TG.

![image](https://user-images.githubusercontent.com/20813598/211410046-73b75336-00fe-419f-9e0a-abe3f1285ff2.png)


I think is ok to declare a "Hybrid implementation (ATOM+WFS)" being conformant without fulfilling the Pre_defined WFS Conformance Class., but Hybrid implementation should however test both ATOM and WFS without Predefined WFS Conformance Test. 

Otherwise it will not be possible to have a test that shows that a download service is compliant or not. But two tests should be performed and users should be aware of this, but this is something quite hidden and difficult to know, unless the user or the client that tests the solution that was implemented by a contractor read all the articles of the TGs and have a very clear understanding of the TGs to know exactly what to test. At least for me it is first time to hear that somebody made a "hybrid implementation". When I suggested to include the "Predefined WFS" into the  "WFS Download Service" I stated here https://github.com/INSPIRE-MIF/helpdesk-validator/issues/476, that:

"I know that someone could argue that part A of the IR could be implemented trough Atom and if so, than ”Download Service: Pre-defined Atom” Conformance class should be a pre-requisite. However this could be quite odd as the WFS already has all the functionalities listed in part A, just that the stored querries should be configured. In any case by looking at the linked metadata of the dataset and services it can be easily spoted by a machine if the download operations listed in part A of the IR where implemented trough WFS or ATOM.

In any case I did not heard of any implementation of a WFS Direct Access implementation that is using ATOM for Pre-defined access to the dataset instead of WFS Pre-defined access"

As stated by @Kate-Lyndegaard "We serve WFS Direct Access services and ATOM feeds for Pre-defined access to the dataset", so for a hybrid implementation it should be tested that Part A is covered by ATOM, and Part B & C are covered by WFS.

Probably would be important to have Hybrid implementation declared in metadata too, by including the links to both ATOM and WFS download services and to test this.
