### ISSUE TITLE
Issue building docker container for production

### ISSUE THREAD

**Issue by bcosyn** [INSPIRE-MIF/helpdesk-validator#935]
I wanted to adjust the parameters for deploying version 2023:1 of the inspire validator. https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2023.1
Docker build gives an error on the squid package. Could there be something wrong with the ets-rpeository.2023.1.zip file? Any advise is most welcome.
![image](https://user-images.githubusercontent.com/13509656/227515436-d3784e4a-fbdb-439a-b10f-179a5142ca37.png)

**Comment by fernandocuevasgdtel** [comment]
Dear @bcosyn,

thanks for communicating this issue.
As you have mentioned the issue is related to the non-existence of the squid package when building the image for deployment.
We are developing a different set-up to build the docker image to solve the issue.
In the meantime, please run the built docker image provided in v2023.1 release, according to the instructions provided in the [release notes](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2023.1).

Thank you for your attention,

Best,

**Comment by joachimnielandt** [comment]
Dear @fernandocuevasgdtel , 

Perhaps you are already considering this, but the current setup uses outdated base images I believe (references to missing debian repository servers etc). On my machine, that makes `apt-get update` file in the Dockerfile, for example.

Additionally, am I correct in thinking that the pre-built docker image you suggested is not configurable for a production environmment (modify the base url in the various required files)?

**Comment by jbarreroj** [comment]
Dear @joachimnielandt , @bcosyn , all,

You are correct about the non-possibility of modifying the URLs.
There have been some improvements related to this matter and it could be considered solved by now.
These issues are caused by the lack of maintenance of the image files, which caused the apt-get instructions to not function correctly.

To solve these issues, you will need to replace the following files with the ones that are attached:
* /Dockerfile
* /res/docker-entrypoint.sh
* /res/squid.conf

If you find any trouble reproducing these steps, please contact us.

Best
[files_docker.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/11634829/files_docker.zip)

**Comment by jenriquesoriano** [comment]
Dear @bcosyn ,

did you have the chance to validate the proposed solution?

Best

**Comment by DanielMartinPerezdeLeon** [comment]
Dear @bcosyn ,

we close this issue as a solution has been provided.

Please do not hesitate to open a new issue in case further input is needed.

Regards,
