### ISSUE TITLE
Validation fails for CRS URI

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#953]
Dear all,

after the Validator updates, we get error: 

"_XML document 'Koristenje_zemljista_iz_topografske_baze_Grada_Zagreba_2018_manji_uzorak.gml', ExistingLandUseObject 'ExistingLandUse_1': A spatial or temporal geometry uses an unexpected coordinate reference system with identifier 'http://www.opengis.net/def/crs/EPSG/0/3765' that cannot be retrieved. Every URI must be a HTTP URI in a CRS register that when retrieved with HTTP GET returns a definition of the reference system._". 

Is this caused by the INSPIRE Validator since there was no this kind of error in previous validations?

**Comment by jenriquesoriano** [comment]
Dear @Ana-SGA ,

thank you for reporting this issue, could you provide the data you are testing, so we can reproduce it?
Thanks.

Best,

**Comment by Ana-SGA** [comment]
Dear @jenriquesoriano,

staging instance now says it is ok, production won't test it says 502 error.

**Comment by jenriquesoriano** [comment]
Thanks @Ana-SGA .
Could you provide the input data in order to reproduce the issue?
Nevertheless, there are no substantial differences at this part of the code, but we would need this to discriminate it.
The error received in the report could be related to the actual availability of the URL: 'http://www.opengis.net/def/crs/EPSG/0/3765 but we cannot confirm without testing by ourselves.

Best,

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

it seems the error was due to the temporary unavailability of the OpenGIS repository.
Now the URL (http://www.opengis.net/def/crs/EPSG/0/3765) works, so the error should not be present.

I will close the issue, please reopen it if the problem persists, even if it has an external dependence.
