### ISSUE TITLE
HOW TO GO ABOUT THE TEST

### ISSUE THREAD

**Issue by silkysingz** [INSPIRE-MIF/helpdesk-validator#962]
Before reporting an issue with the INSPIRE Reference Validator deployed at JRC, please:
- check whether a similar issue has already been opened
- try to validate your resource after cleaning the browser cache (in case of error during the upload of the resource) 
- check the [list of known limitations](https://github.com/INSPIRE-MIF/helpdesk-validator/wiki/Known-limitations).

To report an issue, please replace these lines with a brief summary of your issue and the expected behaviour.

To help us investigate the issue, you may want to include:

- a description of the steps to reproduce your issue
- the browser and version used
- a screenshot illustrating the problem
- the Test Report (ideally as an attachment to the issue)
- the name of the Test that failed or better: change the `Level of Detail`
in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI`
- the URL of your service / the file you have uploaded or referenced (as
an attachment).

If your service is protected or you have confidential data that you cannot
upload here, you can request an email address to which you can send URLs / files.
Please note that issues cannot be investigated for services/datasets that we cannot
access.

**Comment by fabiovinci** [comment]
Dear @silkysingz,

could you please replace the example text of the issue template with a detailed description of your issue?
Thanks

**Comment by fabiovinci** [comment]
Dear @silkysingz,

if your issue is entirely described by the title "HOW TO GO ABOUT THE TEST", please go to the following link: https://inspire.ec.europa.eu/validator/test-selection/index.html, and after selecting the relevant resource you can start the test. The field for the upload of the resource will appear after the completion of the antispam.

I hope this helps and answers your question.
I will close the issue, please reopen it adding a more detailed description of the problem if you weren't able to solve it.
