### ISSUE TITLE
Failed validation of voidable LC nomenclatur elements embedded/external description

### ISSUE THREAD

**Issue by FrLemmel** [INSPIRE-MIF/helpdesk-validator#969]
Hi, 

I am currently trying to validate a preliminary GML for AII LCV data. I run into the issue that the validator reports a missing embedded or external description when testing against the LCN schema. 
Looking at the UML Model it becomes apparent, that these elements are voidable. Hence, I am a bit confused on how to solve this issue and make the GML valid. The attached zip contains the .gml file currently tested.

[lc_to_gml.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/11893451/lc_to_gml.zip)

And here is the latest test report:
https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID7d47d0ee-98dd-4a97-a9ca-36296c2a08e5

There is also the error of GML and INSPIRE GML Application Schema validation. Might this be in relation to the above mentioned error ?

Unfortnuately I cannot run any tests in the staging environment, as I am not prompted further after setting al the parameters.

**Comment by fabiovinci** [comment]
Dear @FrLemmel,

I had a look at your dataset and it contains the following errors:

1. Dates of the beginLifespanVersion attribute are wrong because the dataType of this eleemnt is `dateTime`, so they should have the following format: `2018-05-20T00:00:00`
2. The schemaLocation attribute should contain the declaration of the gml schema since the validator is not able to retrieve it from the INSPIRE schema, so it should be: `xsi:schemaLocation="http://inspire.ec.europa.eu/schemas/lcv/4.0 http://inspire.ec.europa.eu/schemas/lcv/4.0/LandCoverVector.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd">`
3. The `embedded description` OR the `external description` shall be provided. Even if the two attributes are voidable and have multiplicity equal to zero, there is a constraint that requires one of the two (see screenshot below).

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/22212406/14eb5289-48bb-4d23-accc-a8926e60c0d2)

I hope that this helps to clarify.

**Comment by FrLemmel** [comment]
Thanks @fabiovinci for clarification. I will try to implement it in the following days and re-check with the validator. If needed I will come back to this ticket or close it when being successful.
