### ISSUE TITLE
Instructions for configuring reference validator with forwarding proxy

### ISSUE THREAD

**Issue by mwjsanders** [INSPIRE-MIF/helpdesk-validator#978]
Because of issues https://github.com/INSPIRE-MIF/helpdesk-validator/issues/972, https://github.com/INSPIRE-MIF/helpdesk-registry/issues/42 and to reduce the many calls to the inspire registry, we try to configure a locally running reference validator in docker (as described in the [release notes](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2023.2)) to use a proxy cache. We have created a proxy cache using nginx.
We now need to configure this proxy cache as a forwarding proxing in the reference validator, but there are no clear instructions for this. Setting the http_proxy environment variable in the reference validator container does does not work.

Please provide instructions on how to configure a forwarding proxy for the inspire reference validator running in a docker container.

**Comment by DanielMartinPerezdeLeon** [comment]
Dear @mwjsanders ,

thank you for reaching out to us with your issue.
As far as we understand you are trying to create a reverse proxy in order to manage the requests from the ETF to the external resources (INSPIRE Registry).
For the existing set-up of the INSPIRE Reference Validator, Nginx is not intended to be used as a caching proxy (while Nginx does have caching capabilities, its primary role is that of a web server).

In order to manage issues with a reverse proxy, you can make use of the installed instance of Squid + Apache within the INSPIRE Reference Validator Docker, configured with INSPIRE URLs.

By using this Squid instance within your INSPIRE Reference Validator Docker, it should resolve any cache redirection issues you may encounter with INSPIRE resources, and there should be no need for any additional cache proxy configurations.

Additionally, please note that using another Nginx instance with the ETF Docker could potentially misconfigure the original Nginx used in the Docker, which might hinder the proper functioning of your instance.

Finally, we suggest to use the [latest version of the INSPIRE Reference Validator (v2023.3)](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2023.3) in order to be kept up to date.

If you have any further questions or concerns, please don't hesitate to contact us.

Regards,

**Comment by fabiovinci** [comment]
Dear user,

we hope the solution provided helps you to resolve the issue.
So we close this issue.
If there are any further questions or problems, please do not hesitate to reopen it or create a new issue.
