### ISSUE TITLE
roblem with local ETF validator

### ISSUE THREAD

**Issue by trodin** [INSPIRE-MIF/helpdesk-validator#997]
Before reporting an issue with the INSPIRE Reference Validator deployed at JRC, please:
- check whether a similar issue has already been opened
- try to validate your resource after cleaning the browser cache (in case of error during the upload of the resource) 
- check the [list of known limitations](https://github.com/INSPIRE-MIF/helpdesk-validator/wiki/Known-limitations).

To report an issue, please replace these lines with a brief summary of your issue and the expected behaviour.

To help us investigate the issue, you may want to include:

- a description of the steps to reproduce your issue
- the browser and version used
- a screenshot illustrating the problem
- the Test Report (ideally as an attachment to the issue)
- the name of the Test that failed or better: change the `Level of Detail`
in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI`
- the URL of your service / the file you have uploaded or referenced (as
an attachment).

If your service is protected or you have confidential data that you cannot
upload here, you can request an email address to which you can send URLs / files.
Please note that issues cannot be investigated for services/datasets that we cannot
access.

**Comment by trodin** [comment]
We uploded file gml with data of Geologic map to local instance of ETF validator.
However, we still have issues with the test report. The data and our report are in the attachment.

Can you check what is wrong with our istance of validaor so we have errors in validation?

Thanks.
Tanja
[gk300_inspireV5_pom_1.zip](https://github.com/INSPIRE-MIF/hel
[ETF Test Report.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/12712445/ETF.Test.Report.zip)
pdesk-validator/files/12712430/gk300_inspireV5_pom_1.zip)

**Comment by trodin** [comment]
[gk300_inspireV5_pom_1.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/12712489/gk300_inspireV5_pom_1.zip)

**Comment by fabiovinci** [comment]
Dear @trodin,

could you please save the test report in HTML format?
I'm not able to open the failed Conformance classes to see the error details.

**Comment by trodin** [comment]
[](url)
[ETF Test Report.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/12715288/ETF.Test.Report.zip)
It is not possible to drag and drop html file.

**Comment by fabiovinci** [comment]
I was able to open the HTML version and to had a look at the errors.

Regarding the error:
`_XML document 'gk300_inspireV5_pom_1.gml': 1:1454: cvc-elt.1.a: Cannot find the declaration of element 'gml:FeatureCollection'._, `,
you should add the gml schema in the "schemaLocation" attribute:
`xsi:schemaLocation="http://inspire.ec.europa.eu/schemas/ge-core/4.0 http://inspire.ec.europa.eu/schemas/ge-core/4.0/GeologyCore.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd"`

Regarding the errors related to the unavailability of the codelist values (e.g.` System error in the Executable Test Suite. Please contact a system administrator. Error information:Code list http://inspire.ec.europa.eu/codelist/GrammaticalNumberValue cannot be accessed.`), they could be due to a temporary unavailability of the INSPIRE registry or an error in accessing the resources by your instance.

Regarding the errors related to the "Feature references" tests (e.g. `XML document 'gk300_inspireV5_pom_1.gml', GeologicUnit 'GeologicUnit_113': The property 'geologicHistory' has a reference to element '#GeologicEvent_GeologicUnit_113' but there is not any element with a gml:id attribute with that value.`), they are related to the lack of the related features in the dataset.

Could you try to fix your dataset and validate it again?

**Comment by trodin** [comment]
Thank you for comments. I will try to fix it and let you know.

I was worried about "error in accessing the resources by your instance" because earlier we had also problems with accessing code lists by our instance of validator and we could not fix that.

Tanja

**Comment by trodin** [comment]
My new report:

https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDef27a4e6-3106-4d9a-8f40-4f710a165828

Can you check?

Thank you
Tanja

**Comment by fabiovinci** [comment]
Hi @trodin,

regarding the errors related to the "Feature references" tests, they are related to the lack of the related features in the dataset.

The other errors are not clear, so could you please share your data?

**Comment by trodin** [comment]
I did copy of your gml shema in shema location but I don't know what is now wrong .
xsi:schemaLocation="http://inspire.ec.europa.eu/schemas/ge-core/4.0 http://inspire.ec.europa.eu/schemas/ge-core/4.0/GeologyCore.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd"

The dataset is here
[gk300_inspire_Slavko3.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/12890634/gk300_inspire_Slavko3.zip)

**Comment by fabiovinci** [comment]
Hi @trodin,

I revalidated your resource (https://inspire.ec.europa.eu/validator/test-reports/details.html?id=EID606a86f5-00e4-4d87-9a8c-c9c34d577225) and the system errors are no longer present, they were probably due to temporary unavailability of the INSPIRE application schema.

**Comment by trodin** [comment]
Ok, thank you very much for your support.

Regards,
Tanja

**Comment by fabiovinci** [comment]
Dear @trodin,

I will close the issue, please reopen it or open a new one if the error persists.
